# ETL — S&P 500 (mensual 2015–2025) con Refinitiv

**Objetivo:** construir un panel mensual (firm × month) a partir de datos 100% Refinitiv (Eikon/RDP) y exportar el dataset final para estimaciones econométricas.

**Inputs principales:**
- Universo de firmas: `empresas_tickers_test.csv`
- (Opcional) Excels de bonos corporativos: carpeta local (ver Config)

**Outputs principales:**
- `data/clean/panel_master.parquet`
- `data/clean/data_dictionary.csv`
- `outputs/qa/qa_report.csv` (o similar)

**Notas:**
- Requiere credenciales Refinitiv vía variable de entorno `EIKON_APP_KEY`.
- Algunas descargas pueden tardar y están sujetas a rate limits (HTTP 429). El notebook aplica pausas/reintentos donde corresponde.

## 2) Imports

In [ ]:
# ======================
# IMPORTS E INICIALIZACIÓN DE REFINTIV
# ======================

from pathlib import Path
import os
from dotenv import load_dotenv, find_dotenv
import eikon as ek

# Carga de variables de entorno (archivo .env en la raíz del proyecto).
env_path = find_dotenv(usecwd=True)
load_dotenv(env_path, override=True)

EIKON_APP_KEY = os.environ.get("EIKON_APP_KEY")

assert EIKON_APP_KEY, (
    "Falta la variable de entorno EIKON_APP_KEY. "
    "Definila en el .env antes de ejecutar el notebook."
)

# Inicialización de sesión Refinitiv/Eikon.
ek.set_app_key(EIKON_APP_KEY)

Using key prefix: 00f40e04

In [13]:
# --- Standard library
from __future__ import annotations

import os
import time
import logging
from pathlib import Path
from typing import Iterable, Optional

# --- Third-party
import numpy as np
import pandas as pd

# --- Refinitiv (Eikon)
import eikon as ek

## 3) Config

In [14]:
# ======================
# CONFIGURACIÓN GENERAL DEL ETL
# ======================

# Horizonte temporal del panel mensual (2015-2025).
START_DATE = "2015-01-01"
END_DATE   = "2025-12-31"

# -------------------------------------------------
# Estructura de directorios del proyecto
# -------------------------------------------------
PROJECT_ROOT = Path.cwd().resolve().parent

DATA_DIR   = PROJECT_ROOT / "data"
INPUT_DIR  = DATA_DIR / "inputs"
RAW_DIR    = DATA_DIR / "raw"
CLEAN_DIR  = DATA_DIR / "clean"

OUTPUT_DIR = PROJECT_ROOT / "outputs"
QA_DIR     = OUTPUT_DIR / "qa"
LOG_DIR    = OUTPUT_DIR / "logs"

for p in (INPUT_DIR, RAW_DIR, CLEAN_DIR, QA_DIR, LOG_DIR):
    p.mkdir(parents=True, exist_ok=True)

# -------------------------------------------------
# Inputs
# -------------------------------------------------

# Universo base de empresas.
UNIVERSE_FILE = INPUT_DIR / "empresas_tickers_test.csv"

# Exportes consolidados de bonos corporativos desde Refinitiv Workspace.
BONDS_DIR = INPUT_DIR / "new_bonds"
BOND_BATCH_FILES = [
    BONDS_DIR / "first_batch.xlsx",
    BONDS_DIR / "second_batch.xlsx",
    BONDS_DIR / "third_batch.xlsx",
]

# -------------------------------------------------
# Outputs
# -------------------------------------------------

OUT = {
    "universe_firms": CLEAN_DIR / "universe_firms.parquet",
    "firms_metadata": CLEAN_DIR / "firms_metadata.parquet",
    "bonds_metadata": CLEAN_DIR / "bonds_metadata.parquet",

    "equity_prices_daily": RAW_DIR / "equity_prices_daily.parquet",
    "equity_returns_monthly": CLEAN_DIR / "equity_returns_monthly.parquet",

    "market_prices_daily": RAW_DIR / "market_prices_daily.parquet",
    "market_returns_monthly": CLEAN_DIR / "market_returns_monthly.parquet",

    "bonds_universe_full": CLEAN_DIR / "bonds_universe_full.parquet",
    "oas_spreads_monthly_bond": RAW_DIR / "oas_spreads_monthly_bond.parquet",
    "cds_spreads_daily": RAW_DIR / "cds_spreads_daily.parquet",

    "panel_master": CLEAN_DIR / "panel_master.parquet",
    "data_dictionary": CLEAN_DIR / "data_dictionary.csv",
    "qa_report": QA_DIR / "qa_report.csv",
}

EIKON_APP_KEY = os.environ.get("EIKON_APP_KEY")
assert EIKON_APP_KEY, (
    "Falta la variable de entorno EIKON_APP_KEY. "
    "Ejemplo (Windows PowerShell): $env:EIKON_APP_KEY='TU_KEY'"
)

REQUEST_PAUSE_SEC = 0.25
RETRY_MAX = 5
RETRY_BACKOFF_SEC = 2.0

PROJECT_ROOT: C:\Users\vidar\OneDrive\Desktop\UDESA\Tesis\Tesis-main
INPUT_DIR: C:\Users\vidar\OneDrive\Desktop\UDESA\Tesis\Tesis-main\data\inputs
BONDS_DIR: C:\Users\vidar\OneDrive\Desktop\UDESA\Tesis\Tesis-main\data\inputs\new_bonds
BOND_BATCH_FILES: ['first_batch.xlsx', 'second_batch.xlsx', 'third_batch.xlsx']
UNIVERSE_FILE: C:\Users\vidar\OneDrive\Desktop\UDESA\Tesis\Tesis-main\data\inputs\empresas_tickers_test.csv

## 4) Logging y algunos helpers

In [15]:
# ======================
# LOGGING + HELPERS
# ======================

def _build_logger(name: str = "etl") -> logging.Logger:
    logger = logging.getLogger(name)
    if logger.handlers:
        return logger  # evita duplicar handlers si re-ejecutás la celda

    logger.setLevel(logging.INFO)

    fmt = logging.Formatter("%(asctime)s | %(levelname)s | %(message)s", "%Y-%m-%d %H:%M:%S")

    sh = logging.StreamHandler()
    sh.setFormatter(fmt)
    logger.addHandler(sh)

    fh = logging.FileHandler(LOG_DIR / "etl.log", encoding="utf-8")
    fh.setFormatter(fmt)
    logger.addHandler(fh)

    return logger


logger = _build_logger("etl")


def ensure_datetime(df: pd.DataFrame, col: str) -> pd.DataFrame:
    """
    Fuerza `df[col]` a datetime (naive, sin tz). No altera otras columnas.
    """
    if col not in df.columns:
        raise KeyError(f"Columna '{col}' no existe en df.")
    out = df.copy()
    out[col] = pd.to_datetime(out[col], errors="coerce")
    # Si viniera con tz, lo baja a naive
    if getattr(out[col].dt, "tz", None) is not None:
        out[col] = out[col].dt.tz_localize(None)
    return out


def safe_write_parquet(df: pd.DataFrame, path: Path, index: bool = False) -> None:
    """
    Escribe parquet y loguea tamaño y destino.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    df.to_parquet(path, index=index)
    logger.info(f"Output -> {path.as_posix()} | rows={len(df):,} cols={df.shape[1]}")


def sleep_request(pause_sec: float = REQUEST_PAUSE_SEC) -> None:
    time.sleep(pause_sec)

## 5) Conexión a refinitiv

In [16]:
# ======================
# REFINTIV CONNECTION
# ======================

ek.set_app_key(EIKON_APP_KEY)
logger.info("Refinitiv/Eikon: APP_KEY seteada.")

2026-03-24 19:11:44 | INFO | Refinitiv/Eikon: APP_KEY seteada.
2026-03-24 19:11:44,571 P[19164] [MainThread 20064] Refinitiv/Eikon: APP_KEY seteada.

# Construcción del universo ampliado del S&P 500 desde Refinitiv

En esta sección se reemplaza la lista manual reducida de empresas por un universo ampliado de firmas del S&P 500 descargado directamente desde Refinitiv.

## Objetivo
Construir una base de firmas más amplia y trazable, manteniendo compatibilidad con el pipeline actual.

## Cambio introducido
Se descarga el universo de constituyentes del S&P 500 mediante Refinitiv y se genera un archivo `empresas_tickers_test.csv` con el mismo formato básico ya utilizado por el notebook:

- `Issuer`
- `Ticker`

Además, se agregan columnas adicionales útiles para robustecer los merges y la trazabilidad:

- `RIC`
- `ISIN`
- `CUSIP`
- `PermID`
- clasificaciones GICS.

## Motivación
Hasta ahora, la muestra partía de una lista manual de firmas, lo que restringía el universo de forma arbitraria y dificultaba una expansión escalable.

Al construir el universo directamente desde Refinitiv:

- se elimina una restricción técnica importante;
- se preserva el criterio conceptual de trabajar dentro del S&P 500;
- se facilita la posterior selección de emisores elegibles en función de la disponibilidad de OAS.

## Resultado esperado
A partir de este bloque:

- el universo de firmas deja de depender de una selección manual;
- el archivo de entrada principal del notebook se mantiene compatible con las celdas existentes;
- se mejora la cobertura potencial sin romper el pipeline.

In [17]:
# ======================
# UNIVERSO S&P 500 (REFINITIV)
# Genera un archivo ampliado compatible con el pipeline existente
# ======================

SPX_CHAIN = "0#.SPX"

SPX_FIELDS = [
    "TR.CommonName",
    "TR.TickerSymbol",
    "TR.RIC",
    "TR.ISIN",
    "TR.CUSIP",
    "TR.PermID",
    "TR.HeadquartersCountry",
    "TR.GICSSectorName",
    "TR.GICSIndustryGroupName",
    "TR.GICSIndustryName",
    "TR.GICSSubIndustryName"
]

def clean_str_series(s):
    return (
        s.astype("string")
         .str.strip()
         .replace({"": pd.NA, "nan": pd.NA, "None": pd.NA})
    )

spx, err = ek.get_data([SPX_CHAIN], SPX_FIELDS)

if err is not None and len(err):
    logger.warning(f"Warnings Refinitiv universo S&P 500: {err}")

if spx is None or spx.empty:
    raise RuntimeError("No se pudo descargar el universo S&P 500 desde Refinitiv.")

logger.info(f"Universo S&P 500 descargado | filas={len(spx):,} cols={spx.shape[1]}")

spx.columns = [str(c).strip() for c in spx.columns]

rename_map = {
    "Company Common Name": "Issuer",
    "Ticker Symbol": "Ticker",
    "RIC": "RIC",
    "ISIN": "ISIN",
    "CUSIP": "CUSIP",
    "Country of Headquarters": "HeadquartersCountry",
}
spx = spx.rename(columns={k: v for k, v in rename_map.items() if k in spx.columns})

for c in ["Issuer", "Ticker", "RIC", "ISIN", "CUSIP", "PermID"]:
    if c in spx.columns:
        spx[c] = clean_str_series(spx[c])

# Limpieza mínima para asegurar identificadores válidos por firma.
spx = spx.dropna(subset=["Ticker", "Issuer"]).copy()
spx["Ticker"] = spx["Ticker"].str.upper().str.strip()

# Deduplicación conservadora por ticker (mantiene primera observación).
spx = spx.drop_duplicates(subset=["Ticker"], keep="first").reset_index(drop=True)

# Guardado en formato CSV (compatibilidad heredada) y parquet (uso analítico).
spx.to_csv(UNIVERSE_FILE, index=False)
safe_write_parquet(spx, OUT["universe_firms"], index=False)

logger.info(f"Universo S&P 500 guardado en: {UNIVERSE_FILE}")
logger.info(f"Firmas en universo ampliado: {len(spx):,}")

2026-03-24 19:11:46 | INFO | Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/clean/universe_firms.parquet | rows=503 cols=7
2026-03-24 19:11:46,446 P[19164] [MainThread 20064] Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/clean/universe_firms.parquet | rows=503 cols=7
2026-03-24 19:11:46 | INFO | Universo S&P 500 guardado en: C:\Users\vidar\OneDrive\Desktop\UDESA\Tesis\Tesis-main\data\inputs\empresas_tickers_test.csv
2026-03-24 19:11:46,462 P[19164] [MainThread 20064] Universo S&P 500 guardado en: C:\Users\vidar\OneDrive\Desktop\UDESA\Tesis\Tesis-main\data\inputs\empresas_tickers_test.csv
2026-03-24 19:11:46 | INFO | Firmas en universo ampliado: 503
2026-03-24 19:11:46,464 P[19164] [MainThread 20064] Firmas en universo ampliado: 503

==============================
DEBUG REFINTIV S&P 500
==============================

--- ERRORS ---
None

--- SHAPE ---
(503, 7)

--- COLUMNAS ---
['Instrument', 'Company Common Name', 'Ticker Symbol', 'RIC', 'ISIN', 'CUSIP', 'Country of Headquarters']

--- HEAD ---
  Instrument             Company Common Name Ticker Symbol      RIC  \
0       PG.N             Procter & Gamble Co            PG     PG.N
1      FDS.N    Factset Research Systems Inc           FDS    FDS.N
2    ODFL.OQ   Old Dominion Freight Line Inc          ODFL  ODFL.OQ
3    GEHC.OQ  GE Healthcare Technologies Inc          GEHC  GEHC.OQ
4     UAL.OQ    United Airlines Holdings Inc           UAL   UAL.OQ

           ISIN      CUSIP   Country of Headquarters
0  US7427181091  742718109  United States of America
1  US3030751057  303075105  United States of America
2  US6795801009  679580100  United States of America
3  US36266G1076  36266G107  United States of America
4  US9100471096  910047109  United States of America

--- DTYPES ---
Instrument                 string[python]
Company Common Name        string[python]
Ticker Symbol              string[python]
RIC                        string[python]
ISIN                       string[python]
CUSIP                      string[python]
Country of Headquarters    string[python]
dtype: object

==============================

  Instrument                          Issuer Ticker      RIC          ISIN  \
0       PG.N             Procter & Gamble Co     PG     PG.N  US7427181091
1      FDS.N    Factset Research Systems Inc    FDS    FDS.N  US3030751057
2    ODFL.OQ   Old Dominion Freight Line Inc   ODFL  ODFL.OQ  US6795801009
3    GEHC.OQ  GE Healthcare Technologies Inc   GEHC  GEHC.OQ  US36266G1076
4     UAL.OQ    United Airlines Holdings Inc    UAL   UAL.OQ  US9100471096

       CUSIP       HeadquartersCountry
0  742718109  United States of America
1  303075105  United States of America
2  679580100  United States of America
3  36266G107  United States of America
4  910047109  United States of America

## 6) Bonos corporativos — universo amplio desde Workspace y filtro por S&P 500

**Input 1:** universo ampliado de firmas del S&P 500 descargado desde Refinitiv (`empresas_tickers_test.csv`).  
**Input 2:** tres exports grandes de bonos corporativos desde Refinitiv Workspace (`first_batch.xlsx`, `second_batch.xlsx`, `third_batch.xlsx`) guardados en `data/inputs/new_bonds/`.

### Objetivo
Construir un universo amplio y escalable de bonos corporativos observables y restringirlo a aquellos emitidos por firmas pertenecientes al S&P 500.

### Lógica
En lugar de partir de una lista manual reducida de emisores o de exports sectoriales pequeños, este bloque:

1. concatena tres descargas amplias de bonos corporativos desde Workspace;
2. normaliza columnas e identificadores;
3. filtra ese universo usando el universo oficial de firmas del S&P 500;
4. construye la tabla final `df_bonds_universe`, que será la base para la descarga posterior de OAS.

El matching principal se realiza por `Ticker`, preservando el `bond_ric` de cada bono.

### Output principal
- `df_bonds_universe`
- `bonds_universe_full.parquet`
- `bonds_universe_full.csv`

### Chequeos de QA
- cantidad total de bonos descargados;
- cantidad de bonos que matchean con el S&P 500;
- cantidad de `bond_ric` únicos;
- cantidad de empresas cubiertas;
- cobertura del universo de firmas.

### Interpretación
La muestra de deuda deja de surgir de una selección manual de emisores y pasa a definirse como la intersección entre:

1. el universo de firmas del S&P 500 identificado con Refinitiv, y
2. el universo observable de bonos corporativos disponible en Workspace.

Este cambio permite escalar la muestra de manera sustancial sin romper el pipeline posterior de descarga de OAS y construcción del panel.

In [18]:
# ==========================================================
# BONOS | Universo amplio desde Workspace + filtro por S&P 500
# ==========================================================

# -------------------------------------------------
# 1) Definición de rutas de entrada
# -------------------------------------------------
BONDS_DIR = INPUT_DIR / "new_bonds"

BOND_BATCH_FILES = [
    BONDS_DIR / "first_batch.xlsx",
    BONDS_DIR / "second_batch.xlsx",
    BONDS_DIR / "third_batch.xlsx",
]

# -------------------------------------------------
# 2) Lectura y concatenación de lotes de bonos
# -------------------------------------------------
dfs = []

for f in BOND_BATCH_FILES:
    if not f.exists():
        raise FileNotFoundError(f"No existe el archivo: {f}")

    logger.info(f"Leyendo archivo de bonos: {f.name}")
    df = pd.read_excel(f, dtype=str)
    df["source_file"] = f.name
    dfs.append(df)

bonds_raw = pd.concat(dfs, ignore_index=True)
logger.info(f"Bonos crudos concatenados | filas={len(bonds_raw):,} cols={bonds_raw.shape[1]}")

# -------------------------------------------------
# 3) Limpieza y normalización
# -------------------------------------------------
def clean_str(s: pd.Series) -> pd.Series:
    return (
        s.astype("string")
         .str.upper()
         .str.strip()
         .replace({"": pd.NA, "NAN": pd.NA, "NONE": pd.NA})
    )

rename_map = {
    "Issuer": "Issuer",
    "Ticker": "Ticker",
    "Coupon": "Coupon",
    "Maturity": "Maturity",
    "ISIN": "ISIN",
    "Preferred RIC": "bond_ric",
    "Principal Currency": "Principal_Currency",
    "Amount Issued (USD)": "Amount_Issued_USD",
}

bonds = bonds_raw.rename(columns={k: v for k, v in rename_map.items() if k in bonds_raw.columns}).copy()

for c in ["Issuer", "Ticker", "ISIN", "bond_ric", "Principal_Currency"]:
    if c in bonds.columns:
        bonds[c] = clean_str(bonds[c])

if "Coupon" in bonds.columns:
    bonds["Coupon"] = pd.to_numeric(bonds["Coupon"], errors="coerce")

if "Maturity" in bonds.columns:
    bonds["Maturity"] = pd.to_datetime(bonds["Maturity"], errors="coerce")

if "Amount_Issued_USD" in bonds.columns:
    bonds["Amount_Issued_USD"] = pd.to_numeric(bonds["Amount_Issued_USD"], errors="coerce")

# -------------------------------------------------
# 4) Carga del universo S&P 500
# -------------------------------------------------
sp500 = pd.read_csv(UNIVERSE_FILE, dtype=str).copy()

sp500["Ticker"] = clean_str(sp500["Ticker"])
if "Issuer" in sp500.columns:
    sp500["Issuer"] = clean_str(sp500["Issuer"])

logger.info(f"Universo S&P 500 cargado | firmas={len(sp500):,} tickers={sp500['Ticker'].nunique():,}")

# -------------------------------------------------
# 5) Filtro principal: bonos de firmas del S&P 500
# -------------------------------------------------
bonds_sp500 = bonds.merge(
    sp500[["Ticker"]].drop_duplicates(),
    on="Ticker",
    how="inner",
    validate="m:1"
)

# -------------------------------------------------
# 6) Limpieza final del universo de bonos
# -------------------------------------------------
req_cols = ["Issuer", "Ticker", "bond_ric"]
missing_req = [c for c in req_cols if c not in bonds_sp500.columns]
if missing_req:
    raise ValueError(f"Faltan columnas requeridas en bonds_sp500: {missing_req}")

df_bonds_universe = (
    bonds_sp500
    .dropna(subset=["Ticker", "bond_ric"])
    .drop_duplicates(subset=["Ticker", "bond_ric"])
    .reset_index(drop=True)
)

# -------------------------------------------------
# 7) Indicadores de calidad/cobertura
# -------------------------------------------------
coverage = df_bonds_universe["Ticker"].nunique() / sp500["Ticker"].nunique()

logger.info(f"Bonos totales descargados: {len(bonds):,}")
logger.info(f"Bonos S&P 500: {len(df_bonds_universe):,}")
logger.info(f"RICs únicos de bonos: {df_bonds_universe['bond_ric'].nunique():,}")
logger.info(f"Empresas cubiertas: {df_bonds_universe['Ticker'].nunique():,}")
logger.info(f"Cobertura de empresas: {coverage:.2%}")

# -------------------------------------------------
# 8) Guardado oficial
# -------------------------------------------------
out_parquet = OUT.get("bonds_universe_full", CLEAN_DIR / "bonds_universe_full.parquet")
out_csv = out_parquet.with_suffix(".csv")

safe_write_parquet(df_bonds_universe, out_parquet, index=False)
df_bonds_universe.to_csv(out_csv, index=False)

logger.info(f"Output -> {out_csv.as_posix()}")
logger.info(f"Bonos SP500 guardados: {len(df_bonds_universe):,}")

2026-03-24 19:11:46 | INFO | Leyendo archivo de bonos: first_batch.xlsx
2026-03-24 19:11:46,489 P[19164] [MainThread 20064] Leyendo archivo de bonos: first_batch.xlsx
2026-03-24 19:11:47 | INFO | Leyendo archivo de bonos: second_batch.xlsx
2026-03-24 19:11:47,421 P[19164] [MainThread 20064] Leyendo archivo de bonos: second_batch.xlsx
2026-03-24 19:11:48 | INFO | Leyendo archivo de bonos: third_batch.xlsx
2026-03-24 19:11:48,347 P[19164] [MainThread 20064] Leyendo archivo de bonos: third_batch.xlsx

=== BONDS RAW ===
Shape: (28839, 9)
Columnas: ['Issuer', 'Ticker', 'Coupon', 'Maturity', 'ISIN', 'Preferred RIC', 'Principal Currency', 'Amount Issued (USD)', 'source_file']

2026-03-24 19:11:49 | INFO | Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/clean/bonds_universe_full.parquet | rows=9,448 cols=9
2026-03-24 19:11:49,628 P[19164] [MainThread 20064] Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/clean/bonds_universe_full.parquet | rows=9,448 cols=9
2026-03-24 19:11:49 | INFO | Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/clean/bonds_universe_full.csv
2026-03-24 19:11:49,690 P[19164] [MainThread 20064] Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/clean/bonds_universe_full.csv
2026-03-24 19:11:49 | INFO | Bonos SP500 guardados: 9,448
2026-03-24 19:11:49,692 P[19164] [MainThread 20064] Bonos SP500 guardados: 9,448

=== SP500 ===
Firmas: 503
Tickers únicos: 503

=== RESULTADOS | df_bonds_universe ===
Bonos totales descargados: 28839
Bonos SP500: 9448
RICs únicos (bonos): 9448
Empresas cubiertas: 328
Cobertura empresas: 65.21%

=== HEAD ===
     Issuer Ticker    bond_ric   Maturity          ISIN  Coupon  \
0  AT&T INC      T  00206RML3= 2026-03-25  US00206RML32    1.70
1  AT&T INC      T  00206RHV7= 2026-07-15  US00206RHV78    2.95
2  AT&T INC      T  00206RGJ5= 2026-08-15  US00206RGJ59    7.30
3  AT&T INC      T  00206RHW5= 2027-02-15  US00206RHW51    3.80
4  AT&T INC      T  00206RDQ2= 2027-03-01  US00206RDQ20    4.25

  Principal_Currency  Amount_Issued_USD       source_file
0          US DOLLAR       3.000000e+09  first_batch.xlsx
1          US DOLLAR       7.072580e+08  first_batch.xlsx
2          US DOLLAR       2.127000e+07  first_batch.xlsx
3          US DOLLAR       1.329194e+09  first_batch.xlsx
4          US DOLLAR       2.000000e+09  first_batch.xlsx

## 7) Empresas — descarga de metadata (Refinitiv)

**Input:** `data/inputs/empresas_tickers_test.csv` (Issuer, Ticker).  
**Output:** `data/raw/company_metadata.parquet` (+ `.csv`).  
**Chequeos:** cobertura de columnas clave (nombre, ISIN, CUSIP), listado de tickers con metadata incompleta y reintentos con sufijos.  
**Notas:** la descarga se hace por batches para evitar rate limits; algunos tickers requieren sufijos de mercado (ej. `.O`, `.N`, `.K`).

In [19]:
# ======================
# EMPRESAS -> metadata Refinitiv
# ======================

FIELDS = [
    "TR.CommonName",
    "TR.ISIN",
    "TR.CUSIP",
    "TR.PermID",
    "TR.HeadquartersCountry",
    "TR.GICSSectorName",
    "TR.GICSIndustryGroupName",
    "TR.GICSIndustryName",
    "TR.GICSSubIndustryName"
]

REQUIRED_META_COLS = ["ISIN", "CUSIP"]

# -----------------------------------
# Helpers
# -----------------------------------

def ticker_to_ric(ticker: str):

    ticker = ticker.strip().upper()

    nasdaq = {"AAPL","MSFT","GOOGL","META","CSCO","PEP","HON"}
    nyse   = {"JPM","BAC","C","WFC","GS","MS","XOM","CVX","COP","OXY",
              "JNJ","PFE","MRK","ABBV","PG","KO","MCD","WMT",
              "GE","MMM","CAT","DUK","NEE","SO","ORCL"}

    if ticker in nasdaq:
        return f"{ticker}.O"

    if ticker in nyse:
        return f"{ticker}.N"

    return f"{ticker}.N"


def normalize_str(s):

    out = s.astype("string").str.strip()
    out = out.replace({"": pd.NA, "nan": pd.NA, "None": pd.NA})

    return out


def fetch_metadata_retry(rics, fields, retries=3):

    for attempt in range(retries):

        try:

            df, err = ek.get_data(rics, fields)

            if err is not None and len(err):
                logger.warning(f"Refinitiv error: {err}")

            if df is not None and not df.empty:
                return df

            else:
                logger.warning(f"Intento {attempt+1}: dataframe vacío")

        except Exception as e:

            logger.warning(f"Intento {attempt+1}/{retries} falló con excepción: {e}")

        sleep_request(2)

    raise RuntimeError("Refinitiv no respondió después de varios intentos")


# -----------------------------------
# Helper: dividir listas en batches
# -----------------------------------

def chunked(iterable, size):

    for i in range(0, len(iterable), size):
        yield iterable[i:i + size]


# -----------------------------------
# 1) Leer universo
# -----------------------------------

df_universe = pd.read_csv(UNIVERSE_FILE, dtype=str)

missing_cols = [c for c in ["Ticker","Issuer"] if c not in df_universe.columns]

if missing_cols:
    raise ValueError(f"Faltan columnas {missing_cols}")

df_universe = df_universe.dropna(subset=["Ticker","Issuer"]).reset_index(drop=True)

# usar RIC directo si ya vino en el universo; fallback a ticker_to_ric()
if "RIC" in df_universe.columns:
    df_universe["RIC"] = normalize_str(df_universe["RIC"])
else:
    df_universe["RIC"] = pd.NA

df_universe["ric_for_download"] = df_universe["RIC"]

mask_missing_ric = df_universe["ric_for_download"].isna()
df_universe.loc[mask_missing_ric, "ric_for_download"] = (
    df_universe.loc[mask_missing_ric, "Ticker"]
    .astype(str)
    .str.strip()
    .apply(ticker_to_ric)
)

rics = (
    df_universe["ric_for_download"]
    .dropna()
    .astype(str)
    .str.strip()
    .unique()
    .tolist()
)

logger.info(f"Universo cargado: {len(rics)} RICs")
logger.info(f"Primeros RICs enviados: {rics[:20]}")

# -----------------------------------
# 2) Descarga metadata
# -----------------------------------

meta_frames = []

for i, batch in enumerate(chunked(rics, 10), start=1):

    logger.info(f"Batch {i} | instrumentos={len(batch)}")

    df = fetch_metadata_retry(batch, FIELDS)

    if df is not None and not df.empty:
        meta_frames.append(df)

    sleep_request(0.5)


if not meta_frames:
    raise RuntimeError("No se descargó metadata de ninguna empresa.")

meta = pd.concat(meta_frames, ignore_index=True)

logger.info(f"Metadata descargada: filas={len(meta)}")


# -----------------------------------
# 3) Normalización
# -----------------------------------

meta.columns = [c.replace("TR.", "").strip() for c in meta.columns]

if "Instrument" in meta.columns:
    meta = meta.rename(columns={"Instrument": "ric"})
elif "RIC" in meta.columns:
    meta = meta.rename(columns={"RIC": "ric"})

if "ric" in meta.columns:
    meta["ric"] = normalize_str(meta["ric"])

for col in ["ISIN", "CUSIP"]:
    if col in meta.columns:
        meta[col] = normalize_str(meta[col])


# -----------------------------------
# 4) QA rápido
# -----------------------------------

bad_mask = pd.Series(False, index=meta.index)

for col in REQUIRED_META_COLS:

    if col not in meta.columns:
        logger.warning(f"Falta columna esperada: {col}")
        continue

    bad_mask |= meta[col].isna()

bad_rows = meta[bad_mask]

logger.info(f"Empresas con metadata incompleta: {len(bad_rows)}")


# -----------------------------------
# 5) Export
# -----------------------------------

out_parquet = RAW_DIR / "company_metadata.parquet"
out_csv     = RAW_DIR / "company_metadata.csv"

safe_write_parquet(meta, out_parquet, index=False)
meta.to_csv(out_csv, index=False)

logger.info(f"Output -> {out_csv}")

2026-03-24 19:11:49 | INFO | Universo cargado: 503 RICs
2026-03-24 19:11:49,730 P[19164] [MainThread 20064] Universo cargado: 503 RICs
2026-03-24 19:11:49 | INFO | Primeros RICs enviados: ['PG.N', 'FDS.N', 'ODFL.OQ', 'GEHC.OQ', 'UAL.OQ', 'FCX.N', 'NOC.N', 'FIX.N', 'SNDK.OQ', 'EVRG.OQ', 'ETN.N', 'TAP.N', 'LIN.OQ', 'AMZN.OQ', 'MNST.OQ', 'ESS.N', 'JNJ.N', 'NVDA.OQ', 'PNR.N', 'FDX.N']
2026-03-24 19:11:49,732 P[19164] [MainThread 20064] Primeros RICs enviados: ['PG.N', 'FDS.N', 'ODFL.OQ', 'GEHC.OQ', 'UAL.OQ', 'FCX.N', 'NOC.N', 'FIX.N', 'SNDK.OQ', 'EVRG.OQ', 'ETN.N', 'TAP.N', 'LIN.OQ', 'AMZN.OQ', 'MNST.OQ', 'ESS.N', 'JNJ.N', 'NVDA.OQ', 'PNR.N', 'FDX.N']
2026-03-24 19:11:49 | INFO | Batch 1 | instrumentos=10
2026-03-24 19:11:49,733 P[19164] [MainThread 20064] Batch 1 | instrumentos=10
2026-03-24 19:11:50 | INFO | Batch 2 | instrumentos=10
2026-03-24 19:11:50,831 P[19164] [MainThread 20064] Batch 2 | instrumentos=10
2026-03-24 19:11:51 | INFO | Batch 3 | instrumentos=10
2026-03-24 19:11:51,855 P[19164] [MainThread 20064] Batch 3 | instrumentos=10
2026-03-24 19:11:52 | INFO | Batch 4 | instrumentos=10
2026-03-24 19:11:52,965 P[19164] [MainThread 20064] Batch 4 | instrumentos=10
2026-03-24 19:11:54 | INFO | Batch 5 | instrumentos=10
2026-03-24 19:11:54,097 P[19164] [MainThread 20064] Batch 5 | instrumentos=10
2026-03-24 19:11:55 | INFO | Batch 6 | instrumentos=10
2026-03-24 19:11:55,116 P[19164] [MainThread 20064] Batch 6 | instrumentos=10
2026-03-24 19:11:56 | INFO | Batch 7 | instrumentos=10
2026-03-24 19:11:56,128 P[19164] [MainThread 20064] Batch 7 | instrumentos=10
2026-03-24 19:11:57 | INFO | Batch 8 | instrumentos=10
2026-03-24 19:11:57,315 P[19164] [MainThread 20064] Batch 8 | instrumentos=10
2026-03-24 19:11:58 | INFO | Batch 9 | instrumentos=10
2026-03-24 19:11:58,411 P[19164] [MainThread 20064] Batch 9 | instrumentos=10
2026-03-24 19:11:59 | INFO | Batch 10 | instrumentos=10
2026-03-24 19:11:59,564 P[19164] [MainThread 20064] Batch 10 | instrumentos=10
2026-03-24 19:12:00 | INFO | Batch 11 | instrumentos=10
2026-03-24 19:12:00,660 P[19164] [MainThread 20064] Batch 11 | instrumentos=10
2026-03-24 19:12:01 | INFO | Batch 12 | instrumentos=10
2026-03-24 19:12:01,674 P[19164] [MainThread 20064] Batch 12 | instrumentos=10
2026-03-24 19:12:02 | INFO | Batch 13 | instrumentos=10
2026-03-24 19:12:02,752 P[19164] [MainThread 20064] Batch 13 | instrumentos=10
2026-03-24 19:12:03 | INFO | Batch 14 | instrumentos=10
2026-03-24 19:12:03,775 P[19164] [MainThread 20064] Batch 14 | instrumentos=10
2026-03-24 19:12:04 | INFO | Batch 15 | instrumentos=10
2026-03-24 19:12:04,850 P[19164] [MainThread 20064] Batch 15 | instrumentos=10
2026-03-24 19:12:05 | INFO | Batch 16 | instrumentos=10
2026-03-24 19:12:05,948 P[19164] [MainThread 20064] Batch 16 | instrumentos=10
2026-03-24 19:12:07 | INFO | Batch 17 | instrumentos=10
2026-03-24 19:12:07,055 P[19164] [MainThread 20064] Batch 17 | instrumentos=10
2026-03-24 19:12:08 | INFO | Batch 18 | instrumentos=10
2026-03-24 19:12:08,078 P[19164] [MainThread 20064] Batch 18 | instrumentos=10
2026-03-24 19:12:09 | INFO | Batch 19 | instrumentos=10
2026-03-24 19:12:09,103 P[19164] [MainThread 20064] Batch 19 | instrumentos=10
2026-03-24 19:12:10 | INFO | Batch 20 | instrumentos=10
2026-03-24 19:12:10,180 P[19164] [MainThread 20064] Batch 20 | instrumentos=10
2026-03-24 19:12:11 | INFO | Batch 21 | instrumentos=10
2026-03-24 19:12:11,285 P[19164] [MainThread 20064] Batch 21 | instrumentos=10
2026-03-24 19:12:12 | INFO | Batch 22 | instrumentos=10
2026-03-24 19:12:12,326 P[19164] [MainThread 20064] Batch 22 | instrumentos=10
2026-03-24 19:12:13 | INFO | Batch 23 | instrumentos=10
2026-03-24 19:12:13,358 P[19164] [MainThread 20064] Batch 23 | instrumentos=10
2026-03-24 19:12:14 | INFO | Batch 24 | instrumentos=10
2026-03-24 19:12:14,372 P[19164] [MainThread 20064] Batch 24 | instrumentos=10
2026-03-24 19:12:15 | INFO | Batch 25 | instrumentos=10
2026-03-24 19:12:15,408 P[19164] [MainThread 20064] Batch 25 | instrumentos=10
2026-03-24 19:12:16 | INFO | Batch 26 | instrumentos=10
2026-03-24 19:12:16,436 P[19164] [MainThread 20064] Batch 26 | instrumentos=10
2026-03-24 19:12:17 | INFO | Batch 27 | instrumentos=10
2026-03-24 19:12:17,528 P[19164] [MainThread 20064] Batch 27 | instrumentos=10
2026-03-24 19:12:18 | INFO | Batch 28 | instrumentos=10
2026-03-24 19:12:18,632 P[19164] [MainThread 20064] Batch 28 | instrumentos=10
2026-03-24 19:12:19 | INFO | Batch 29 | instrumentos=10
2026-03-24 19:12:19,639 P[19164] [MainThread 20064] Batch 29 | instrumentos=10
2026-03-24 19:12:20 | INFO | Batch 30 | instrumentos=10
2026-03-24 19:12:20,664 P[19164] [MainThread 20064] Batch 30 | instrumentos=10
2026-03-24 19:12:21 | INFO | Batch 31 | instrumentos=10
2026-03-24 19:12:21,801 P[19164] [MainThread 20064] Batch 31 | instrumentos=10
2026-03-24 19:12:22 | INFO | Batch 32 | instrumentos=10
2026-03-24 19:12:22,817 P[19164] [MainThread 20064] Batch 32 | instrumentos=10
2026-03-24 19:12:23 | INFO | Batch 33 | instrumentos=10
2026-03-24 19:12:23,980 P[19164] [MainThread 20064] Batch 33 | instrumentos=10
2026-03-24 19:12:25 | INFO | Batch 34 | instrumentos=10
2026-03-24 19:12:25,003 P[19164] [MainThread 20064] Batch 34 | instrumentos=10
2026-03-24 19:12:26 | INFO | Batch 35 | instrumentos=10
2026-03-24 19:12:26,089 P[19164] [MainThread 20064] Batch 35 | instrumentos=10
2026-03-24 19:12:27 | INFO | Batch 36 | instrumentos=10
2026-03-24 19:12:27,175 P[19164] [MainThread 20064] Batch 36 | instrumentos=10
2026-03-24 19:12:28 | INFO | Batch 37 | instrumentos=10
2026-03-24 19:12:28,200 P[19164] [MainThread 20064] Batch 37 | instrumentos=10
2026-03-24 19:12:29 | INFO | Batch 38 | instrumentos=10
2026-03-24 19:12:29,295 P[19164] [MainThread 20064] Batch 38 | instrumentos=10
2026-03-24 19:12:30 | INFO | Batch 39 | instrumentos=10
2026-03-24 19:12:30,321 P[19164] [MainThread 20064] Batch 39 | instrumentos=10
2026-03-24 19:12:31 | INFO | Batch 40 | instrumentos=10
2026-03-24 19:12:31,432 P[19164] [MainThread 20064] Batch 40 | instrumentos=10
2026-03-24 19:12:32 | INFO | Batch 41 | instrumentos=10
2026-03-24 19:12:32,456 P[19164] [MainThread 20064] Batch 41 | instrumentos=10
2026-03-24 19:12:33 | INFO | Batch 42 | instrumentos=10
2026-03-24 19:12:33,544 P[19164] [MainThread 20064] Batch 42 | instrumentos=10
2026-03-24 19:12:34 | INFO | Batch 43 | instrumentos=10
2026-03-24 19:12:34,558 P[19164] [MainThread 20064] Batch 43 | instrumentos=10
2026-03-24 19:12:35 | INFO | Batch 44 | instrumentos=10
2026-03-24 19:12:35,592 P[19164] [MainThread 20064] Batch 44 | instrumentos=10
2026-03-24 19:12:36 | INFO | Batch 45 | instrumentos=10
2026-03-24 19:12:36,630 P[19164] [MainThread 20064] Batch 45 | instrumentos=10
2026-03-24 19:12:37 | INFO | Batch 46 | instrumentos=10
2026-03-24 19:12:37,656 P[19164] [MainThread 20064] Batch 46 | instrumentos=10
2026-03-24 19:12:38 | INFO | Batch 47 | instrumentos=10
2026-03-24 19:12:38,745 P[19164] [MainThread 20064] Batch 47 | instrumentos=10
2026-03-24 19:12:39 | INFO | Batch 48 | instrumentos=10
2026-03-24 19:12:39,842 P[19164] [MainThread 20064] Batch 48 | instrumentos=10
2026-03-24 19:12:40 | INFO | Batch 49 | instrumentos=10
2026-03-24 19:12:40,876 P[19164] [MainThread 20064] Batch 49 | instrumentos=10
2026-03-24 19:12:42 | INFO | Batch 50 | instrumentos=10
2026-03-24 19:12:42,001 P[19164] [MainThread 20064] Batch 50 | instrumentos=10
2026-03-24 19:12:43 | INFO | Batch 51 | instrumentos=3
2026-03-24 19:12:43,103 P[19164] [MainThread 20064] Batch 51 | instrumentos=3
2026-03-24 19:12:44 | INFO | Metadata descargada: filas=503
2026-03-24 19:12:44,116 P[19164] [MainThread 20064] Metadata descargada: filas=503
2026-03-24 19:12:44 | INFO | Empresas con metadata incompleta: 27
2026-03-24 19:12:44,127 P[19164] [MainThread 20064] Empresas con metadata incompleta: 27
2026-03-24 19:12:44 | INFO | Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/raw/company_metadata.parquet | rows=503 cols=5
2026-03-24 19:12:44,134 P[19164] [MainThread 20064] Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/raw/company_metadata.parquet | rows=503 cols=5
2026-03-24 19:12:44 | INFO | Output -> C:\Users\vidar\OneDrive\Desktop\UDESA\Tesis\Tesis-main\data\raw\company_metadata.csv
2026-03-24 19:12:44,139 P[19164] [MainThread 20064] Output -> C:\Users\vidar\OneDrive\Desktop\UDESA\Tesis\Tesis-main\data\raw\company_metadata.csv

## 8) Equity — precios diarios (CLOSE, VOLUME)

**Input:** `data/inputs/empresas_tickers_test.csv` (Ticker).  
**Output:** `data/raw/equity_prices_daily.parquet` (+ `.csv`).  
**Chequeos:** conteo de RICs con datos vs sin datos; rango de fechas por RIC; listado de series que arrancan tarde.  
**Notas:** para algunos tickers se prueban sufijos `.N` y `.O`. Se aplica pausa entre requests para reducir riesgos de rate limit (HTTP 429).

In [20]:
# ======================
# EQUITY -> precios diarios (CLOSE, VOLUME)
# ======================

# Universo de empresas (sale del CSV de inputs)
df_emp = pd.read_csv(UNIVERSE_FILE, dtype=str).dropna(subset=["Ticker"]).copy()
df_emp["Ticker"] = df_emp["Ticker"].astype(str).str.strip()

if "RIC" in df_emp.columns:
    df_emp["RIC"] = df_emp["RIC"].astype("string").str.strip()
else:
    df_emp["RIC"] = pd.NA

logger.info(f"Empresas en CSV: {len(df_emp):,}")
logger.info(f"Tickers detectados: {df_emp['Ticker'].nunique():,}")
logger.info(f"RICs no nulos: {df_emp['RIC'].notna().sum():,}")

def ric_candidates_row(row) -> list[str]:
    """
    Prioriza el RIC ya provisto en el universo.
    Si no existe, arma candidatos a partir del ticker.
    """
    ric = row.get("RIC", pd.NA)
    ticker = str(row["Ticker"]).strip()

    if pd.notna(ric) and str(ric).strip() != "":
        return [str(ric).strip()]

    if "." in ticker:
        return [ticker]

    return [f"{ticker}.N", f"{ticker}.O"]

all_frames = []
success = 0
fail = 0

for _, row in df_emp.iterrows():
    t = row["Ticker"]
    got_it = False

    for ric in ric_candidates_row(row):
        try:
            ts = ek.get_timeseries(
                ric,
                fields=["CLOSE", "VOLUME"],
                start_date=START_DATE,
                end_date=END_DATE,
                interval="daily",
            )

            if ts is not None and not ts.empty:
                ts = ts.reset_index().rename(columns={"Date": "date"})
                ts["date"] = pd.to_datetime(ts["date"], errors="coerce")

                # Normalización defensiva del nombre de columnas
                cols_upper = {c: str(c).upper() for c in ts.columns}
                ts = ts.rename(columns=cols_upper)

                if "DATE" in ts.columns and "date" not in ts.columns:
                    ts = ts.rename(columns={"DATE": "date"})

                if "date" not in ts.columns:
                    raise ValueError(f"No encontré columna de fecha en la serie descargada para {ric}")

                if getattr(ts["date"].dt, "tz", None) is not None:
                    ts["date"] = ts["date"].dt.tz_localize(None)

                ts["ric"] = ric

                # asegurar columnas esperadas
                if "CLOSE" not in ts.columns:
                    ts["CLOSE"] = pd.NA
                if "VOLUME" not in ts.columns:
                    ts["VOLUME"] = pd.NA

                all_frames.append(ts[["date", "ric", "CLOSE", "VOLUME"]])

                dmin = ts["date"].min()
                dmax = ts["date"].max()
                logger.info(f"OK {ric:<12} | {dmin.date()} -> {dmax.date()}")

                success += 1
                got_it = True
                break

        except Exception as e:
            logger.warning(f"Error con {ric}: {type(e).__name__}: {e}")

        sleep_request(0.6)

    if not got_it:
        logger.warning(f"Sin datos para ticker: {t}")
        fail += 1

logger.info(f"RICs con datos: {success:,}")
logger.info(f"RICs sin datos: {fail:,}")

# Consolidación final
if all_frames:
    out = pd.concat(all_frames, ignore_index=True)
else:
    out = pd.DataFrame(columns=["date", "ric", "CLOSE", "VOLUME"])

out = out.sort_values(["ric", "date"]).reset_index(drop=True)

# Export
out_parquet = OUT.get("equity_prices_daily", RAW_DIR / "equity_prices_daily.parquet")
out_csv = out_parquet.with_suffix(".csv")

safe_write_parquet(out, out_parquet, index=False)
out.to_csv(out_csv, index=False)

logger.info(f"Output -> {out_csv.as_posix()}")
logger.info(f"Total filas: {len(out):,}")

# Chequeo: series que arrancan tarde
if not out.empty:
    late = out.groupby("ric")["date"].min().reset_index()
    late = late[late["date"] > pd.Timestamp("2016-01-01")]

    if not late.empty:
        logger.warning("Series que arrancan tarde (min date > 2016-01-01):")
        logger.warning(late.sort_values("date").head(50).to_string(index=False))
    else:
        logger.info("Cobertura temporal OK (no hay series que arranquen tarde según el umbral).")
else:
    logger.warning("El output de equity quedó vacío.")

2026-03-24 19:12:44 | INFO | Empresas en CSV: 503
2026-03-24 19:12:44,170 P[19164] [MainThread 20064] Empresas en CSV: 503
2026-03-24 19:12:44 | INFO | Tickers detectados: 503
2026-03-24 19:12:44,172 P[19164] [MainThread 20064] Tickers detectados: 503
2026-03-24 19:12:44 | INFO | RICs no nulos: 503
2026-03-24 19:12:44,175 P[19164] [MainThread 20064] RICs no nulos: 503
2026-03-24 19:12:45 | INFO | OK PG.N         | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:45,133 P[19164] [MainThread 20064] OK PG.N         | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:46 | INFO | OK FDS.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:46,319 P[19164] [MainThread 20064] OK FDS.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:47 | INFO | OK ODFL.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:47,254 P[19164] [MainThread 20064] OK ODFL.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:47 | INFO | OK GEHC.OQ      | 2022-12-15 -> 2025-12-31
2026-03-24 19:12:47,992 P[19164] [MainThread 20064] OK GEHC.OQ      | 2022-12-15 -> 2025-12-31
2026-03-24 19:12:48 | INFO | OK UAL.OQ       | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:48,577 P[19164] [MainThread 20064] OK UAL.OQ       | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:49 | INFO | OK FCX.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:49,304 P[19164] [MainThread 20064] OK FCX.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:49 | INFO | OK NOC.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:49,881 P[19164] [MainThread 20064] OK NOC.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:50 | INFO | OK FIX.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:50,701 P[19164] [MainThread 20064] OK FIX.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:51 | INFO | OK SNDK.OQ      | 2025-02-13 -> 2025-12-31
2026-03-24 19:12:51,148 P[19164] [MainThread 20064] OK SNDK.OQ      | 2025-02-13 -> 2025-12-31
2026-03-24 19:12:51 | INFO | OK EVRG.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:51,698 P[19164] [MainThread 20064] OK EVRG.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:52 | INFO | OK ETN.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:52,256 P[19164] [MainThread 20064] OK ETN.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:53 | INFO | OK TAP.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:53,006 P[19164] [MainThread 20064] OK TAP.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:53 | INFO | OK LIN.OQ       | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:53,863 P[19164] [MainThread 20064] OK LIN.OQ       | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:54 | INFO | OK AMZN.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:54,493 P[19164] [MainThread 20064] OK AMZN.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:55 | INFO | OK MNST.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:55,021 P[19164] [MainThread 20064] OK MNST.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:55 | INFO | OK ESS.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:55,716 P[19164] [MainThread 20064] OK ESS.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:56 | INFO | OK JNJ.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:56,276 P[19164] [MainThread 20064] OK JNJ.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:56 | INFO | OK NVDA.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:56,823 P[19164] [MainThread 20064] OK NVDA.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:57 | INFO | OK PNR.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:57,333 P[19164] [MainThread 20064] OK PNR.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:57 | INFO | OK FDX.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:57,908 P[19164] [MainThread 20064] OK FDX.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:58 | INFO | OK TRMB.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:58,428 P[19164] [MainThread 20064] OK TRMB.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:58 | INFO | OK VTRS.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:58,958 P[19164] [MainThread 20064] OK VTRS.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:59 | INFO | OK ALLE.N       | 2015-01-02 -> 2025-12-31
2026-03-24 19:12:59,483 P[19164] [MainThread 20064] OK ALLE.N       | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:00 | INFO | OK BKR.OQ       | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:00,010 P[19164] [MainThread 20064] OK BKR.OQ       | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:00 | INFO | OK CDW.OQ       | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:00,527 P[19164] [MainThread 20064] OK CDW.OQ       | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:01 | INFO | OK RF.N         | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:01,206 P[19164] [MainThread 20064] OK RF.N         | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:01 | INFO | OK SBAC.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:01,739 P[19164] [MainThread 20064] OK SBAC.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:02 | INFO | OK CCI.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:02,520 P[19164] [MainThread 20064] OK CCI.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:03 | INFO | OK CRWD.OQ      | 2019-06-12 -> 2025-12-31
2026-03-24 19:13:03,159 P[19164] [MainThread 20064] OK CRWD.OQ      | 2019-06-12 -> 2025-12-31
2026-03-24 19:13:03 | INFO | OK BLK.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:03,686 P[19164] [MainThread 20064] OK BLK.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:04 | INFO | OK GPN.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:04,366 P[19164] [MainThread 20064] OK GPN.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:04 | INFO | OK UNP.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:04,918 P[19164] [MainThread 20064] OK UNP.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:05 | INFO | OK EFX.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:05,418 P[19164] [MainThread 20064] OK EFX.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:05 | INFO | OK ANET.N       | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:05,922 P[19164] [MainThread 20064] OK ANET.N       | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:06 | INFO | OK JPM.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:06,455 P[19164] [MainThread 20064] OK JPM.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:07 | INFO | OK CSX.OQ       | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:07,006 P[19164] [MainThread 20064] OK CSX.OQ       | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:07 | INFO | OK AMD.OQ       | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:07,552 P[19164] [MainThread 20064] OK AMD.OQ       | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:08 | INFO | OK COP.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:08,084 P[19164] [MainThread 20064] OK COP.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:08 | INFO | OK TER.OQ       | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:08,659 P[19164] [MainThread 20064] OK TER.OQ       | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:09 | INFO | OK IR.N         | 2017-05-12 -> 2025-12-31
2026-03-24 19:13:09,178 P[19164] [MainThread 20064] OK IR.N         | 2017-05-12 -> 2025-12-31
2026-03-24 19:13:09 | INFO | OK TKO.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:09,735 P[19164] [MainThread 20064] OK TKO.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:10 | INFO | OK SNA.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:10,325 P[19164] [MainThread 20064] OK SNA.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:10 | INFO | OK PANW.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:10,860 P[19164] [MainThread 20064] OK PANW.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:11 | INFO | OK CRH.N        | 2023-09-25 -> 2025-12-31
2026-03-24 19:13:11,571 P[19164] [MainThread 20064] OK CRH.N        | 2023-09-25 -> 2025-12-31
2026-03-24 19:13:12 | INFO | OK SWK.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:12,129 P[19164] [MainThread 20064] OK SWK.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:12 | INFO | OK TJX.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:12,989 P[19164] [MainThread 20064] OK TJX.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:13 | INFO | OK ED.N         | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:13,561 P[19164] [MainThread 20064] OK ED.N         | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:14 | INFO | OK CIEN.N       | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:14,065 P[19164] [MainThread 20064] OK CIEN.N       | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:14 | INFO | OK RMD.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:14,624 P[19164] [MainThread 20064] OK RMD.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:15 | INFO | OK PWR.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:15,188 P[19164] [MainThread 20064] OK PWR.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:15 | INFO | OK MPWR.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:15,707 P[19164] [MainThread 20064] OK MPWR.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:16 | INFO | OK RVTY.N       | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:16,229 P[19164] [MainThread 20064] OK RVTY.N       | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:16 | INFO | OK DRI.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:16,958 P[19164] [MainThread 20064] OK DRI.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:17 | INFO | OK CF.N         | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:17,735 P[19164] [MainThread 20064] OK CF.N         | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:18 | INFO | OK DOC.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:18,293 P[19164] [MainThread 20064] OK DOC.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:18 | INFO | OK BLDR.N       | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:18,824 P[19164] [MainThread 20064] OK BLDR.N       | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:19 | INFO | OK ROL.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:19,582 P[19164] [MainThread 20064] OK ROL.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:20 | INFO | OK FISV.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:20,135 P[19164] [MainThread 20064] OK FISV.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:20 | INFO | OK TPR.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:20,701 P[19164] [MainThread 20064] OK TPR.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:21 | INFO | OK SYY.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:21,497 P[19164] [MainThread 20064] OK SYY.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:21 | INFO | OK EXE.OQ       | 2021-02-10 -> 2025-12-31
2026-03-24 19:13:21,974 P[19164] [MainThread 20064] OK EXE.OQ       | 2021-02-10 -> 2025-12-31
2026-03-24 19:13:22 | INFO | OK WY.N         | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:22,500 P[19164] [MainThread 20064] OK WY.N         | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:23 | INFO | OK MRNA.OQ      | 2018-12-07 -> 2025-12-31
2026-03-24 19:13:23,261 P[19164] [MainThread 20064] OK MRNA.OQ      | 2018-12-07 -> 2025-12-31
2026-03-24 19:13:23 | INFO | OK ORLY.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:23,864 P[19164] [MainThread 20064] OK ORLY.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:24 | INFO | OK T.N          | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:24,395 P[19164] [MainThread 20064] OK T.N          | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:24 | INFO | OK GNRC.N       | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:24,934 P[19164] [MainThread 20064] OK GNRC.N       | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:25 | INFO | OK CTSH.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:25,684 P[19164] [MainThread 20064] OK CTSH.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:26 | INFO | OK VRSK.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:26,433 P[19164] [MainThread 20064] OK VRSK.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:26 | INFO | OK ORCL.N       | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:26,962 P[19164] [MainThread 20064] OK ORCL.N       | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:27 | INFO | OK XOM.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:27,782 P[19164] [MainThread 20064] OK XOM.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:28 | INFO | OK HSIC.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:28,467 P[19164] [MainThread 20064] OK HSIC.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:29 | INFO | OK LYV.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:29,176 P[19164] [MainThread 20064] OK LYV.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:29 | INFO | OK PLD.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:29,750 P[19164] [MainThread 20064] OK PLD.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:30 | INFO | OK KO.N         | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:30,302 P[19164] [MainThread 20064] OK KO.N         | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:31 | INFO | OK PHM.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:31,022 P[19164] [MainThread 20064] OK PHM.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:31 | INFO | OK DHR.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:31,556 P[19164] [MainThread 20064] OK DHR.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:32 | INFO | OK AXON.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:32,084 P[19164] [MainThread 20064] OK AXON.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:32 | INFO | OK STT.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:32,613 P[19164] [MainThread 20064] OK STT.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:33 | INFO | OK BK.N         | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:33,157 P[19164] [MainThread 20064] OK BK.N         | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:33 | INFO | OK IT.N         | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:33,700 P[19164] [MainThread 20064] OK IT.N         | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:34 | INFO | OK OMC.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:34,230 P[19164] [MainThread 20064] OK OMC.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:34 | INFO | OK URI.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:34,792 P[19164] [MainThread 20064] OK URI.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:35 | INFO | OK VRT.N        | 2018-07-30 -> 2025-12-31
2026-03-24 19:13:35,267 P[19164] [MainThread 20064] OK VRT.N        | 2018-07-30 -> 2025-12-31
2026-03-24 19:13:35 | INFO | OK EPAM.N       | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:35,794 P[19164] [MainThread 20064] OK EPAM.N       | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:36 | INFO | OK SNPS.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:36,328 P[19164] [MainThread 20064] OK SNPS.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:37 | INFO | OK CHRW.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:37,049 P[19164] [MainThread 20064] OK CHRW.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:37 | INFO | OK CPT.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:37,590 P[19164] [MainThread 20064] OK CPT.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:38 | INFO | OK XYZ.N        | 2015-11-19 -> 2025-12-31
2026-03-24 19:13:38,287 P[19164] [MainThread 20064] OK XYZ.N        | 2015-11-19 -> 2025-12-31
2026-03-24 19:13:39 | INFO | OK EQR.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:39,054 P[19164] [MainThread 20064] OK EQR.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:39 | INFO | OK ROK.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:39,597 P[19164] [MainThread 20064] OK ROK.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:40 | INFO | OK PRU.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:40,134 P[19164] [MainThread 20064] OK PRU.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:40 | INFO | OK CARR.N       | 2020-03-19 -> 2025-12-31
2026-03-24 19:13:40,645 P[19164] [MainThread 20064] OK CARR.N       | 2020-03-19 -> 2025-12-31
2026-03-24 19:13:41 | INFO | OK CAT.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:41,197 P[19164] [MainThread 20064] OK CAT.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:42 | INFO | OK GDDY.N       | 2015-04-01 -> 2025-12-31
2026-03-24 19:13:42,135 P[19164] [MainThread 20064] OK GDDY.N       | 2015-04-01 -> 2025-12-31
2026-03-24 19:13:42 | INFO | OK SPGI.N       | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:42,823 P[19164] [MainThread 20064] OK SPGI.N       | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:46 | INFO | OK SMCI.OQ      | 2020-01-14 -> 2025-12-31
2026-03-24 19:13:46,945 P[19164] [MainThread 20064] OK SMCI.OQ      | 2020-01-14 -> 2025-12-31
2026-03-24 19:13:47 | INFO | OK BAC.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:47,862 P[19164] [MainThread 20064] OK BAC.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:48 | INFO | OK MSFT.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:48,470 P[19164] [MainThread 20064] OK MSFT.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:49 | INFO | OK AMP.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:49,195 P[19164] [MainThread 20064] OK AMP.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:49 | INFO | OK HPQ.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:49,877 P[19164] [MainThread 20064] OK HPQ.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:50 | INFO | OK GIS.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:50,739 P[19164] [MainThread 20064] OK GIS.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:51 | INFO | OK AEE.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:51,448 P[19164] [MainThread 20064] OK AEE.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:51 | INFO | OK ABT.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:51,992 P[19164] [MainThread 20064] OK ABT.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:52 | INFO | OK DLR.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:52,780 P[19164] [MainThread 20064] OK DLR.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:53 | INFO | OK ULTA.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:53,311 P[19164] [MainThread 20064] OK ULTA.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:53 | INFO | OK FTNT.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:53,977 P[19164] [MainThread 20064] OK FTNT.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:54 | INFO | OK MCHP.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:54,671 P[19164] [MainThread 20064] OK MCHP.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:55 | INFO | OK REG.OQ       | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:55,191 P[19164] [MainThread 20064] OK REG.OQ       | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:55 | INFO | OK CNP.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:55,957 P[19164] [MainThread 20064] OK CNP.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:56 | INFO | OK COIN.OQ      | 2021-04-14 -> 2025-12-31
2026-03-24 19:13:56,571 P[19164] [MainThread 20064] OK COIN.OQ      | 2021-04-14 -> 2025-12-31
2026-03-24 19:13:57 | INFO | OK PAYX.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:57,169 P[19164] [MainThread 20064] OK PAYX.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:57 | INFO | OK BFb.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:57,767 P[19164] [MainThread 20064] OK BFb.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:58 | INFO | OK LMT.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:58,320 P[19164] [MainThread 20064] OK LMT.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:58 | INFO | OK TEL.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:58,804 P[19164] [MainThread 20064] OK TEL.N        | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:59 | INFO | OK J.N          | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:59,359 P[19164] [MainThread 20064] OK J.N          | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:59 | INFO | OK D.N          | 2015-01-02 -> 2025-12-31
2026-03-24 19:13:59,906 P[19164] [MainThread 20064] OK D.N          | 2015-01-02 -> 2025-12-31
2026-03-24 19:14:00 | INFO | OK ERIE.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:14:00,611 P[19164] [MainThread 20064] OK ERIE.OQ      | 2015-01-02 -> 2025-12-31
2026-03-24 19:14:01 | INFO | OK HPE.N        | 2015-10-19 -> 2025-12-31

## 9) Equity — retornos logarítmicos (diarios)

**Input:** `data/raw/equity_prices_daily.parquet` (date, ric, CLOSE, VOLUME).  
**Output:** `data/clean/equity_returns_daily.parquet` (+ `.csv`).  
**Chequeos:** filas de entrada, cantidad de RICs, filas con retorno válido, cantidad de RICs con retornos.  
**Notas:** el retorno se calcula como `ln(P_t) - ln(P_{t-1})` por activo.

In [21]:
# ======================
# EQUITY -> retornos log diarios
# ======================

# Si venís del bloque anterior, `out` está en memoria.
# Si preferís hacerlo independiente, descomentá esta lectura.
# out = pd.read_parquet(OUT.get("equity_prices_daily", RAW_DIR / "equity_prices_daily.parquet"))

# Orden + tipo numérico
out = out.sort_values(["ric", "date"]).reset_index(drop=True).copy()
out["CLOSE"] = pd.to_numeric(out["CLOSE"], errors="coerce")

logger.info(f"Filas en precios (entrada): {len(out):,}")
logger.info(f"RICs únicos en precios: {out['ric'].nunique():,}")

# Retorno log: ln(P_t) - ln(P_{t-1}) por ric
out["ret_log"] = (
    out.groupby("ric")["CLOSE"]
       .transform(lambda s: np.log(s).diff())
)

# Se eliminan las primeras observaciones sin retorno (NaN por diff)
out_ret = out.dropna(subset=["ret_log"]).copy()

logger.info(f"Filas con ret_log válido: {len(out_ret):,}")
logger.info(f"RICs con al menos un retorno: {out_ret['ric'].nunique():,}")

# Export
out_parquet = OUT.get("equity_returns_daily", CLEAN_DIR / "equity_returns_daily.parquet")
out_csv = out_parquet.with_suffix(".csv")

safe_write_parquet(out_ret, out_parquet, index=False)
out_ret.to_csv(out_csv, index=False)
logger.info(f"Output -> {out_csv.as_posix()}")

2026-03-24 19:18:02 | INFO | Filas en precios (entrada): 1,337,507
2026-03-24 19:18:02,086 P[19164] [MainThread 20064] Filas en precios (entrada): 1,337,507
2026-03-24 19:18:02 | INFO | RICs únicos en precios: 503
2026-03-24 19:18:02,148 P[19164] [MainThread 20064] RICs únicos en precios: 503
c:\Users\vidar\OneDrive\Desktop\UDESA\Tesis\Tesis-main\venv\Lib\site-packages\pandas\core\arrays\masked.py:644: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs2, **kwargs)
2026-03-24 19:18:02 | INFO | Filas con ret_log válido: 1,336,936
2026-03-24 19:18:02,572 P[19164] [MainThread 20064] Filas con ret_log válido: 1,336,936
2026-03-24 19:18:02 | INFO | RICs con al menos un retorno: 503
2026-03-24 19:18:02,635 P[19164] [MainThread 20064] RICs con al menos un retorno: 503
2026-03-24 19:18:03 | INFO | Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/clean/equity_returns_daily.parquet | rows=1,336,936 cols=5
2026-03-24 19:18:03,077 P[19164] [MainThread 20064] Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/clean/equity_returns_daily.parquet | rows=1,336,936 cols=5
2026-03-24 19:18:09 | INFO | Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/clean/equity_returns_daily.csv
2026-03-24 19:18:09,446 P[19164] [MainThread 20064] Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/clean/equity_returns_daily.csv

## 10) Mercado (S&P 500) — serie diaria y merge con retornos de equity

**Input:** candidatos de mercado (TR / índice / ETFs) vía Refinitiv; `data/clean/equity_returns_daily.parquet` (date, ric, ret_log).  
**Output:** `data/raw/market_sp500_daily.parquet` y `data/clean/equity_market_returns_daily.parquet`.  
**Chequeos:** fuente elegida, rango de fechas, filas del merge y cobertura por fecha.  
**Notas:** se prueban varias fuentes por disponibilidad/permisos; se calcula retorno log diario del mercado.

In [22]:
# ======================
# MERCADO S&P 500 -> serie diaria + merge con retornos de equity
# ======================

# Candidatos de mercado (orden de preferencia)
MARKET_CANDIDATES = [".SPXT", ".SPX", "SPY.P", "IVV.P", "VOO.P"]

def fetch_market_series(candidates: list[str]) -> tuple[str, pd.DataFrame]:
    """Intenta descargar una serie diaria de mercado y devuelve (ric_elegido, df)."""
    last_err: Optional[Exception] = None

    for ric in candidates:
        try:
            ts = ek.get_timeseries(
                ric,
                fields=["CLOSE"],
                start_date=START_DATE,
                end_date=END_DATE,
                interval="daily",
            )

            if ts is not None and not ts.empty:
                logger.info(f"Fuente de mercado elegida: {ric}")
                return ric, ts

        except Exception as e:
            last_err = e
            logger.warning(f"Intento fallido con {ric}: {type(e).__name__}: {e}")

        # Pausa suave entre intentos
        sleep_request(REQUEST_PAUSE_SEC)

    raise RuntimeError(
        "No se pudo descargar ninguna serie de mercado. "
        f"Último error: {type(last_err).__name__}: {last_err}" if last_err else
        "No se pudo descargar ninguna serie de mercado."
    )


chosen_ric, mkt_ts = fetch_market_series(MARKET_CANDIDATES)

# Normalización + retorno log del mercado
mkt = (
    mkt_ts.rename_axis(index="date")
          .reset_index()
          .rename(columns={"CLOSE": "mkt_close"})
)

mkt["date"] = pd.to_datetime(mkt["date"], errors="coerce")
if getattr(mkt["date"].dt, "tz", None) is not None:
    mkt["date"] = mkt["date"].dt.tz_localize(None)

mkt = mkt.sort_values("date").reset_index(drop=True)
mkt["mkt_close"] = pd.to_numeric(mkt["mkt_close"], errors="coerce")
mkt["mkt_ret_log"] = np.log(mkt["mkt_close"]).diff()

# Guardado de mercado
mkt_parquet = OUT.get("market_prices_daily", RAW_DIR / "market_sp500_daily.parquet")
mkt_csv = mkt_parquet.with_suffix(".csv")

safe_write_parquet(mkt, mkt_parquet, index=False)
mkt.to_csv(mkt_csv, index=False)
logger.info(f"Output -> {mkt_csv.as_posix()}")

# Merge equity + mercado (retornos)
eq_ret_path = OUT.get("equity_returns_daily", CLEAN_DIR / "equity_returns_daily.parquet")
eq_rets = pd.read_parquet(eq_ret_path)[["date", "ric", "ret_log"]].copy()

eq_rets["date"] = pd.to_datetime(eq_rets["date"], errors="coerce")
if getattr(eq_rets["date"].dt, "tz", None) is not None:
    eq_rets["date"] = eq_rets["date"].dt.tz_localize(None)

eq_mkt = (
    eq_rets.merge(mkt[["date", "mkt_ret_log"]], on="date", how="inner")
           .dropna(subset=["ret_log", "mkt_ret_log"])
           .sort_values(["ric", "date"])
           .reset_index(drop=True)
)

logger.info(f"Merge equity+mercado | filas={len(eq_mkt):,} | rics={eq_mkt['ric'].nunique():,}")

eq_mkt_parquet = OUT.get("equity_market_returns_daily", CLEAN_DIR / "equity_market_returns_daily.parquet")
safe_write_parquet(eq_mkt, eq_mkt_parquet, index=False)

2026-03-24 19:18:09,802 P[19164] [MainThread 20064] Error with .SPXT: The user does not have permission for the requested data
2026-03-24 19:18:09,803 P[19164] [MainThread 20064] .SPXT: The user does not have permission for the requested data |
2026-03-24 19:18:09 | WARNING | Intento fallido con .SPXT: EikonError: Error code -1 | .SPXT: The user does not have permission for the requested data |
2026-03-24 19:18:09,804 P[19164] [MainThread 20064] Intento fallido con .SPXT: EikonError: Error code -1 | .SPXT: The user does not have permission for the requested data |
2026-03-24 19:18:10,368 P[19164] [MainThread 20064] Error with .SPX: The user does not have permission for the requested data
2026-03-24 19:18:10,369 P[19164] [MainThread 20064] .SPX: The user does not have permission for the requested data |
2026-03-24 19:18:10 | WARNING | Intento fallido con .SPX: EikonError: Error code -1 | .SPX: The user does not have permission for the requested data |
2026-03-24 19:18:10,369 P[19164] [MainThread 20064] Intento fallido con .SPX: EikonError: Error code -1 | .SPX: The user does not have permission for the requested data |
2026-03-24 19:18:11 | INFO | Fuente de mercado elegida: SPY.P
2026-03-24 19:18:11,188 P[19164] [MainThread 20064] Fuente de mercado elegida: SPY.P
2026-03-24 19:18:11 | INFO | Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/raw/market_prices_daily.parquet | rows=2,766 cols=3
2026-03-24 19:18:11,201 P[19164] [MainThread 20064] Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/raw/market_prices_daily.parquet | rows=2,766 cols=3
2026-03-24 19:18:11 | INFO | Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/raw/market_prices_daily.csv
2026-03-24 19:18:11,215 P[19164] [MainThread 20064] Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/raw/market_prices_daily.csv
2026-03-24 19:18:12 | INFO | Merge equity+mercado | filas=1,336,936 | rics=503
2026-03-24 19:18:12,334 P[19164] [MainThread 20064] Merge equity+mercado | filas=1,336,936 | rics=503
2026-03-24 19:18:12 | INFO | Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/clean/equity_market_returns_daily.parquet | rows=1,336,936 cols=4
2026-03-24 19:18:12,664 P[19164] [MainThread 20064] Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/clean/equity_market_returns_daily.parquet | rows=1,336,936 cols=4

## 11) ETFs sectoriales — precios diarios (CLOSE)

**Input:** lista de ETFs sectoriales (RICs) vía Refinitiv.  
**Output:** `data/raw/sector_etfs_daily.parquet` (+ `.csv`).  
**Chequeos:** ETFs con datos vs sin datos, rango de fechas por ETF, cantidad de filas por serie.  
**Notas:** se aplican reintentos con backoff ante rate limits (HTTP 429) y pausas entre requests.

In [23]:
# ======================
# ETFs sectoriales -> precios diarios (CLOSE)
# ======================

# Lista de ETFs sectoriales (usar RICs si ya los tenés definidos así)
SECTOR_ETFS = [
    "XLF",     # financials
    "XLE",     # energy
    "XLK",     # tech
    "XLY",     # consumer discretionary
    "XLP",     # consumer staples
    "XLI",     # industrials
    "XLV",     # health care
    "XLU",     # utilities
    "XLRE.K",  # real estate
    "XLB",     # materials
    "XLC",     # communication services
]

def get_ts_safe(
    ric: str,
    start_date: str,
    end_date: str,
    fields: list[str] | None = None,
    max_attempts: int = 3,
) -> Optional[pd.DataFrame]:
    """
    Descarga una timeseries diaria con reintentos si aparece rate limit (429).
    Devuelve DataFrame o None si no se pudo.
    """
    if fields is None:
        fields = ["CLOSE"]

    for attempt in range(1, max_attempts + 1):
        try:
            ts = ek.get_timeseries(
                ric,
                fields=fields,
                start_date=start_date,
                end_date=end_date,
                interval="daily",
            )
            return ts

        except Exception as e:
            msg = str(e)

            # Si es 429, hacemos backoff y reintentamos
            if "429" in msg or "Too many requests" in msg:
                wait_sec = int(RETRY_BACKOFF_SEC * attempt * 2)
                logger.warning(f"429 para {ric} | espero {wait_sec}s | intento {attempt}/{max_attempts}")
                time.sleep(wait_sec)
                continue

            # Otros errores: se registra y se corta
            logger.warning(f"Error con {ric}: {type(e).__name__}: {e}")
            return None

    return None


sec_frames: list[pd.DataFrame] = []
missing: list[str] = []

logger.info(f"Descarga ETFs sectoriales | total={len(SECTOR_ETFS)}")

for ric in SECTOR_ETFS:
    logger.info(f"ETF sector: {ric}")

    ts = get_ts_safe(ric, START_DATE, END_DATE, fields=["CLOSE"], max_attempts=RETRY_MAX)

    if ts is None or ts.empty:
        logger.warning(f"Sin datos: {ric}")
        missing.append(ric)
        sleep_request(0.5)
        continue

    # Normalización estándar
    df = ts.reset_index().rename(columns={"Date": "date", "CLOSE": "price"})
    df["sector_ric"] = ric

    df["date"] = pd.to_datetime(df["date"], errors="coerce")
    if getattr(df["date"].dt, "tz", None) is not None:
        df["date"] = df["date"].dt.tz_localize(None)

    df["price"] = pd.to_numeric(df["price"], errors="coerce")

    # Log corto con rango
    dmin = df["date"].min()
    dmax = df["date"].max()
    logger.info(f"OK {ric:<6} | {dmin.date()} -> {dmax.date()} | filas={len(df):,}")

    sec_frames.append(df)

    # Pausa corta para no saturar
    sleep_request(0.5)

if not sec_frames:
    raise RuntimeError("No se pudo descargar ningún ETF sectorial (todas las series vinieron vacías).")

sectors_ts = pd.concat(sec_frames, ignore_index=True)

# Guardado
out_parquet = OUT.get("sector_etfs_daily", RAW_DIR / "sector_etfs_daily.parquet")
out_csv = out_parquet.with_suffix(".csv")

safe_write_parquet(sectors_ts, out_parquet, index=False)
sectors_ts.to_csv(out_csv, index=False)
logger.info(f"Output -> {out_csv.as_posix()}")

# Resumen de cobertura
logger.info(f"ETFs con datos: {sectors_ts['sector_ric'].nunique():,}")
logger.info(f"Filas totales: {len(sectors_ts):,}")

if missing:
    logger.warning(f"ETFs sin datos (muestra): {missing[:10]}")

# Tabla rápida de rangos por ETF (útil para QA)
summary = sectors_ts.groupby("sector_ric")["date"].agg(["min", "max", "count"]).sort_values("count", ascending=False)
logger.info("Cobertura por ETF (top):")
logger.info(summary.head(12).to_string())

2026-03-24 19:18:12 | INFO | Descarga ETFs sectoriales | total=11
2026-03-24 19:18:12,684 P[19164] [MainThread 20064] Descarga ETFs sectoriales | total=11
2026-03-24 19:18:12 | INFO | ETF sector: XLF
2026-03-24 19:18:12,686 P[19164] [MainThread 20064] ETF sector: XLF
2026-03-24 19:18:13 | INFO | OK XLF    | 2015-01-02 -> 2025-12-31 | filas=2,766
2026-03-24 19:18:13,277 P[19164] [MainThread 20064] OK XLF    | 2015-01-02 -> 2025-12-31 | filas=2,766
2026-03-24 19:18:13 | INFO | ETF sector: XLE
2026-03-24 19:18:13,779 P[19164] [MainThread 20064] ETF sector: XLE
2026-03-24 19:18:14 | INFO | OK XLE    | 2015-01-02 -> 2025-12-31 | filas=2,766
2026-03-24 19:18:14,336 P[19164] [MainThread 20064] OK XLE    | 2015-01-02 -> 2025-12-31 | filas=2,766
2026-03-24 19:18:14 | INFO | ETF sector: XLK
2026-03-24 19:18:14,838 P[19164] [MainThread 20064] ETF sector: XLK
2026-03-24 19:18:15 | INFO | OK XLK    | 2015-01-02 -> 2025-12-31 | filas=2,766
2026-03-24 19:18:15,718 P[19164] [MainThread 20064] OK XLK    | 2015-01-02 -> 2025-12-31 | filas=2,766
2026-03-24 19:18:16 | INFO | ETF sector: XLY
2026-03-24 19:18:16,220 P[19164] [MainThread 20064] ETF sector: XLY
2026-03-24 19:18:16 | INFO | OK XLY    | 2015-01-02 -> 2025-12-31 | filas=2,766
2026-03-24 19:18:16,999 P[19164] [MainThread 20064] OK XLY    | 2015-01-02 -> 2025-12-31 | filas=2,766
2026-03-24 19:18:17 | INFO | ETF sector: XLP
2026-03-24 19:18:17,502 P[19164] [MainThread 20064] ETF sector: XLP
2026-03-24 19:18:18 | INFO | OK XLP    | 2015-01-02 -> 2025-12-31 | filas=2,766
2026-03-24 19:18:18,048 P[19164] [MainThread 20064] OK XLP    | 2015-01-02 -> 2025-12-31 | filas=2,766
2026-03-24 19:18:18 | INFO | ETF sector: XLI
2026-03-24 19:18:18,550 P[19164] [MainThread 20064] ETF sector: XLI
2026-03-24 19:18:19 | INFO | OK XLI    | 2015-01-02 -> 2025-12-31 | filas=2,766
2026-03-24 19:18:19,060 P[19164] [MainThread 20064] OK XLI    | 2015-01-02 -> 2025-12-31 | filas=2,766
2026-03-24 19:18:19 | INFO | ETF sector: XLV
2026-03-24 19:18:19,562 P[19164] [MainThread 20064] ETF sector: XLV
2026-03-24 19:18:20 | INFO | OK XLV    | 2015-01-02 -> 2025-12-31 | filas=2,766
2026-03-24 19:18:20,303 P[19164] [MainThread 20064] OK XLV    | 2015-01-02 -> 2025-12-31 | filas=2,766
2026-03-24 19:18:20 | INFO | ETF sector: XLU
2026-03-24 19:18:20,805 P[19164] [MainThread 20064] ETF sector: XLU
2026-03-24 19:18:21 | INFO | OK XLU    | 2015-01-02 -> 2025-12-31 | filas=2,766
2026-03-24 19:18:21,210 P[19164] [MainThread 20064] OK XLU    | 2015-01-02 -> 2025-12-31 | filas=2,766
2026-03-24 19:18:21 | INFO | ETF sector: XLRE.K
2026-03-24 19:18:21,712 P[19164] [MainThread 20064] ETF sector: XLRE.K
2026-03-24 19:18:22 | INFO | OK XLRE.K | 2015-10-08 -> 2025-12-31 | filas=2,571
2026-03-24 19:18:22,421 P[19164] [MainThread 20064] OK XLRE.K | 2015-10-08 -> 2025-12-31 | filas=2,571
2026-03-24 19:18:22 | INFO | ETF sector: XLB
2026-03-24 19:18:22,923 P[19164] [MainThread 20064] ETF sector: XLB
2026-03-24 19:18:23 | INFO | OK XLB    | 2015-01-02 -> 2025-12-31 | filas=2,766
2026-03-24 19:18:23,642 P[19164] [MainThread 20064] OK XLB    | 2015-01-02 -> 2025-12-31 | filas=2,766
2026-03-24 19:18:24 | INFO | ETF sector: XLC
2026-03-24 19:18:24,145 P[19164] [MainThread 20064] ETF sector: XLC
2026-03-24 19:18:24 | INFO | OK XLC    | 2018-06-19 -> 2025-12-31 | filas=1,895
2026-03-24 19:18:24,876 P[19164] [MainThread 20064] OK XLC    | 2018-06-19 -> 2025-12-31 | filas=1,895
2026-03-24 19:18:25 | INFO | Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/raw/sector_etfs_daily.parquet | rows=29,360 cols=3
2026-03-24 19:18:25,393 P[19164] [MainThread 20064] Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/raw/sector_etfs_daily.parquet | rows=29,360 cols=3
2026-03-24 19:18:25 | INFO | Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/raw/sector_etfs_daily.csv
2026-03-24 19:18:25,463 P[19164] [MainThread 20064] Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/raw/sector_etfs_daily.csv
2026-03-24 19:18:25 | INFO | ETFs con datos: 11
2026-03-24 19:18:25,466 P[19164] [MainThread 20064] ETFs con datos: 11
2026-03-24 19:18:25 | INFO | Filas totales: 29,360
2026-03-24 19:18:25,468 P[19164] [MainThread 20064] Filas totales: 29,360
2026-03-24 19:18:25 | INFO | Cobertura por ETF (top):
2026-03-24 19:18:25,473 P[19164] [MainThread 20064] Cobertura por ETF (top):
2026-03-24 19:18:25 | INFO |                   min        max  count
sector_ric
XLB        2015-01-02 2025-12-31   2766
XLE        2015-01-02 2025-12-31   2766
XLF        2015-01-02 2025-12-31   2766
XLI        2015-01-02 2025-12-31   2766
XLK        2015-01-02 2025-12-31   2766
XLP        2015-01-02 2025-12-31   2766
XLU        2015-01-02 2025-12-31   2766
XLV        2015-01-02 2025-12-31   2766
XLY        2015-01-02 2025-12-31   2766
XLRE.K     2015-10-08 2025-12-31   2571
XLC        2018-06-19 2025-12-31   1895
2026-03-24 19:18:25,476 P[19164] [MainThread 20064]                   min        max  count
sector_ric
XLB        2015-01-02 2025-12-31   2766
XLE        2015-01-02 2025-12-31   2766
XLF        2015-01-02 2025-12-31   2766
XLI        2015-01-02 2025-12-31   2766
XLK        2015-01-02 2025-12-31   2766
XLP        2015-01-02 2025-12-31   2766
XLU        2015-01-02 2025-12-31   2766
XLV        2015-01-02 2025-12-31   2766
XLY        2015-01-02 2025-12-31   2766
XLRE.K     2015-10-08 2025-12-31   2571
XLC        2018-06-19 2025-12-31   1895

## 12) Fundamentals — descarga trimestral (Refinitiv)

**Input:** `data/inputs/empresas_tickers_test.csv` (Ticker) + overrides de RIC puntuales.  
**Output:** `data/raw/fundamentals_extended_q.parquet` (+ `.csv`).  
**Chequeos:** RICs con fundamentals vs sin fundamentals; quarters esperados por firma; duplicados por (ric, date).  
**Notas:** se descarga por batches con backoff ante rate limits (HTTP 429). La fecha trimestral se asigna por grilla Q 2015–2025 para uniformizar el panel.

In [24]:
# ======================
# FUNDAMENTALS -> descarga trimestral (Q) por batches
# ======================

import math
import time
from typing import Iterable

# Overrides puntuales de RIC para consultas (casos conocidos)
RIC_OVERRIDE = {
    "PEP":   "PEP.O",
    "ABBV":  "ABBV.K",
    "HON":   "HON.O",
    "AAPL":  "AAPL.O",
    "CSCO":  "CSCO.O",
    "ORCL":  "ORCL.K",
    "META":  "META.O",
    "GOOGL": "GOOGL.O",
    "MSFT":  "MSFT.O",
}

# Fields (fundamentals extendidos)
FUND_FIELDS = [
    "TR.F.TotAssets",
    "TR.F.TotLiab",
    "TR.F.TotShHoldEq",
    "TR.F.TotCurrAssets",
    "TR.F.TotCurrLiab",
    "TR.TotalDebtActValue",
    "TR.F.CashSTInvst",
    "TR.F.STDebtCurrPortOfLTDebt",
    "TR.F.DebtLTTot",
    "TR.F.TotRevenue",
    "TR.F.EBITDA",
    "TR.F.NetCashFlowOp",
    "TR.IntExp",
    "TR.F.CAPEXTot",
]

FUND_PARAMS = {
    "SDate": "2015-01-01",
    "EDate": "2025-12-31",
    "Frq": "Q",
    "Curn": "USD",
}

BATCH_SIZE = 20
SLEEP_BATCH_SEC = 1.0
MAX_RETRY = 3


def chunked(items: list[str], n: int) -> Iterable[list[str]]:
    for i in range(0, len(items), n):
        yield items[i:i + n]


def get_data_safe(
    rics_batch: list[str],
    fields: list[str],
    params: dict,
    max_retry: int = 3
) -> pd.DataFrame:
    """
    Wrapper para ek.get_data con reintentos ante 429.
    Devuelve DataFrame (puede venir vacío).
    """
    for attempt in range(1, max_retry + 1):
        try:
            df, err = ek.get_data(rics_batch, fields=fields, parameters=params)

            if err is not None and len(err):
                logger.warning(f"Refinitiv devolvió warnings/errores (muestra): {str(err[:2])}")

            return df if df is not None else pd.DataFrame()

        except Exception as e:
            msg = str(e)

            if "429" in msg or "Too many requests" in msg:
                wait_sec = 4 + (attempt - 1) * 4
                logger.warning(f"429 en batch | espero {wait_sec}s | intento {attempt}/{max_retry}")
                time.sleep(wait_sec)
                continue

            logger.warning(f"Error en batch (no 429): {type(e).__name__}: {e}")
            return pd.DataFrame()

    return pd.DataFrame()


def to_snake(col: str) -> str:
    x = col.replace("TR.", "").replace("F.", "").replace(":", ".")
    x = x.replace(".", "_")
    return x.lower()


# ----------------------
# 1) Universo + ric_query
# ----------------------
df_emp = pd.read_csv(UNIVERSE_FILE, dtype=str).dropna(subset=["Ticker"]).reset_index(drop=True)

df_emp["ticker"] = df_emp["Ticker"].astype(str).str.strip()
df_emp["ric_query"] = df_emp["ticker"].map(RIC_OVERRIDE).fillna(df_emp["ticker"])

rics = df_emp["ric_query"].dropna().astype(str).unique().tolist()

logger.info(f"Empresas en universo: {len(df_emp):,}")
logger.info(f"RICs únicos (consulta): {len(rics):,}")


# ----------------------
# 2) Descarga por batches
# ----------------------
all_frames: list[pd.DataFrame] = []

logger.info("Descargando fundamentals (Q) por batches...")

for i, batch in enumerate(chunked(rics, BATCH_SIZE), start=1):
    logger.info(f"Batch {i} | size={len(batch)}")

    df_batch = get_data_safe(batch, FUND_FIELDS, FUND_PARAMS, max_retry=MAX_RETRY)
    if not df_batch.empty:
        all_frames.append(df_batch)

    time.sleep(SLEEP_BATCH_SEC)

if not all_frames:
    raise RuntimeError("No se descargaron fundamentals. Revisar fields/permisos/conexión.")

fund = pd.concat(all_frames, ignore_index=True)


# ----------------------
# 3) Normalización de columnas
# ----------------------
if "Instrument" in fund.columns:
    fund = fund.rename(columns={"Instrument": "ric"})
elif "RIC" in fund.columns:
    fund = fund.rename(columns={"RIC": "ric"})

fund.columns = [to_snake(c) for c in fund.columns]


# ----------------------
# 4) Mapeo de rastreo (ticker original)
# ----------------------
df_map = df_emp[["ticker", "ric_query"]].rename(columns={"ric_query": "ric"})
fund = fund.merge(df_map, on="ric", how="left")


# ----------------------
# 5) Fecha trimestral (grilla Q 2015–2025)
# ----------------------
start_q = pd.Timestamp("2015-01-01")
end_q   = pd.Timestamp("2025-12-31")
full_q_range = pd.date_range(start=start_q, end=end_q, freq="Q")


def assign_quarter_grid(g: pd.DataFrame) -> pd.DataFrame:
    g = g.reset_index(drop=True)
    n = len(g)

    if n == 0:
        return g

    reps = math.ceil(n / len(full_q_range))
    dates = list(full_q_range) * reps
    g["date"] = dates[:n]
    return g


fund = fund.groupby("ric", group_keys=False).apply(assign_quarter_grid)

fund = (
    fund.sort_values(["ric", "date"])
        .groupby(["ric", "date"], as_index=False)
        .first()
)


# ----------------------
# 6) QA y export
# ----------------------
logger.info(f"Fundamentals final | filas={len(fund):,} | rics={fund['ric'].nunique():,}")
logger.info(f"Quarters esperados (grilla): {len(full_q_range):,}")

missing = df_emp.loc[
    ~df_emp["ric_query"].isin(fund["ric"]),
    ["Issuer", "ticker", "ric_query"]
]

if not missing.empty:
    logger.warning(f"Empresas sin fundamentals: {len(missing):,}")
    logger.warning(missing.head(20).to_string(index=False))

out_parquet = OUT.get("fundamentals_q", RAW_DIR / "fundamentals_extended_q.parquet")
out_csv = out_parquet.with_suffix(".csv")

safe_write_parquet(fund, out_parquet, index=False)
fund.to_csv(out_csv, index=False)

logger.info(f"Output -> {out_csv.as_posix()}")

2026-03-24 19:18:25 | INFO | Empresas en universo: 503
2026-03-24 19:18:25,511 P[19164] [MainThread 20064] Empresas en universo: 503
2026-03-24 19:18:25 | INFO | RICs únicos (consulta): 503
2026-03-24 19:18:25,513 P[19164] [MainThread 20064] RICs únicos (consulta): 503
2026-03-24 19:18:25 | INFO | Descargando fundamentals (Q) por batches...
2026-03-24 19:18:25,524 P[19164] [MainThread 20064] Descargando fundamentals (Q) por batches...
2026-03-24 19:18:25 | INFO | Batch 1 | size=20
2026-03-24 19:18:25,525 P[19164] [MainThread 20064] Batch 1 | size=20
c:\Users\vidar\OneDrive\Desktop\UDESA\Tesis\Tesis-main\venv\Lib\site-packages\pandas\core\dtypes\cast.py:1056: RuntimeWarning: invalid value encountered in cast
  if (arr.astype(int) == arr).all():
c:\Users\vidar\OneDrive\Desktop\UDESA\Tesis\Tesis-main\venv\Lib\site-packages\pandas\core\dtypes\cast.py:1080: RuntimeWarning: invalid value encountered in cast
  if (arr.astype(int) == arr).all():
2026-03-24 19:18:29 | WARNING | Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 1276}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 1276}]
2026-03-24 19:18:29,973 P[19164] [MainThread 20064] Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 1276}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 1276}]
2026-03-24 19:18:30 | INFO | Batch 2 | size=20
2026-03-24 19:18:30,978 P[19164] [MainThread 20064] Batch 2 | size=20
2026-03-24 19:18:33 | WARNING | Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 0}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 0}]
2026-03-24 19:18:33,872 P[19164] [MainThread 20064] Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 0}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 0}]
2026-03-24 19:18:34 | INFO | Batch 3 | size=20
2026-03-24 19:18:34,874 P[19164] [MainThread 20064] Batch 3 | size=20
2026-03-24 19:18:38 | WARNING | Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 792}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 792}]
2026-03-24 19:18:38,473 P[19164] [MainThread 20064] Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 792}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 792}]
2026-03-24 19:18:39 | INFO | Batch 4 | size=20
2026-03-24 19:18:39,476 P[19164] [MainThread 20064] Batch 4 | size=20
2026-03-24 19:18:43 | WARNING | Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 0}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 0}]
2026-03-24 19:18:43,767 P[19164] [MainThread 20064] Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 0}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 0}]
2026-03-24 19:18:44 | INFO | Batch 5 | size=20
2026-03-24 19:18:44,769 P[19164] [MainThread 20064] Batch 5 | size=20
2026-03-24 19:18:48 | WARNING | Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 1716}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 1716}]
2026-03-24 19:18:48,047 P[19164] [MainThread 20064] Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 1716}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 1716}]
2026-03-24 19:18:49 | INFO | Batch 6 | size=20
2026-03-24 19:18:49,050 P[19164] [MainThread 20064] Batch 6 | size=20
2026-03-24 19:18:52 | WARNING | Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 2376}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 2376}]
2026-03-24 19:18:52,147 P[19164] [MainThread 20064] Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 2376}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 2376}]
2026-03-24 19:18:53 | INFO | Batch 7 | size=20
2026-03-24 19:18:53,149 P[19164] [MainThread 20064] Batch 7 | size=20
2026-03-24 19:18:58 | WARNING | Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 0}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 0}]
2026-03-24 19:18:58,309 P[19164] [MainThread 20064] Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 0}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 0}]
2026-03-24 19:18:59 | INFO | Batch 8 | size=20
2026-03-24 19:18:59,311 P[19164] [MainThread 20064] Batch 8 | size=20
2026-03-24 19:19:02 | WARNING | Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 0}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 0}]
2026-03-24 19:19:02,778 P[19164] [MainThread 20064] Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 0}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 0}]
2026-03-24 19:19:03 | INFO | Batch 9 | size=20
2026-03-24 19:19:03,780 P[19164] [MainThread 20064] Batch 9 | size=20
2026-03-24 19:19:07 | WARNING | Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 0}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 0}]
2026-03-24 19:19:07,253 P[19164] [MainThread 20064] Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 0}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 0}]
2026-03-24 19:19:08 | INFO | Batch 10 | size=20
2026-03-24 19:19:08,255 P[19164] [MainThread 20064] Batch 10 | size=20
2026-03-24 19:19:12 | WARNING | Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 0}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 0}]
2026-03-24 19:19:12,143 P[19164] [MainThread 20064] Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 0}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 0}]
2026-03-24 19:19:13 | INFO | Batch 11 | size=20
2026-03-24 19:19:13,146 P[19164] [MainThread 20064] Batch 11 | size=20
2026-03-24 19:19:16 | WARNING | Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 0}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 0}]
2026-03-24 19:19:16,979 P[19164] [MainThread 20064] Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 0}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 0}]
2026-03-24 19:19:17 | INFO | Batch 12 | size=20
2026-03-24 19:19:17,981 P[19164] [MainThread 20064] Batch 12 | size=20
2026-03-24 19:19:22 | WARNING | Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 2376}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 2376}]
2026-03-24 19:19:22,246 P[19164] [MainThread 20064] Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 2376}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 2376}]
2026-03-24 19:19:23 | INFO | Batch 13 | size=20
2026-03-24 19:19:23,247 P[19164] [MainThread 20064] Batch 13 | size=20
2026-03-24 19:19:26 | WARNING | Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 572}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 572}]
2026-03-24 19:19:26,727 P[19164] [MainThread 20064] Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 572}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 572}]
2026-03-24 19:19:27 | INFO | Batch 14 | size=20
2026-03-24 19:19:27,730 P[19164] [MainThread 20064] Batch 14 | size=20
2026-03-24 19:19:31 | WARNING | Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 1716}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 1716}]
2026-03-24 19:19:31,353 P[19164] [MainThread 20064] Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 1716}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 1716}]
2026-03-24 19:19:32 | INFO | Batch 15 | size=20
2026-03-24 19:19:32,357 P[19164] [MainThread 20064] Batch 15 | size=20
2026-03-24 19:19:37 | WARNING | Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 0}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 0}]
2026-03-24 19:19:37,077 P[19164] [MainThread 20064] Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 0}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 0}]
2026-03-24 19:19:38 | INFO | Batch 16 | size=20
2026-03-24 19:19:38,080 P[19164] [MainThread 20064] Batch 16 | size=20
2026-03-24 19:19:41 | WARNING | Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 1760}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 1760}]
2026-03-24 19:19:41,082 P[19164] [MainThread 20064] Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 1760}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 1760}]
2026-03-24 19:19:42 | INFO | Batch 17 | size=20
2026-03-24 19:19:42,085 P[19164] [MainThread 20064] Batch 17 | size=20
2026-03-24 19:19:45 | WARNING | Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 0}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 0}]
2026-03-24 19:19:45,964 P[19164] [MainThread 20064] Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 0}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 0}]
2026-03-24 19:19:46 | INFO | Batch 18 | size=20
2026-03-24 19:19:46,967 P[19164] [MainThread 20064] Batch 18 | size=20
2026-03-24 19:19:50 | WARNING | Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 0}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 0}]
2026-03-24 19:19:50,897 P[19164] [MainThread 20064] Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 0}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 0}]
2026-03-24 19:19:51 | INFO | Batch 19 | size=20
2026-03-24 19:19:51,898 P[19164] [MainThread 20064] Batch 19 | size=20
2026-03-24 19:20:00 | WARNING | Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 0}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 0}]
2026-03-24 19:20:00,757 P[19164] [MainThread 20064] Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 0}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 0}]
2026-03-24 19:20:01 | INFO | Batch 20 | size=20
2026-03-24 19:20:01,760 P[19164] [MainThread 20064] Batch 20 | size=20
2026-03-24 19:20:05 | WARNING | Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 748}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 748}]
2026-03-24 19:20:05,787 P[19164] [MainThread 20064] Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 748}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 748}]
2026-03-24 19:20:06 | INFO | Batch 21 | size=20
2026-03-24 19:20:06,789 P[19164] [MainThread 20064] Batch 21 | size=20
2026-03-24 19:20:09 | WARNING | Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 352}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 352}]
2026-03-24 19:20:09,879 P[19164] [MainThread 20064] Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 352}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 352}]
2026-03-24 19:20:10 | INFO | Batch 22 | size=20
2026-03-24 19:20:10,883 P[19164] [MainThread 20064] Batch 22 | size=20
2026-03-24 19:20:14 | WARNING | Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 968}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 968}]
2026-03-24 19:20:14,253 P[19164] [MainThread 20064] Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 1, 'message': "Unable to collect data for the field 'TR.F.TotAssets' and some specific identifier(s).", 'row': 968}, {'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.F.TotLiab' and some specific identifier(s).", 'row': 968}]
2026-03-24 19:20:15 | INFO | Batch 23 | size=20
2026-03-24 19:20:15,255 P[19164] [MainThread 20064] Batch 23 | size=20
2026-03-24 19:20:19 | WARNING | Refinitiv devolvió warnings/errores (muestra): [{'code': 416, 'col': 6, 'message': "Unable to collect data for the field 'TR.TotalDebtActValue' and some specific identifier(s).", 'row': 2288}, {'code': 416, 'col': 13, 'message': "Unable to collect data for the field 'TR.IntExp' and some specific identifier(s).", 'row': 2288}]

## 13) Curva soberana USD (UST) — yields diarios por tenor

**Input:** RICs de UST (`US1MT=RR`, `US3MT=RR`, …) vía Refinitiv.  
**Output:** `data/raw/ust_yield_curve_daily.parquet` (+ `.csv`).  
**Chequeos:** tenores con datos vs sin datos, rango de fechas por tenor, cantidad de filas.  
**Notas:** se aplican reintentos con backoff ante rate limits (HTTP 429) y pausas entre requests.

In [25]:
# ======================
# UST yield curve -> daily (por tenor)
# ======================

UST_RICS = {
    "US1M":  "US1MT=RR",
    "US3M":  "US3MT=RR",
    "US6M":  "US6MT=RR",
    "US1Y":  "US1YT=RR",
    "US2Y":  "US2YT=RR",
    "US3Y":  "US3YT=RR",
    "US5Y":  "US5YT=RR",
    "US7Y":  "US7YT=RR",
    "US10Y": "US10YT=RR",
    "US30Y": "US30YT=RR",
}

def get_ts_safe(
    ric: str,
    start_date: str,
    end_date: str,
    fields: list[str] | None = None,
    max_attempts: int = 3,
) -> Optional[pd.DataFrame]:
    """Timeseries diaria con reintentos si cae 429. Devuelve DataFrame o None."""
    if fields is None:
        fields = ["CLOSE"]

    for attempt in range(1, max_attempts + 1):
        try:
            ts = ek.get_timeseries(
                ric,
                fields=fields,
                start_date=start_date,
                end_date=end_date,
                interval="daily",
            )
            return ts

        except Exception as e:
            msg = str(e)

            if "429" in msg or "Too many requests" in msg:
                wait_sec = 4 + (attempt - 1) * 4
                logger.warning(f"429 para {ric} | espero {wait_sec}s | intento {attempt}/{max_attempts}")
                time.sleep(wait_sec)
                continue

            logger.warning(f"Error con {ric}: {type(e).__name__}: {e}")
            return None

    return None


logger.info("Descargando curva UST (USD) por tenor...")
logger.info(f"Tenores: {list(UST_RICS.keys())}")

ust_frames: list[pd.DataFrame] = []
missing: list[str] = []

for tenor, ric in UST_RICS.items():
    logger.info(f"UST {tenor} | {ric}")

    ts = get_ts_safe(ric, START_DATE, END_DATE, fields=["CLOSE"], max_attempts=RETRY_MAX)

    if ts is None or ts.empty:
        logger.warning(f"Sin datos: {tenor} ({ric})")
        missing.append(tenor)
        sleep_request(0.4)
        continue

    df = ts.reset_index().rename(columns={"Date": "date", "CLOSE": "yield"})
    df["tenor"] = tenor
    df["ric"] = ric

    df["date"] = pd.to_datetime(df["date"], errors="coerce")
    if getattr(df["date"].dt, "tz", None) is not None:
        df["date"] = df["date"].dt.tz_localize(None)

    df["yield"] = pd.to_numeric(df["yield"], errors="coerce")

    dmin = df["date"].min()
    dmax = df["date"].max()
    logger.info(f"OK {tenor:<4} | {dmin.date()} -> {dmax.date()} | filas={len(df):,}")

    ust_frames.append(df)

    # Pausa corta para no saturar
    sleep_request(0.4)

if not ust_frames:
    raise RuntimeError("No se pudo descargar ningún punto de la curva UST.")

ust = pd.concat(ust_frames, ignore_index=True)

# Export
out_parquet = OUT.get("ust_yield_curve_daily", RAW_DIR / "ust_yield_curve_daily.parquet")
out_csv = out_parquet.with_suffix(".csv")

safe_write_parquet(ust, out_parquet, index=False)
ust.to_csv(out_csv, index=False)
logger.info(f"Output -> {out_csv.as_posix()}")

# Resumen corto
logger.info(f"Tenores con datos: {ust['tenor'].nunique():,}")
logger.info(f"Filas totales: {len(ust):,}")
logger.info(f"Rango global: {ust['date'].min().date()} -> {ust['date'].max().date()}")

if missing:
    logger.warning(f"Tenores sin datos: {missing}")

2026-03-24 19:20:33 | INFO | Descargando curva UST (USD) por tenor...
2026-03-24 19:20:33,425 P[19164] [MainThread 20064] Descargando curva UST (USD) por tenor...
2026-03-24 19:20:33 | INFO | Tenores: ['US1M', 'US3M', 'US6M', 'US1Y', 'US2Y', 'US3Y', 'US5Y', 'US7Y', 'US10Y', 'US30Y']
2026-03-24 19:20:33,433 P[19164] [MainThread 20064] Tenores: ['US1M', 'US3M', 'US6M', 'US1Y', 'US2Y', 'US3Y', 'US5Y', 'US7Y', 'US10Y', 'US30Y']
2026-03-24 19:20:33 | INFO | UST US1M | US1MT=RR
2026-03-24 19:20:33,442 P[19164] [MainThread 20064] UST US1M | US1MT=RR
2026-03-24 19:20:34 | INFO | OK US1M | 2015-01-02 -> 2025-12-31 | filas=2,750
2026-03-24 19:20:34,084 P[19164] [MainThread 20064] OK US1M | 2015-01-02 -> 2025-12-31 | filas=2,750
2026-03-24 19:20:34 | INFO | UST US3M | US3MT=RR
2026-03-24 19:20:34,486 P[19164] [MainThread 20064] UST US3M | US3MT=RR
2026-03-24 19:20:35 | INFO | OK US3M | 2015-01-02 -> 2025-12-31 | filas=2,750
2026-03-24 19:20:35,414 P[19164] [MainThread 20064] OK US3M | 2015-01-02 -> 2025-12-31 | filas=2,750
2026-03-24 19:20:35 | INFO | UST US6M | US6MT=RR
2026-03-24 19:20:35,816 P[19164] [MainThread 20064] UST US6M | US6MT=RR
2026-03-24 19:20:36 | INFO | OK US6M | 2015-01-02 -> 2025-12-31 | filas=2,750
2026-03-24 19:20:36,462 P[19164] [MainThread 20064] OK US6M | 2015-01-02 -> 2025-12-31 | filas=2,750
2026-03-24 19:20:36 | INFO | UST US1Y | US1YT=RR
2026-03-24 19:20:36,865 P[19164] [MainThread 20064] UST US1Y | US1YT=RR
2026-03-24 19:20:37 | INFO | OK US1Y | 2015-01-02 -> 2025-12-31 | filas=2,750
2026-03-24 19:20:37,292 P[19164] [MainThread 20064] OK US1Y | 2015-01-02 -> 2025-12-31 | filas=2,750
2026-03-24 19:20:37 | INFO | UST US2Y | US2YT=RR
2026-03-24 19:20:37,694 P[19164] [MainThread 20064] UST US2Y | US2YT=RR
2026-03-24 19:20:38 | INFO | OK US2Y | 2015-01-02 -> 2025-12-31 | filas=2,750
2026-03-24 19:20:38,178 P[19164] [MainThread 20064] OK US2Y | 2015-01-02 -> 2025-12-31 | filas=2,750
2026-03-24 19:20:38 | INFO | UST US3Y | US3YT=RR
2026-03-24 19:20:38,581 P[19164] [MainThread 20064] UST US3Y | US3YT=RR
2026-03-24 19:20:39 | INFO | OK US3Y | 2015-01-02 -> 2025-12-31 | filas=2,750
2026-03-24 19:20:39,516 P[19164] [MainThread 20064] OK US3Y | 2015-01-02 -> 2025-12-31 | filas=2,750
2026-03-24 19:20:39 | INFO | UST US5Y | US5YT=RR
2026-03-24 19:20:39,918 P[19164] [MainThread 20064] UST US5Y | US5YT=RR
2026-03-24 19:20:40 | INFO | OK US5Y | 2015-01-02 -> 2025-12-31 | filas=2,750
2026-03-24 19:20:40,669 P[19164] [MainThread 20064] OK US5Y | 2015-01-02 -> 2025-12-31 | filas=2,750
2026-03-24 19:20:41 | INFO | UST US7Y | US7YT=RR
2026-03-24 19:20:41,071 P[19164] [MainThread 20064] UST US7Y | US7YT=RR
2026-03-24 19:20:41 | INFO | OK US7Y | 2015-01-02 -> 2025-12-31 | filas=2,750
2026-03-24 19:20:41,540 P[19164] [MainThread 20064] OK US7Y | 2015-01-02 -> 2025-12-31 | filas=2,750
2026-03-24 19:20:41 | INFO | UST US10Y | US10YT=RR
2026-03-24 19:20:41,943 P[19164] [MainThread 20064] UST US10Y | US10YT=RR
2026-03-24 19:20:42 | INFO | OK US10Y | 2015-01-02 -> 2025-12-31 | filas=2,750
2026-03-24 19:20:42,305 P[19164] [MainThread 20064] OK US10Y | 2015-01-02 -> 2025-12-31 | filas=2,750
2026-03-24 19:20:42 | INFO | UST US30Y | US30YT=RR
2026-03-24 19:20:42,708 P[19164] [MainThread 20064] UST US30Y | US30YT=RR
2026-03-24 19:20:43 | INFO | OK US30Y | 2015-01-02 -> 2025-12-31 | filas=2,750
2026-03-24 19:20:43,365 P[19164] [MainThread 20064] OK US30Y | 2015-01-02 -> 2025-12-31 | filas=2,750
2026-03-24 19:20:43 | INFO | Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/raw/ust_yield_curve_daily.parquet | rows=27,500 cols=4
2026-03-24 19:20:43,782 P[19164] [MainThread 20064] Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/raw/ust_yield_curve_daily.parquet | rows=27,500 cols=4
2026-03-24 19:20:43 | INFO | Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/raw/ust_yield_curve_daily.csv
2026-03-24 19:20:43,850 P[19164] [MainThread 20064] Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/raw/ust_yield_curve_daily.csv
2026-03-24 19:20:43 | INFO | Tenores con datos: 10
2026-03-24 19:20:43,852 P[19164] [MainThread 20064] Tenores con datos: 10
2026-03-24 19:20:43 | INFO | Filas totales: 27,500
2026-03-24 19:20:43,853 P[19164] [MainThread 20064] Filas totales: 27,500
2026-03-24 19:20:43 | INFO | Rango global: 2015-01-02 -> 2025-12-31
2026-03-24 19:20:43,855 P[19164] [MainThread 20064] Rango global: 2015-01-02 -> 2025-12-31

## 13bis) OAS por bono — histórico mensual (Refinitiv)

In [30]:
# ======================
# OAS -> histórico mensual por bono (batch = 25 RICs)
# ======================

if "df_bonds_universe" not in globals():
    raise RuntimeError(
        "df_bonds_universe no existe en memoria. "
        "Primero corré la celda que construye el universo de bonos desde "
        "'data/inputs/new_bonds/' y lo filtra por el universo S&P 500."
    )

if "bond_ric" not in df_bonds_universe.columns:
    raise RuntimeError(
        "df_bonds_universe no tiene columna 'bond_ric'. "
        "Revisá la celda de bonos para preservar el RIC del bono."
    )

bonds_full = df_bonds_universe.copy()

bond_rics = (
    bonds_full["bond_ric"]
    .dropna()
    .astype(str)
    .str.strip()
    .replace({"": pd.NA, "nan": pd.NA, "None": pd.NA})
    .dropna()
    .unique()
    .tolist()
)

logger.info(f"Bond RICs para OAS: {len(bond_rics):,}")

if len(bond_rics) == 0:
    raise RuntimeError("La lista de bond_rics quedó vacía.")

# -------------------------------------------------
# Helper para batches
# -------------------------------------------------
def chunk_list(lst, n):
    for i in range(0, len(lst), n):
        yield lst[i:i+n]

BATCH_SIZE = 25
MAX_RETRIES = 3

oas_frames = []
failed_rics = []
batch_logs = []

total_batches = int(np.ceil(len(bond_rics) / BATCH_SIZE))

for bnum, batch in enumerate(chunk_list(bond_rics, BATCH_SIZE), start=1):
    success = False
    batch_start = time.time()
    batch_errs = []

    print("\n" + "="*60)
    print(f"BATCH {bnum}/{total_batches} | tamaño = {len(batch)}")
    print("="*60)

    for attempt in range(1, MAX_RETRIES + 1):
        try:
            df, err = ek.get_data(
                batch,
                ["TR.OPTIONADJUSTEDSPREADBID.date", "TR.OPTIONADJUSTEDSPREADBID"],
                parameters={
                    "SDate": START_DATE,
                    "EDate": END_DATE,
                    "Frq": "M"
                }
            )

            n_rows = 0 if df is None else len(df)
            n_errs = 0 if err is None else len(err)

            print(f"Intento {attempt} | filas: {n_rows} | errores: {n_errs}")

            # registrar errores individuales
            if err is not None and len(err):
                for e in err:
                    batch_errs.append(e)

                    row = e.get("row")
                    if row is not None and 0 <= row < len(batch):
                        failed_rics.append(batch[row])

            if df is not None and len(df) > 0:
                oas_frames.append(df)

            success = True
            break

        except Exception as e:
            msg = str(e)
            print(f"Intento {attempt} falló: {msg}")

            if "400" in msg or "Backend error" in msg:
                time.sleep(10 * attempt)
            else:
                time.sleep(3 * attempt)

    if not success:
        print("❌ Batch fallido")
        failed_rics.extend(batch)

    batch_time = time.time() - batch_start
    print(f"Tiempo batch: {batch_time:.2f} s")

    if batch_errs:
        print(f"⚠️ Errores en batch: {len(batch_errs)}")

    # progreso cada 10 batches
    if bnum % 10 == 0 or bnum == total_batches:
        covered = min(bnum * BATCH_SIZE, len(bond_rics))
        print(
            f"\n>>> PROGRESO: {covered:,}/{len(bond_rics):,} bonos "
            f"({100*covered/len(bond_rics):.2f}%)"
        )

    sleep_request(1.5)

    if not success:
        failed_rics.extend(batch)

    batch_time = time.time() - batch_start
    batch_logs.append({
        "batch_num": bnum,
        "batch_size": len(batch),
        "success": success,
        "seconds": round(batch_time, 2),
        "n_errs": len(batch_errs),
    })

    if bnum % 10 == 0 or bnum == total_batches:
        covered = min(bnum * BATCH_SIZE, len(bond_rics))
        logger.info(f"OAS progreso: batch {bnum:,} / {total_batches:,} | bonos aprox. {covered:,} / {len(bond_rics):,}")

    # pausa entre batches
    sleep_request(1.5)

oas_all = pd.concat(oas_frames, ignore_index=True) if oas_frames else pd.DataFrame()

print("\n=== OAS HIST ALL ===")
print("Shape:", oas_all.shape)

if oas_all.empty:
    logger.warning("No se descargó ningún OAS.")
else:
    oas_all["Date"] = pd.to_datetime(oas_all["Date"], errors="coerce")
    if getattr(oas_all["Date"].dt, "tz", None) is not None:
        oas_all["Date"] = oas_all["Date"].dt.tz_localize(None)

    oas_all["Option Adjusted Spread Bid"] = pd.to_numeric(
        oas_all["Option Adjusted Spread Bid"], errors="coerce"
    )

    oas_all = oas_all.rename(columns={
        "Instrument": "bond_ric",
        "Date": "date",
        "Option Adjusted Spread Bid": "oas_bps"
    })

    oas_all = oas_all.merge(
        bonds_full[["Issuer", "Ticker", "bond_ric"]].drop_duplicates(),
        on="bond_ric",
        how="left",
        validate="m:1"
    )

    oas_all = oas_all.sort_values(["bond_ric", "date"]).reset_index(drop=True)

    coverage = (
        oas_all.groupby("bond_ric")
        .agg(
            first_date=("date", "min"),
            last_date=("date", "max"),
            n_obs=("oas_bps", "count")
        )
        .reset_index()
    )

    print("\n=== OAS COVERAGE ===")
    print(coverage.head())

    safe_write_parquet(
        oas_all,
        OUT["oas_spreads_monthly_bond"],
        index=False
    )
    oas_all.to_csv(OUT["oas_spreads_monthly_bond"].with_suffix(".csv"), index=False)

    coverage.to_csv(
        OUT["oas_spreads_monthly_bond"].with_name("oas_coverage_report.csv"),
        index=False
    )

    pd.DataFrame({"bond_ric": sorted(set(failed_rics))}).to_csv(
        OUT["oas_spreads_monthly_bond"].with_name("oas_failed_rics.csv"),
        index=False
    )

    pd.DataFrame(batch_logs).to_csv(
        OUT["oas_spreads_monthly_bond"].with_name("oas_batch_logs.csv"),
        index=False
    )

    logger.info(f"Guardado OAS en: {OUT['oas_spreads_monthly_bond']}")
    logger.info(f"Filas OAS: {len(oas_all):,}")
    logger.info(f"Bond RICs con OAS: {oas_all['bond_ric'].nunique():,} / {len(bond_rics):,}")
    logger.info(f"Bond RICs sin OAS o fallidos: {len(set(failed_rics)):,}")

2026-03-24 20:41:50 | INFO | Bond RICs para OAS: 9,448
2026-03-24 20:41:50,818 P[19164] [MainThread 20064] Bond RICs para OAS: 9,448

============================================================
BATCH 1/378 | tamaño = 25
============================================================
Intento 1 | filas: 1937 | errores: 0
Tiempo batch: 0.77 s

============================================================
BATCH 2/378 | tamaño = 25
============================================================
Intento 1 | filas: 1828 | errores: 0
Tiempo batch: 0.73 s

============================================================
BATCH 3/378 | tamaño = 25
============================================================
Intento 1 | filas: 2558 | errores: 0
Tiempo batch: 0.81 s

============================================================
BATCH 4/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 128.20 s
⚠️ Errores en batch: 50

============================================================
BATCH 5/378 | tamaño = 25
============================================================
Intento 1 | filas: 1200 | errores: 0
Tiempo batch: 0.73 s

============================================================
BATCH 6/378 | tamaño = 25
============================================================
Intento 1 | filas: 1088 | errores: 0
Tiempo batch: 0.75 s

============================================================
BATCH 7/378 | tamaño = 25
============================================================
Intento 1 | filas: 636 | errores: 0
Tiempo batch: 0.71 s

============================================================
BATCH 8/378 | tamaño = 25
============================================================
Intento 1 | filas: 387 | errores: 0
Tiempo batch: 0.68 s

============================================================
BATCH 9/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 121.20 s
⚠️ Errores en batch: 50

============================================================
BATCH 10/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 128.14 s
⚠️ Errores en batch: 50

>>> PROGRESO: 250/9,448 bonos (2.65%)

2026-03-24 20:48:42 | INFO | OAS progreso: batch 10 / 378 | bonos aprox. 250 / 9,448
2026-03-24 20:48:42,046 P[19164] [MainThread 20064] OAS progreso: batch 10 / 378 | bonos aprox. 250 / 9,448

============================================================
BATCH 11/378 | tamaño = 25
============================================================
Intento 1 | filas: 1077 | errores: 0
Tiempo batch: 0.73 s

============================================================
BATCH 12/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 128.20 s
⚠️ Errores en batch: 50

============================================================
BATCH 13/378 | tamaño = 25
============================================================
Intento 1 | filas: 203 | errores: 0
Tiempo batch: 0.68 s

============================================================
BATCH 14/378 | tamaño = 25
============================================================
Intento 1 | filas: 327 | errores: 0
Tiempo batch: 0.82 s

============================================================
BATCH 15/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 128.17 s
⚠️ Errores en batch: 50

============================================================
BATCH 16/378 | tamaño = 25
============================================================
Intento 1 | filas: 706 | errores: 0
Tiempo batch: 7.80 s

============================================================
BATCH 17/378 | tamaño = 25
============================================================
Intento 1 | filas: 728 | errores: 0
Tiempo batch: 1.14 s

============================================================
BATCH 18/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 121.28 s
⚠️ Errores en batch: 50

============================================================
BATCH 19/378 | tamaño = 25
============================================================
Intento 1 | filas: 267 | errores: 0
Tiempo batch: 0.95 s

============================================================
BATCH 20/378 | tamaño = 25
============================================================
Intento 1 | filas: 638 | errores: 0
Tiempo batch: 1.83 s

>>> PROGRESO: 500/9,448 bonos (5.29%)

2026-03-24 20:55:43 | INFO | OAS progreso: batch 20 / 378 | bonos aprox. 500 / 9,448
2026-03-24 20:55:43,648 P[19164] [MainThread 20064] OAS progreso: batch 20 / 378 | bonos aprox. 500 / 9,448

============================================================
BATCH 21/378 | tamaño = 25
============================================================
Intento 1 | filas: 475 | errores: 0
Tiempo batch: 1.05 s

============================================================
BATCH 22/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 128.20 s
⚠️ Errores en batch: 50

============================================================
BATCH 23/378 | tamaño = 25
============================================================
Intento 1 | filas: 1376 | errores: 4
Tiempo batch: 1.95 s
⚠️ Errores en batch: 4

============================================================
BATCH 24/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 128.85 s
⚠️ Errores en batch: 50

============================================================
BATCH 25/378 | tamaño = 25
============================================================
Intento 1 | filas: 1160 | errores: 2
Tiempo batch: 1.38 s
⚠️ Errores en batch: 2

============================================================
BATCH 26/378 | tamaño = 25
============================================================
Intento 1 | filas: 1355 | errores: 4
Tiempo batch: 1.60 s
⚠️ Errores en batch: 4

============================================================
BATCH 27/378 | tamaño = 25
============================================================
Intento 1 | filas: 985 | errores: 2
Tiempo batch: 1.00 s
⚠️ Errores en batch: 2

============================================================
BATCH 28/378 | tamaño = 25
============================================================
Intento 1 | filas: 1396 | errores: 0
Tiempo batch: 1.43 s

============================================================
BATCH 29/378 | tamaño = 25
============================================================
Intento 1 | filas: 665 | errores: 0
Tiempo batch: 1.15 s

============================================================
BATCH 30/378 | tamaño = 25
============================================================
Intento 1 | filas: 1196 | errores: 0
Tiempo batch: 1.47 s

>>> PROGRESO: 750/9,448 bonos (7.94%)

2026-03-24 21:00:41 | INFO | OAS progreso: batch 30 / 378 | bonos aprox. 750 / 9,448
2026-03-24 21:00:41,726 P[19164] [MainThread 20064] OAS progreso: batch 30 / 378 | bonos aprox. 750 / 9,448

============================================================
BATCH 31/378 | tamaño = 25
============================================================
Intento 1 | filas: 872 | errores: 0
Tiempo batch: 1.20 s

============================================================
BATCH 32/378 | tamaño = 25
============================================================
Intento 1 | filas: 547 | errores: 0
Tiempo batch: 1.54 s

============================================================
BATCH 33/378 | tamaño = 25
============================================================
Intento 1 | filas: 1046 | errores: 0
Tiempo batch: 1.13 s

============================================================
BATCH 34/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 128.17 s
⚠️ Errores en batch: 50

============================================================
BATCH 35/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 128.19 s
⚠️ Errores en batch: 50

============================================================
BATCH 36/378 | tamaño = 25
============================================================
Intento 1 | filas: 566 | errores: 0
Tiempo batch: 2.41 s

============================================================
BATCH 37/378 | tamaño = 25
============================================================
Intento 1 | filas: 797 | errores: 0
Tiempo batch: 2.45 s

============================================================
BATCH 38/378 | tamaño = 25
============================================================
Intento 1 | filas: 868 | errores: 0
Tiempo batch: 2.70 s

============================================================
BATCH 39/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 125.01 s
⚠️ Errores en batch: 50

============================================================
BATCH 40/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 128.12 s
⚠️ Errores en batch: 50

>>> PROGRESO: 1,000/9,448 bonos (10.58%)

2026-03-24 21:09:52 | INFO | OAS progreso: batch 40 / 378 | bonos aprox. 1,000 / 9,448
2026-03-24 21:09:52,654 P[19164] [MainThread 20064] OAS progreso: batch 40 / 378 | bonos aprox. 1,000 / 9,448

============================================================
BATCH 41/378 | tamaño = 25
============================================================
Intento 1 | filas: 746 | errores: 0
Tiempo batch: 2.64 s

============================================================
BATCH 42/378 | tamaño = 25
============================================================
Intento 1 | filas: 397 | errores: 0
Tiempo batch: 2.42 s

============================================================
BATCH 43/378 | tamaño = 25
============================================================
Intento 1 | filas: 659 | errores: 0
Tiempo batch: 2.45 s

============================================================
BATCH 44/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 124.36 s
⚠️ Errores en batch: 50

============================================================
BATCH 45/378 | tamaño = 25
============================================================
Intento 1 | filas: 1148 | errores: 0
Tiempo batch: 6.75 s

============================================================
BATCH 46/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 133.05 s
⚠️ Errores en batch: 50

============================================================
BATCH 47/378 | tamaño = 25
============================================================
Intento 1 | filas: 1154 | errores: 0
Tiempo batch: 2.33 s

============================================================
BATCH 48/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 128.36 s
⚠️ Errores en batch: 50

============================================================
BATCH 49/378 | tamaño = 25
============================================================
Intento 1 | filas: 1153 | errores: 0
Tiempo batch: 2.78 s

============================================================
BATCH 50/378 | tamaño = 25
============================================================
Intento 1 | filas: 2194 | errores: 0
Tiempo batch: 2.73 s

>>> PROGRESO: 1,250/9,448 bonos (13.23%)

2026-03-24 21:17:10 | INFO | OAS progreso: batch 50 / 378 | bonos aprox. 1,250 / 9,448
2026-03-24 21:17:10,521 P[19164] [MainThread 20064] OAS progreso: batch 50 / 378 | bonos aprox. 1,250 / 9,448

============================================================
BATCH 51/378 | tamaño = 25
============================================================
Intento 1 | filas: 915 | errores: 0
Tiempo batch: 6.07 s

============================================================
BATCH 52/378 | tamaño = 25
============================================================
Intento 1 | filas: 694 | errores: 0
Tiempo batch: 2.49 s

============================================================
BATCH 53/378 | tamaño = 25
============================================================
Intento 1 | filas: 396 | errores: 0
Tiempo batch: 24.50 s

============================================================
BATCH 54/378 | tamaño = 25
============================================================
Intento 1 | filas: 635 | errores: 0
Tiempo batch: 2.60 s

============================================================
BATCH 55/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 132.77 s
⚠️ Errores en batch: 50

============================================================
BATCH 56/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 128.94 s
⚠️ Errores en batch: 50

============================================================
BATCH 57/378 | tamaño = 25
============================================================
Intento 1 | filas: 280 | errores: 2
Tiempo batch: 2.27 s
⚠️ Errores en batch: 2

============================================================
BATCH 58/378 | tamaño = 25
============================================================
Intento 1 | filas: 1411 | errores: 0
Tiempo batch: 2.71 s

============================================================
BATCH 59/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 128.16 s
⚠️ Errores en batch: 50

============================================================
BATCH 60/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 129.54 s
⚠️ Errores en batch: 50

>>> PROGRESO: 1,500/9,448 bonos (15.88%)

2026-03-24 21:27:00 | INFO | OAS progreso: batch 60 / 378 | bonos aprox. 1,500 / 9,448
2026-03-24 21:27:00,587 P[19164] [MainThread 20064] OAS progreso: batch 60 / 378 | bonos aprox. 1,500 / 9,448

============================================================
BATCH 61/378 | tamaño = 25
============================================================
Intento 1 | filas: 2076 | errores: 0
Tiempo batch: 2.90 s

============================================================
BATCH 62/378 | tamaño = 25
============================================================
Intento 1 | filas: 493 | errores: 0
Tiempo batch: 2.57 s

============================================================
BATCH 63/378 | tamaño = 25
============================================================
Intento 1 | filas: 1467 | errores: 0
Tiempo batch: 2.60 s

============================================================
BATCH 64/378 | tamaño = 25
============================================================
Intento 1 | filas: 1342 | errores: 0
Tiempo batch: 3.11 s

============================================================
BATCH 65/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 128.19 s
⚠️ Errores en batch: 50

============================================================
BATCH 66/378 | tamaño = 25
============================================================
Intento 1 | filas: 851 | errores: 0
Tiempo batch: 2.65 s

============================================================
BATCH 67/378 | tamaño = 25
============================================================
Intento 1 | filas: 1335 | errores: 0
Tiempo batch: 2.62 s

============================================================
BATCH 68/378 | tamaño = 25
============================================================
Intento 1 | filas: 509 | errores: 0
Tiempo batch: 2.59 s

============================================================
BATCH 69/378 | tamaño = 25
============================================================
Intento 1 | filas: 892 | errores: 0
Tiempo batch: 2.23 s

============================================================
BATCH 70/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 128.12 s
⚠️ Errores en batch: 50

>>> PROGRESO: 1,750/9,448 bonos (18.52%)

2026-03-24 21:32:08 | INFO | OAS progreso: batch 70 / 378 | bonos aprox. 1,750 / 9,448
2026-03-24 21:32:08,174 P[19164] [MainThread 20064] OAS progreso: batch 70 / 378 | bonos aprox. 1,750 / 9,448

============================================================
BATCH 71/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 122.25 s
⚠️ Errores en batch: 50

============================================================
BATCH 72/378 | tamaño = 25
============================================================
Intento 1 | filas: 999 | errores: 0
Tiempo batch: 2.00 s

============================================================
BATCH 73/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 122.04 s
⚠️ Errores en batch: 50

============================================================
BATCH 74/378 | tamaño = 25
============================================================
Intento 1 | filas: 464 | errores: 4
Tiempo batch: 2.85 s
⚠️ Errores en batch: 4

============================================================
BATCH 75/378 | tamaño = 25
============================================================
Intento 1 | filas: 718 | errores: 0
Tiempo batch: 2.49 s

============================================================
BATCH 76/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 129.46 s
⚠️ Errores en batch: 50

============================================================
BATCH 77/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 133.34 s
⚠️ Errores en batch: 50

============================================================
BATCH 78/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 128.31 s
⚠️ Errores en batch: 50

============================================================
BATCH 79/378 | tamaño = 25
============================================================
Intento 1 | filas: 941 | errores: 0
Tiempo batch: 2.28 s

============================================================
BATCH 80/378 | tamaño = 25
============================================================
Intento 1 | filas: 1312 | errores: 0
Tiempo batch: 7.61 s

>>> PROGRESO: 2,000/9,448 bonos (21.17%)

2026-03-24 21:43:30 | INFO | OAS progreso: batch 80 / 378 | bonos aprox. 2,000 / 9,448
2026-03-24 21:43:30,830 P[19164] [MainThread 20064] OAS progreso: batch 80 / 378 | bonos aprox. 2,000 / 9,448

============================================================
BATCH 81/378 | tamaño = 25
============================================================
Intento 1 | filas: 1003 | errores: 0
Tiempo batch: 2.47 s

============================================================
BATCH 82/378 | tamaño = 25
============================================================
Intento 1 | filas: 452 | errores: 2
Tiempo batch: 2.68 s
⚠️ Errores en batch: 2

============================================================
BATCH 83/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 128.19 s
⚠️ Errores en batch: 50

============================================================
BATCH 84/378 | tamaño = 25
============================================================
Intento 1 | filas: 755 | errores: 0
Tiempo batch: 2.44 s

============================================================
BATCH 85/378 | tamaño = 25
============================================================
Intento 1 | filas: 744 | errores: 0
Tiempo batch: 6.70 s

============================================================
BATCH 86/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 125.29 s
⚠️ Errores en batch: 50

============================================================
BATCH 87/378 | tamaño = 25
============================================================
Intento 1 | filas: 660 | errores: 0
Tiempo batch: 35.04 s

============================================================
BATCH 88/378 | tamaño = 25
============================================================
Intento 1 | filas: 1982 | errores: 0
Tiempo batch: 19.90 s

============================================================
BATCH 89/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 133.06 s
⚠️ Errores en batch: 50

============================================================
BATCH 90/378 | tamaño = 25
============================================================
Intento 1 | filas: 547 | errores: 0
Tiempo batch: 2.50 s

>>> PROGRESO: 2,250/9,448 bonos (23.81%)

2026-03-24 21:51:39 | INFO | OAS progreso: batch 90 / 378 | bonos aprox. 2,250 / 9,448
2026-03-24 21:51:39,125 P[19164] [MainThread 20064] OAS progreso: batch 90 / 378 | bonos aprox. 2,250 / 9,448

============================================================
BATCH 91/378 | tamaño = 25
============================================================
Intento 1 | filas: 72 | errores: 44
Tiempo batch: 125.00 s
⚠️ Errores en batch: 44

============================================================
BATCH 92/378 | tamaño = 25
============================================================
Intento 1 | filas: 368 | errores: 0
Tiempo batch: 2.41 s

============================================================
BATCH 93/378 | tamaño = 25
============================================================
Intento 1 | filas: 143 | errores: 0
Tiempo batch: 2.36 s

============================================================
BATCH 94/378 | tamaño = 25
============================================================
Intento 1 | filas: 945 | errores: 0
Tiempo batch: 2.36 s

============================================================
BATCH 95/378 | tamaño = 25
============================================================
Intento 1 | filas: 177 | errores: 30
Tiempo batch: 94.23 s
⚠️ Errores en batch: 30

============================================================
BATCH 96/378 | tamaño = 25
============================================================
Intento 1 | filas: 1068 | errores: 0
Tiempo batch: 2.27 s

============================================================
BATCH 97/378 | tamaño = 25
============================================================
Intento 1 | filas: 1152 | errores: 0
Tiempo batch: 2.47 s

============================================================
BATCH 98/378 | tamaño = 25
============================================================
Intento 1 | filas: 1420 | errores: 0
Tiempo batch: 19.69 s

============================================================
BATCH 99/378 | tamaño = 25
============================================================
Intento 1 | filas: 1965 | errores: 0
Tiempo batch: 2.72 s

============================================================
BATCH 100/378 | tamaño = 25
============================================================
Intento 1 | filas: 1176 | errores: 0
Tiempo batch: 2.76 s

>>> PROGRESO: 2,500/9,448 bonos (26.46%)

2026-03-24 21:56:25 | INFO | OAS progreso: batch 100 / 378 | bonos aprox. 2,500 / 9,448
2026-03-24 21:56:25,416 P[19164] [MainThread 20064] OAS progreso: batch 100 / 378 | bonos aprox. 2,500 / 9,448

============================================================
BATCH 101/378 | tamaño = 25
============================================================
Intento 1 | filas: 1898 | errores: 0
Tiempo batch: 2.34 s

============================================================
BATCH 102/378 | tamaño = 25
============================================================
Intento 1 | filas: 1501 | errores: 0
Tiempo batch: 2.48 s

============================================================
BATCH 103/378 | tamaño = 25
============================================================
Intento 1 | filas: 2108 | errores: 0
Tiempo batch: 7.95 s

============================================================
BATCH 104/378 | tamaño = 25
============================================================
Intento 1 | filas: 1334 | errores: 0
Tiempo batch: 8.74 s

============================================================
BATCH 105/378 | tamaño = 25
============================================================
Intento 1 | filas: 1164 | errores: 0
Tiempo batch: 2.40 s

============================================================
BATCH 106/378 | tamaño = 25
============================================================
Intento 1 | filas: 1035 | errores: 0
Tiempo batch: 2.43 s

============================================================
BATCH 107/378 | tamaño = 25
============================================================
Intento 1 | filas: 1029 | errores: 0
Tiempo batch: 2.42 s

============================================================
BATCH 108/378 | tamaño = 25
============================================================
Intento 1 | filas: 499 | errores: 0
Tiempo batch: 2.31 s

============================================================
BATCH 109/378 | tamaño = 25
============================================================
Intento 1 | filas: 735 | errores: 2
Tiempo batch: 2.29 s
⚠️ Errores en batch: 2

============================================================
BATCH 110/378 | tamaño = 25
============================================================
Intento 1 | filas: 748 | errores: 2
Tiempo batch: 2.32 s
⚠️ Errores en batch: 2

>>> PROGRESO: 2,750/9,448 bonos (29.11%)

2026-03-24 21:57:31 | INFO | OAS progreso: batch 110 / 378 | bonos aprox. 2,750 / 9,448
2026-03-24 21:57:31,114 P[19164] [MainThread 20064] OAS progreso: batch 110 / 378 | bonos aprox. 2,750 / 9,448

============================================================
BATCH 111/378 | tamaño = 25
============================================================
Intento 1 | filas: 436 | errores: 0
Tiempo batch: 2.13 s

============================================================
BATCH 112/378 | tamaño = 25
============================================================
Intento 1 | filas: 536 | errores: 0
Tiempo batch: 3.11 s

============================================================
BATCH 113/378 | tamaño = 25
============================================================
Intento 1 | filas: 616 | errores: 0
Tiempo batch: 2.50 s

============================================================
BATCH 114/378 | tamaño = 25
============================================================
Intento 1 | filas: 463 | errores: 0
Tiempo batch: 3.24 s

============================================================
BATCH 115/378 | tamaño = 25
============================================================
Intento 1 | filas: 431 | errores: 2
Tiempo batch: 2.81 s
⚠️ Errores en batch: 2

============================================================
BATCH 116/378 | tamaño = 25
============================================================
Intento 1 | filas: 285 | errores: 0
Tiempo batch: 2.23 s

============================================================
BATCH 117/378 | tamaño = 25
============================================================
Intento 1 | filas: 654 | errores: 0
Tiempo batch: 2.73 s

============================================================
BATCH 118/378 | tamaño = 25
============================================================
Intento 1 | filas: 393 | errores: 0
Tiempo batch: 2.27 s

============================================================
BATCH 119/378 | tamaño = 25
============================================================
Intento 1 | filas: 488 | errores: 0
Tiempo batch: 2.65 s

============================================================
BATCH 120/378 | tamaño = 25
============================================================
Intento 1 | filas: 554 | errores: 0
Tiempo batch: 3.25 s

>>> PROGRESO: 3,000/9,448 bonos (31.75%)

2026-03-24 21:58:28 | INFO | OAS progreso: batch 120 / 378 | bonos aprox. 3,000 / 9,448
2026-03-24 21:58:28,054 P[19164] [MainThread 20064] OAS progreso: batch 120 / 378 | bonos aprox. 3,000 / 9,448

============================================================
BATCH 121/378 | tamaño = 25
============================================================
Intento 1 | filas: 146 | errores: 38
Tiempo batch: 95.49 s
⚠️ Errores en batch: 38

============================================================
BATCH 122/378 | tamaño = 25
============================================================
Intento 1 | filas: 534 | errores: 0
Tiempo batch: 19.51 s

============================================================
BATCH 123/378 | tamaño = 25
============================================================
Intento 1 | filas: 277 | errores: 28
Tiempo batch: 95.43 s
⚠️ Errores en batch: 28

============================================================
BATCH 124/378 | tamaño = 25
============================================================
Intento 1 | filas: 270 | errores: 0
Tiempo batch: 24.57 s

============================================================
BATCH 125/378 | tamaño = 25
============================================================
Intento 1 | filas: 270 | errores: 0
Tiempo batch: 2.32 s

============================================================
BATCH 126/378 | tamaño = 25
============================================================
Intento 1 | filas: 350 | errores: 0
Tiempo batch: 1.89 s

============================================================
BATCH 127/378 | tamaño = 25
============================================================
Intento 1 | filas: 133 | errores: 46
Tiempo batch: 133.96 s
⚠️ Errores en batch: 46

============================================================
BATCH 128/378 | tamaño = 25
============================================================
Intento 1 | filas: 481 | errores: 0
Tiempo batch: 2.63 s

============================================================
BATCH 129/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 139.67 s
⚠️ Errores en batch: 50

============================================================
BATCH 130/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 128.07 s
⚠️ Errores en batch: 50

>>> PROGRESO: 3,250/9,448 bonos (34.40%)

2026-03-24 22:09:41 | INFO | OAS progreso: batch 130 / 378 | bonos aprox. 3,250 / 9,448
2026-03-24 22:09:41,605 P[19164] [MainThread 20064] OAS progreso: batch 130 / 378 | bonos aprox. 3,250 / 9,448

============================================================
BATCH 131/378 | tamaño = 25
============================================================
Intento 1 | filas: 188 | errores: 2
Tiempo batch: 19.50 s
⚠️ Errores en batch: 2

============================================================
BATCH 132/378 | tamaño = 25
============================================================
Intento 1 | filas: 639 | errores: 2
Tiempo batch: 2.43 s
⚠️ Errores en batch: 2

============================================================
BATCH 133/378 | tamaño = 25
============================================================
Intento 1 | filas: 354 | errores: 0
Tiempo batch: 3.34 s

============================================================
BATCH 134/378 | tamaño = 25
============================================================
Intento 1 | filas: 946 | errores: 0
Tiempo batch: 7.74 s

============================================================
BATCH 135/378 | tamaño = 25
============================================================
Intento 1 | filas: 366 | errores: 0
Tiempo batch: 2.22 s

============================================================
BATCH 136/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 128.33 s
⚠️ Errores en batch: 50

============================================================
BATCH 137/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 128.87 s
⚠️ Errores en batch: 50

============================================================
BATCH 138/378 | tamaño = 25
============================================================
Intento 1 | filas: 335 | errores: 0
Tiempo batch: 3.49 s

============================================================
BATCH 139/378 | tamaño = 25
============================================================
Intento 1 | filas: 318 | errores: 0
Tiempo batch: 2.03 s

============================================================
BATCH 140/378 | tamaño = 25
============================================================
Intento 1 | filas: 317 | errores: 0
Tiempo batch: 5.00 s

>>> PROGRESO: 3,500/9,448 bonos (37.04%)

2026-03-24 22:15:14 | INFO | OAS progreso: batch 140 / 378 | bonos aprox. 3,500 / 9,448
2026-03-24 22:15:14,582 P[19164] [MainThread 20064] OAS progreso: batch 140 / 378 | bonos aprox. 3,500 / 9,448

============================================================
BATCH 141/378 | tamaño = 25
============================================================
Intento 1 | filas: 332 | errores: 0
Tiempo batch: 2.14 s

============================================================
BATCH 142/378 | tamaño = 25
============================================================
Intento 1 | filas: 202 | errores: 0
Tiempo batch: 2.99 s

============================================================
BATCH 143/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 128.33 s
⚠️ Errores en batch: 50

============================================================
BATCH 144/378 | tamaño = 25
============================================================
Intento 1 | filas: 672 | errores: 0
Tiempo batch: 2.63 s

============================================================
BATCH 145/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 122.03 s
⚠️ Errores en batch: 50

============================================================
BATCH 146/378 | tamaño = 25
============================================================
Intento 1 | filas: 359 | errores: 0
Tiempo batch: 5.23 s

============================================================
BATCH 147/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 128.26 s
⚠️ Errores en batch: 50

============================================================
BATCH 148/378 | tamaño = 25
============================================================
Intento 1 | filas: 283 | errores: 0
Tiempo batch: 4.57 s

============================================================
BATCH 149/378 | tamaño = 25
============================================================
Intento 1 | filas: 63 | errores: 0
Tiempo batch: 1.82 s

============================================================
BATCH 150/378 | tamaño = 25
============================================================
Intento 1 | filas: 26 | errores: 2
Tiempo batch: 5.13 s
⚠️ Errores en batch: 2

>>> PROGRESO: 3,750/9,448 bonos (39.69%)

2026-03-24 22:22:27 | INFO | OAS progreso: batch 150 / 378 | bonos aprox. 3,750 / 9,448
2026-03-24 22:22:27,730 P[19164] [MainThread 20064] OAS progreso: batch 150 / 378 | bonos aprox. 3,750 / 9,448

============================================================
BATCH 151/378 | tamaño = 25
============================================================
Intento 1 | filas: 266 | errores: 0
Tiempo batch: 2.32 s

============================================================
BATCH 152/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 125.77 s
⚠️ Errores en batch: 50

============================================================
BATCH 153/378 | tamaño = 25
============================================================
Intento 1 | filas: 257 | errores: 2
Tiempo batch: 3.64 s
⚠️ Errores en batch: 2

============================================================
BATCH 154/378 | tamaño = 25
============================================================
Intento 1 | filas: 1299 | errores: 2
Tiempo batch: 2.43 s
⚠️ Errores en batch: 2

============================================================
BATCH 155/378 | tamaño = 25
============================================================
Intento 1 | filas: 682 | errores: 4
Tiempo batch: 1.89 s
⚠️ Errores en batch: 4

============================================================
BATCH 156/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 122.01 s
⚠️ Errores en batch: 50

============================================================
BATCH 157/378 | tamaño = 25
============================================================
Intento 1 | filas: 560 | errores: 0
Tiempo batch: 5.57 s

============================================================
BATCH 158/378 | tamaño = 25
============================================================
Intento 1 | filas: 509 | errores: 0
Tiempo batch: 3.29 s

============================================================
BATCH 159/378 | tamaño = 25
============================================================
Intento 1 | filas: 491 | errores: 2
Tiempo batch: 4.37 s
⚠️ Errores en batch: 2

============================================================
BATCH 160/378 | tamaño = 25
============================================================
Intento 1 | filas: 768 | errores: 0
Tiempo batch: 2.18 s

>>> PROGRESO: 4,000/9,448 bonos (42.34%)

2026-03-24 22:27:31 | INFO | OAS progreso: batch 160 / 378 | bonos aprox. 4,000 / 9,448
2026-03-24 22:27:31,215 P[19164] [MainThread 20064] OAS progreso: batch 160 / 378 | bonos aprox. 4,000 / 9,448

============================================================
BATCH 161/378 | tamaño = 25
============================================================
Intento 1 | filas: 1345 | errores: 0
Tiempo batch: 5.13 s

============================================================
BATCH 162/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 128.51 s
⚠️ Errores en batch: 50

============================================================
BATCH 163/378 | tamaño = 25
============================================================
Intento 1 | filas: 948 | errores: 0
Tiempo batch: 2.54 s

============================================================
BATCH 164/378 | tamaño = 25
============================================================
Intento 1 | filas: 998 | errores: 0
Tiempo batch: 3.30 s

============================================================
BATCH 165/378 | tamaño = 25
============================================================
Intento 1 | filas: 1326 | errores: 0
Tiempo batch: 2.77 s

============================================================
BATCH 166/378 | tamaño = 25
============================================================
Intento 1 | filas: 1319 | errores: 0
Tiempo batch: 5.72 s

============================================================
BATCH 167/378 | tamaño = 25
============================================================
Intento 1 | filas: 2102 | errores: 0
Tiempo batch: 2.58 s

============================================================
BATCH 168/378 | tamaño = 25
============================================================
Intento 1 | filas: 717 | errores: 0
Tiempo batch: 2.54 s

============================================================
BATCH 169/378 | tamaño = 25
============================================================
Intento 1 | filas: 492 | errores: 0
Tiempo batch: 2.37 s

============================================================
BATCH 170/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 128.19 s
⚠️ Errores en batch: 50

>>> PROGRESO: 4,250/9,448 bonos (44.98%)

2026-03-24 22:32:44 | INFO | OAS progreso: batch 170 / 378 | bonos aprox. 4,250 / 9,448
2026-03-24 22:32:44,880 P[19164] [MainThread 20064] OAS progreso: batch 170 / 378 | bonos aprox. 4,250 / 9,448

============================================================
BATCH 171/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 122.68 s
⚠️ Errores en batch: 50

============================================================
BATCH 172/378 | tamaño = 25
============================================================
Intento 1 | filas: 1158 | errores: 0
Tiempo batch: 2.58 s

============================================================
BATCH 173/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 129.28 s
⚠️ Errores en batch: 50

============================================================
BATCH 174/378 | tamaño = 25
============================================================
Intento 1 | filas: 1492 | errores: 0
Tiempo batch: 2.42 s

============================================================
BATCH 175/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 121.70 s
⚠️ Errores en batch: 50

============================================================
BATCH 176/378 | tamaño = 25
============================================================
Intento 1 | filas: 3237 | errores: 0
Tiempo batch: 5.53 s

============================================================
BATCH 177/378 | tamaño = 25
============================================================
Intento 1 | filas: 3111 | errores: 0
Tiempo batch: 5.94 s

============================================================
BATCH 178/378 | tamaño = 25
============================================================
Intento 1 | filas: 3300 | errores: 0
Tiempo batch: 3.05 s

============================================================
BATCH 179/378 | tamaño = 25
============================================================
Intento 1 | filas: 3296 | errores: 0
Tiempo batch: 3.05 s

============================================================
BATCH 180/378 | tamaño = 25
============================================================
Intento 1 | filas: 3029 | errores: 0
Tiempo batch: 3.10 s

>>> PROGRESO: 4,500/9,448 bonos (47.63%)

2026-03-24 22:39:54 | INFO | OAS progreso: batch 180 / 378 | bonos aprox. 4,500 / 9,448
2026-03-24 22:39:54,219 P[19164] [MainThread 20064] OAS progreso: batch 180 / 378 | bonos aprox. 4,500 / 9,448

============================================================
BATCH 181/378 | tamaño = 25
============================================================
Intento 1 | filas: 1401 | errores: 0
Tiempo batch: 2.46 s

============================================================
BATCH 182/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 127.96 s
⚠️ Errores en batch: 50

============================================================
BATCH 183/378 | tamaño = 25
============================================================
Intento 1 | filas: 712 | errores: 0
Tiempo batch: 2.58 s

============================================================
BATCH 184/378 | tamaño = 25
============================================================

2026-03-24 22:44:19,074 P[19164] [MainThread 20064] Eikon Proxy not running or cannot be reached. Please read the documentation on troubleshooting

Intento 1 falló: Error code 401 | Eikon Proxy not running or cannot be reached. Please read the documentation on troubleshooting
Intento 2 | filas: 25 | errores: 50
Tiempo batch: 257.40 s
⚠️ Errores en batch: 50

============================================================
BATCH 185/378 | tamaño = 25
============================================================
Intento 1 | filas: 1499 | errores: 0
Tiempo batch: 2.73 s

============================================================
BATCH 186/378 | tamaño = 25
============================================================
Intento 1 | filas: 1777 | errores: 0
Tiempo batch: 2.55 s

============================================================
BATCH 187/378 | tamaño = 25
============================================================
Intento 1 | filas: 961 | errores: 0
Tiempo batch: 3.90 s

============================================================
BATCH 188/378 | tamaño = 25
============================================================
Intento 1 | filas: 569 | errores: 0
Tiempo batch: 2.16 s

============================================================
BATCH 189/378 | tamaño = 25
============================================================
Intento 1 | filas: 451 | errores: 4
Tiempo batch: 2.12 s
⚠️ Errores en batch: 4

============================================================
BATCH 190/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 129.73 s
⚠️ Errores en batch: 50

>>> PROGRESO: 4,750/9,448 bonos (50.28%)

2026-03-24 22:49:17 | INFO | OAS progreso: batch 190 / 378 | bonos aprox. 4,750 / 9,448
2026-03-24 22:49:17,828 P[19164] [MainThread 20064] OAS progreso: batch 190 / 378 | bonos aprox. 4,750 / 9,448

============================================================
BATCH 191/378 | tamaño = 25
============================================================
Intento 1 | filas: 442 | errores: 0
Tiempo batch: 8.46 s

============================================================
BATCH 192/378 | tamaño = 25
============================================================
Intento 1 | filas: 294 | errores: 0
Tiempo batch: 4.74 s

============================================================
BATCH 193/378 | tamaño = 25
============================================================
Intento 1 | filas: 377 | errores: 0
Tiempo batch: 2.63 s

============================================================
BATCH 194/378 | tamaño = 25
============================================================
Intento 1 | filas: 512 | errores: 0
Tiempo batch: 5.02 s

============================================================
BATCH 195/378 | tamaño = 25
============================================================
Intento 1 | filas: 247 | errores: 0
Tiempo batch: 2.27 s

============================================================
BATCH 196/378 | tamaño = 25
============================================================
Intento 1 | filas: 443 | errores: 0
Tiempo batch: 2.56 s

============================================================
BATCH 197/378 | tamaño = 25
============================================================
Intento 1 | filas: 411 | errores: 2
Tiempo batch: 2.52 s
⚠️ Errores en batch: 2

============================================================
BATCH 198/378 | tamaño = 25
============================================================
Intento 1 | filas: 734 | errores: 0
Tiempo batch: 2.20 s

============================================================
BATCH 199/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 124.52 s
⚠️ Errores en batch: 50

============================================================
BATCH 200/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 131.22 s
⚠️ Errores en batch: 50

>>> PROGRESO: 5,000/9,448 bonos (52.92%)

2026-03-24 22:54:33 | INFO | OAS progreso: batch 200 / 378 | bonos aprox. 5,000 / 9,448
2026-03-24 22:54:33,961 P[19164] [MainThread 20064] OAS progreso: batch 200 / 378 | bonos aprox. 5,000 / 9,448

============================================================
BATCH 201/378 | tamaño = 25
============================================================
Intento 1 | filas: 273 | errores: 0
Tiempo batch: 2.62 s

============================================================
BATCH 202/378 | tamaño = 25
============================================================
Intento 1 | filas: 507 | errores: 0
Tiempo batch: 3.03 s

============================================================
BATCH 203/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 129.16 s
⚠️ Errores en batch: 50

============================================================
BATCH 204/378 | tamaño = 25
============================================================
Intento 1 | filas: 969 | errores: 0
Tiempo batch: 4.11 s

============================================================
BATCH 205/378 | tamaño = 25
============================================================
Intento 1 | filas: 1025 | errores: 0
Tiempo batch: 2.49 s

============================================================
BATCH 206/378 | tamaño = 25
============================================================
Intento 1 | filas: 1303 | errores: 0
Tiempo batch: 2.37 s

============================================================
BATCH 207/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 121.43 s
⚠️ Errores en batch: 50

============================================================
BATCH 208/378 | tamaño = 25
============================================================
Intento 1 | filas: 180 | errores: 0
Tiempo batch: 2.24 s

============================================================
BATCH 209/378 | tamaño = 25
============================================================
Intento 1 | filas: 230 | errores: 0
Tiempo batch: 5.33 s

============================================================
BATCH 210/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 128.41 s
⚠️ Errores en batch: 50

>>> PROGRESO: 5,250/9,448 bonos (55.57%)

2026-03-24 23:01:45 | INFO | OAS progreso: batch 210 / 378 | bonos aprox. 5,250 / 9,448
2026-03-24 23:01:45,151 P[19164] [MainThread 20064] OAS progreso: batch 210 / 378 | bonos aprox. 5,250 / 9,448

============================================================
BATCH 211/378 | tamaño = 25
============================================================
Intento 1 | filas: 102 | errores: 0
Tiempo batch: 2.68 s

============================================================
BATCH 212/378 | tamaño = 25
============================================================
Intento 1 | filas: 276 | errores: 0
Tiempo batch: 2.33 s

============================================================
BATCH 213/378 | tamaño = 25
============================================================
Intento 1 | filas: 709 | errores: 0
Tiempo batch: 2.08 s

============================================================
BATCH 214/378 | tamaño = 25
============================================================
Intento 1 | filas: 1792 | errores: 0
Tiempo batch: 2.86 s

============================================================
BATCH 215/378 | tamaño = 25
============================================================
Intento 1 | filas: 2226 | errores: 0
Tiempo batch: 2.59 s

============================================================
BATCH 216/378 | tamaño = 25
============================================================
Intento 1 | filas: 2099 | errores: 0
Tiempo batch: 2.83 s

============================================================
BATCH 217/378 | tamaño = 25
============================================================
Intento 1 | filas: 1529 | errores: 0
Tiempo batch: 2.39 s

============================================================
BATCH 218/378 | tamaño = 25
============================================================
Intento 1 | filas: 512 | errores: 0
Tiempo batch: 2.25 s

============================================================
BATCH 219/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 125.03 s
⚠️ Errores en batch: 50

============================================================
BATCH 220/378 | tamaño = 25
============================================================
Intento 1 | filas: 964 | errores: 0
Tiempo batch: 2.14 s

>>> PROGRESO: 5,500/9,448 bonos (58.21%)

2026-03-24 23:04:42 | INFO | OAS progreso: batch 220 / 378 | bonos aprox. 5,500 / 9,448
2026-03-24 23:04:42,319 P[19164] [MainThread 20064] OAS progreso: batch 220 / 378 | bonos aprox. 5,500 / 9,448

============================================================
BATCH 221/378 | tamaño = 25
============================================================
Intento 1 | filas: 1334 | errores: 0
Tiempo batch: 2.56 s

============================================================
BATCH 222/378 | tamaño = 25
============================================================
Intento 1 | filas: 883 | errores: 0
Tiempo batch: 2.29 s

============================================================
BATCH 223/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 124.99 s
⚠️ Errores en batch: 50

============================================================
BATCH 224/378 | tamaño = 25
============================================================
Intento 1 | filas: 1267 | errores: 0
Tiempo batch: 5.70 s

============================================================
BATCH 225/378 | tamaño = 25
============================================================
Intento 1 | filas: 1758 | errores: 0
Tiempo batch: 4.12 s

============================================================
BATCH 226/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 120.97 s
⚠️ Errores en batch: 50

============================================================
BATCH 227/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 121.21 s
⚠️ Errores en batch: 50

============================================================
BATCH 228/378 | tamaño = 25
============================================================
Intento 1 | filas: 1239 | errores: 0
Tiempo batch: 2.37 s

============================================================
BATCH 229/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 121.59 s
⚠️ Errores en batch: 50

============================================================
BATCH 230/378 | tamaño = 25
============================================================
Intento 1 | filas: 909 | errores: 0
Tiempo batch: 2.26 s

>>> PROGRESO: 5,750/9,448 bonos (60.86%)

2026-03-24 23:13:40 | INFO | OAS progreso: batch 230 / 378 | bonos aprox. 5,750 / 9,448
2026-03-24 23:13:40,385 P[19164] [MainThread 20064] OAS progreso: batch 230 / 378 | bonos aprox. 5,750 / 9,448

============================================================
BATCH 231/378 | tamaño = 25
============================================================
Intento 1 | filas: 285 | errores: 0
Tiempo batch: 3.59 s

============================================================
BATCH 232/378 | tamaño = 25
============================================================
Intento 1 | filas: 1701 | errores: 0
Tiempo batch: 3.36 s

============================================================
BATCH 233/378 | tamaño = 25
============================================================
Intento 1 | filas: 804 | errores: 0
Tiempo batch: 1.85 s

============================================================
BATCH 234/378 | tamaño = 25
============================================================
Intento 1 | filas: 330 | errores: 0
Tiempo batch: 3.86 s

============================================================
BATCH 235/378 | tamaño = 25
============================================================
Intento 1 | filas: 1662 | errores: 0
Tiempo batch: 2.53 s

============================================================
BATCH 236/378 | tamaño = 25
============================================================
Intento 1 | filas: 1052 | errores: 0
Tiempo batch: 4.56 s

============================================================
BATCH 237/378 | tamaño = 25
============================================================
Intento 1 | filas: 1884 | errores: 0
Tiempo batch: 2.09 s

============================================================
BATCH 238/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 125.18 s
⚠️ Errores en batch: 50

============================================================
BATCH 239/378 | tamaño = 25
============================================================
Intento 1 | filas: 1272 | errores: 0
Tiempo batch: 2.37 s

============================================================
BATCH 240/378 | tamaño = 25
============================================================
Intento 1 | filas: 1546 | errores: 0
Tiempo batch: 2.50 s

>>> PROGRESO: 6,000/9,448 bonos (63.51%)

2026-03-24 23:16:42 | INFO | OAS progreso: batch 240 / 378 | bonos aprox. 6,000 / 9,448
2026-03-24 23:16:42,300 P[19164] [MainThread 20064] OAS progreso: batch 240 / 378 | bonos aprox. 6,000 / 9,448

============================================================
BATCH 241/378 | tamaño = 25
============================================================
Intento 1 | filas: 1746 | errores: 0
Tiempo batch: 2.35 s

============================================================
BATCH 242/378 | tamaño = 25
============================================================
Intento 1 | filas: 1687 | errores: 0
Tiempo batch: 4.49 s

============================================================
BATCH 243/378 | tamaño = 25
============================================================
Intento 1 | filas: 1343 | errores: 0
Tiempo batch: 4.90 s

============================================================
BATCH 244/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 126.70 s
⚠️ Errores en batch: 50

============================================================
BATCH 245/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 121.40 s
⚠️ Errores en batch: 50

============================================================
BATCH 246/378 | tamaño = 25
============================================================
Intento 1 | filas: 1309 | errores: 0
Tiempo batch: 2.42 s

============================================================
BATCH 247/378 | tamaño = 25
============================================================
Intento 1 | filas: 1237 | errores: 0
Tiempo batch: 2.64 s

============================================================
BATCH 248/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 126.91 s
⚠️ Errores en batch: 50

============================================================
BATCH 249/378 | tamaño = 25
============================================================
Intento 1 | filas: 2402 | errores: 0
Tiempo batch: 2.91 s

============================================================
BATCH 250/378 | tamaño = 25
============================================================
Intento 1 | filas: 2334 | errores: 0
Tiempo batch: 2.79 s

>>> PROGRESO: 6,250/9,448 bonos (66.15%)

2026-03-24 23:23:49 | INFO | OAS progreso: batch 250 / 378 | bonos aprox. 6,250 / 9,448
2026-03-24 23:23:49,814 P[19164] [MainThread 20064] OAS progreso: batch 250 / 378 | bonos aprox. 6,250 / 9,448

============================================================
BATCH 251/378 | tamaño = 25
============================================================
Intento 1 | filas: 2143 | errores: 0
Tiempo batch: 5.87 s

============================================================
BATCH 252/378 | tamaño = 25
============================================================
Intento 1 | filas: 1552 | errores: 0
Tiempo batch: 2.65 s

============================================================
BATCH 253/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 124.93 s
⚠️ Errores en batch: 50

============================================================
BATCH 254/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 128.21 s
⚠️ Errores en batch: 50

============================================================
BATCH 255/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 130.13 s
⚠️ Errores en batch: 50

============================================================
BATCH 256/378 | tamaño = 25
============================================================
Intento 1 | filas: 2186 | errores: 0
Tiempo batch: 5.07 s

============================================================
BATCH 257/378 | tamaño = 25
============================================================
Intento 1 | filas: 1191 | errores: 0
Tiempo batch: 2.27 s

============================================================
BATCH 258/378 | tamaño = 25
============================================================
Intento 1 | filas: 1320 | errores: 0
Tiempo batch: 2.30 s

============================================================
BATCH 259/378 | tamaño = 25
============================================================
Intento 1 | filas: 1503 | errores: 0
Tiempo batch: 2.28 s

============================================================
BATCH 260/378 | tamaño = 25
============================================================
Intento 1 | filas: 1313 | errores: 0
Tiempo batch: 3.19 s

>>> PROGRESO: 6,500/9,448 bonos (68.80%)

2026-03-24 23:31:06 | INFO | OAS progreso: batch 260 / 378 | bonos aprox. 6,500 / 9,448
2026-03-24 23:31:06,721 P[19164] [MainThread 20064] OAS progreso: batch 260 / 378 | bonos aprox. 6,500 / 9,448

============================================================
BATCH 261/378 | tamaño = 25
============================================================
Intento 1 | filas: 1635 | errores: 0
Tiempo batch: 3.25 s

============================================================
BATCH 262/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 129.24 s
⚠️ Errores en batch: 50

============================================================
BATCH 263/378 | tamaño = 25
============================================================
Intento 1 | filas: 1047 | errores: 0
Tiempo batch: 4.34 s

============================================================
BATCH 264/378 | tamaño = 25
============================================================
Intento 1 | filas: 1266 | errores: 0
Tiempo batch: 5.75 s

============================================================
BATCH 265/378 | tamaño = 25
============================================================
Intento 1 | filas: 1324 | errores: 0
Tiempo batch: 2.17 s

============================================================
BATCH 266/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 130.18 s
⚠️ Errores en batch: 50

============================================================
BATCH 267/378 | tamaño = 25
============================================================
Intento 1 | filas: 547 | errores: 0
Tiempo batch: 2.85 s

============================================================
BATCH 268/378 | tamaño = 25
============================================================
Intento 1 | filas: 697 | errores: 0
Tiempo batch: 2.93 s

============================================================
BATCH 269/378 | tamaño = 25
============================================================
Intento 1 | filas: 1520 | errores: 0
Tiempo batch: 1.62 s

============================================================
BATCH 270/378 | tamaño = 25
============================================================
Intento 1 | filas: 1825 | errores: 0
Tiempo batch: 2.02 s

>>> PROGRESO: 6,750/9,448 bonos (71.44%)

2026-03-24 23:36:21 | INFO | OAS progreso: batch 270 / 378 | bonos aprox. 6,750 / 9,448
2026-03-24 23:36:21,075 P[19164] [MainThread 20064] OAS progreso: batch 270 / 378 | bonos aprox. 6,750 / 9,448

============================================================
BATCH 271/378 | tamaño = 25
============================================================
Intento 1 | filas: 2109 | errores: 0
Tiempo batch: 3.36 s

============================================================
BATCH 272/378 | tamaño = 25
============================================================
Intento 1 | filas: 790 | errores: 0
Tiempo batch: 2.19 s

============================================================
BATCH 273/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 133.89 s
⚠️ Errores en batch: 50

============================================================
BATCH 274/378 | tamaño = 25
============================================================
Intento 1 | filas: 1437 | errores: 0
Tiempo batch: 3.75 s

============================================================
BATCH 275/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 129.38 s
⚠️ Errores en batch: 50

============================================================
BATCH 276/378 | tamaño = 25
============================================================
Intento 1 | filas: 994 | errores: 0
Tiempo batch: 19.87 s

============================================================
BATCH 277/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 129.41 s
⚠️ Errores en batch: 50

============================================================
BATCH 278/378 | tamaño = 25
============================================================
Intento 1 | filas: 2142 | errores: 0
Tiempo batch: 4.17 s

============================================================
BATCH 279/378 | tamaño = 25
============================================================
Intento 1 | filas: 1693 | errores: 0
Tiempo batch: 6.57 s

============================================================
BATCH 280/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 128.24 s
⚠️ Errores en batch: 50

>>> PROGRESO: 7,000/9,448 bonos (74.09%)

2026-03-24 23:46:11 | INFO | OAS progreso: batch 280 / 378 | bonos aprox. 7,000 / 9,448
2026-03-24 23:46:11,934 P[19164] [MainThread 20064] OAS progreso: batch 280 / 378 | bonos aprox. 7,000 / 9,448

============================================================
BATCH 281/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 129.19 s
⚠️ Errores en batch: 50

============================================================
BATCH 282/378 | tamaño = 25
============================================================
Intento 1 | filas: 1535 | errores: 0
Tiempo batch: 2.98 s

============================================================
BATCH 283/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 123.43 s
⚠️ Errores en batch: 50

============================================================
BATCH 284/378 | tamaño = 25
============================================================
Intento 1 | filas: 1551 | errores: 0
Tiempo batch: 7.93 s

============================================================
BATCH 285/378 | tamaño = 25
============================================================
Intento 1 | filas: 1290 | errores: 0
Tiempo batch: 2.30 s

============================================================
BATCH 286/378 | tamaño = 25
============================================================
Intento 1 | filas: 1426 | errores: 0
Tiempo batch: 2.48 s

============================================================
BATCH 287/378 | tamaño = 25
============================================================
Intento 1 | filas: 1486 | errores: 0
Tiempo batch: 2.70 s

============================================================
BATCH 288/378 | tamaño = 25
============================================================
Intento 1 | filas: 998 | errores: 0
Tiempo batch: 1.91 s

============================================================
BATCH 289/378 | tamaño = 25
============================================================
Intento 1 | filas: 713 | errores: 0
Tiempo batch: 1.89 s

============================================================
BATCH 290/378 | tamaño = 25
============================================================
Intento 1 | filas: 1317 | errores: 0
Tiempo batch: 2.58 s

>>> PROGRESO: 7,250/9,448 bonos (76.74%)

2026-03-24 23:51:19 | INFO | OAS progreso: batch 290 / 378 | bonos aprox. 7,250 / 9,448
2026-03-24 23:51:19,337 P[19164] [MainThread 20064] OAS progreso: batch 290 / 378 | bonos aprox. 7,250 / 9,448

============================================================
BATCH 291/378 | tamaño = 25
============================================================
Intento 1 | filas: 1742 | errores: 0
Tiempo batch: 2.22 s

============================================================
BATCH 292/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 128.33 s
⚠️ Errores en batch: 50

============================================================
BATCH 293/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 129.44 s
⚠️ Errores en batch: 50

============================================================
BATCH 294/378 | tamaño = 25
============================================================
Intento 1 | filas: 1601 | errores: 0
Tiempo batch: 2.29 s

============================================================
BATCH 295/378 | tamaño = 25
============================================================
Intento 1 | filas: 1931 | errores: 0
Tiempo batch: 2.93 s

============================================================
BATCH 296/378 | tamaño = 25
============================================================
Intento 1 | filas: 1525 | errores: 0
Tiempo batch: 2.36 s

============================================================
BATCH 297/378 | tamaño = 25
============================================================
Intento 1 | filas: 1414 | errores: 0
Tiempo batch: 4.02 s

============================================================
BATCH 298/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 134.13 s
⚠️ Errores en batch: 50

============================================================
BATCH 299/378 | tamaño = 25
============================================================
Intento 1 | filas: 1987 | errores: 0
Tiempo batch: 2.61 s

============================================================
BATCH 300/378 | tamaño = 25
============================================================
Intento 1 | filas: 1843 | errores: 0
Tiempo batch: 2.78 s

>>> PROGRESO: 7,500/9,448 bonos (79.38%)

2026-03-24 23:58:40 | INFO | OAS progreso: batch 300 / 378 | bonos aprox. 7,500 / 9,448
2026-03-24 23:58:40,461 P[19164] [MainThread 20064] OAS progreso: batch 300 / 378 | bonos aprox. 7,500 / 9,448

============================================================
BATCH 301/378 | tamaño = 25
============================================================
Intento 1 | filas: 2447 | errores: 0
Tiempo batch: 8.83 s

============================================================
BATCH 302/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 129.64 s
⚠️ Errores en batch: 50

============================================================
BATCH 303/378 | tamaño = 25
============================================================
Intento 1 | filas: 2273 | errores: 0
Tiempo batch: 2.92 s

============================================================
BATCH 304/378 | tamaño = 25
============================================================
Intento 1 | filas: 2097 | errores: 0
Tiempo batch: 6.26 s

============================================================
BATCH 305/378 | tamaño = 25
============================================================
Intento 1 | filas: 1784 | errores: 0
Tiempo batch: 3.16 s

============================================================
BATCH 306/378 | tamaño = 25
============================================================
Intento 1 | filas: 1903 | errores: 0
Tiempo batch: 20.74 s

============================================================
BATCH 307/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 134.67 s
⚠️ Errores en batch: 50

============================================================
BATCH 308/378 | tamaño = 25
============================================================
Intento 1 | filas: 1678 | errores: 0
Tiempo batch: 2.47 s

============================================================
BATCH 309/378 | tamaño = 25
============================================================
Intento 1 | filas: 1169 | errores: 0
Tiempo batch: 2.30 s

============================================================
BATCH 310/378 | tamaño = 25
============================================================
Intento 1 | filas: 1465 | errores: 0
Tiempo batch: 2.18 s

>>> PROGRESO: 7,750/9,448 bonos (82.03%)

2026-03-25 00:04:23 | INFO | OAS progreso: batch 310 / 378 | bonos aprox. 7,750 / 9,448
2026-03-25 00:04:23,620 P[19164] [MainThread 20064] OAS progreso: batch 310 / 378 | bonos aprox. 7,750 / 9,448

============================================================
BATCH 311/378 | tamaño = 25
============================================================
Intento 1 | filas: 1845 | errores: 0
Tiempo batch: 3.05 s

============================================================
BATCH 312/378 | tamaño = 25
============================================================
Intento 1 | filas: 1346 | errores: 0
Tiempo batch: 2.24 s

============================================================
BATCH 313/378 | tamaño = 25
============================================================
Intento 1 | filas: 1498 | errores: 0
Tiempo batch: 2.78 s

============================================================
BATCH 314/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 128.23 s
⚠️ Errores en batch: 50

============================================================
BATCH 315/378 | tamaño = 25
============================================================
Intento 1 | filas: 1816 | errores: 0
Tiempo batch: 7.41 s

============================================================
BATCH 316/378 | tamaño = 25
============================================================
Intento 1 | filas: 1873 | errores: 0
Tiempo batch: 2.66 s

============================================================
BATCH 317/378 | tamaño = 25
============================================================
Intento 1 | filas: 2450 | errores: 0
Tiempo batch: 3.31 s

============================================================
BATCH 318/378 | tamaño = 25
============================================================
Intento 1 | filas: 1139 | errores: 0
Tiempo batch: 29.20 s

============================================================
BATCH 319/378 | tamaño = 25
============================================================
Intento 1 | filas: 1513 | errores: 0
Tiempo batch: 2.66 s

============================================================
BATCH 320/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 129.63 s
⚠️ Errores en batch: 50

>>> PROGRESO: 8,000/9,448 bonos (84.67%)

2026-03-25 00:10:04 | INFO | OAS progreso: batch 320 / 378 | bonos aprox. 8,000 / 9,448
2026-03-25 00:10:04,794 P[19164] [MainThread 20064] OAS progreso: batch 320 / 378 | bonos aprox. 8,000 / 9,448

============================================================
BATCH 321/378 | tamaño = 25
============================================================
Intento 1 | filas: 1736 | errores: 0
Tiempo batch: 2.77 s

============================================================
BATCH 322/378 | tamaño = 25
============================================================
Intento 1 | filas: 2249 | errores: 0
Tiempo batch: 2.83 s

============================================================
BATCH 323/378 | tamaño = 25
============================================================
Intento 1 | filas: 1729 | errores: 0
Tiempo batch: 2.33 s

============================================================
BATCH 324/378 | tamaño = 25
============================================================
Intento 1 | filas: 1232 | errores: 0
Tiempo batch: 3.58 s

============================================================
BATCH 325/378 | tamaño = 25
============================================================
Intento 1 | filas: 1317 | errores: 0
Tiempo batch: 2.61 s

============================================================
BATCH 326/378 | tamaño = 25
============================================================
Intento 1 | filas: 1578 | errores: 0
Tiempo batch: 2.49 s

============================================================
BATCH 327/378 | tamaño = 25
============================================================
Intento 1 | filas: 1549 | errores: 0
Tiempo batch: 2.92 s

============================================================
BATCH 328/378 | tamaño = 25
============================================================
Intento 1 | filas: 2028 | errores: 0
Tiempo batch: 2.71 s

============================================================
BATCH 329/378 | tamaño = 25
============================================================
Intento 1 | filas: 1814 | errores: 0
Tiempo batch: 6.44 s

============================================================
BATCH 330/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 130.58 s
⚠️ Errores en batch: 50

>>> PROGRESO: 8,250/9,448 bonos (87.32%)

2026-03-25 00:13:14 | INFO | OAS progreso: batch 330 / 378 | bonos aprox. 8,250 / 9,448
2026-03-25 00:13:14,073 P[19164] [MainThread 20064] OAS progreso: batch 330 / 378 | bonos aprox. 8,250 / 9,448

============================================================
BATCH 331/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 122.37 s
⚠️ Errores en batch: 50

============================================================
BATCH 332/378 | tamaño = 25
============================================================
Intento 1 | filas: 1680 | errores: 0
Tiempo batch: 2.51 s

============================================================
BATCH 333/378 | tamaño = 25
============================================================
Intento 1 | filas: 1471 | errores: 0
Tiempo batch: 2.59 s

============================================================
BATCH 334/378 | tamaño = 25
============================================================
Intento 1 | filas: 1153 | errores: 0
Tiempo batch: 5.15 s

============================================================
BATCH 335/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 128.24 s
⚠️ Errores en batch: 50

============================================================
BATCH 336/378 | tamaño = 25
============================================================
Intento 1 | filas: 1360 | errores: 0
Tiempo batch: 2.40 s

============================================================
BATCH 337/378 | tamaño = 25
============================================================
Intento 1 | filas: 1811 | errores: 0
Tiempo batch: 19.77 s

============================================================
BATCH 338/378 | tamaño = 25
============================================================
Intento 1 | filas: 769 | errores: 0
Tiempo batch: 4.47 s

============================================================
BATCH 339/378 | tamaño = 25
============================================================
Intento 1 | filas: 1500 | errores: 0
Tiempo batch: 2.61 s

============================================================
BATCH 340/378 | tamaño = 25
============================================================
Intento 1 | filas: 1577 | errores: 0
Tiempo batch: 2.57 s

>>> PROGRESO: 8,500/9,448 bonos (89.97%)

2026-03-25 00:18:36 | INFO | OAS progreso: batch 340 / 378 | bonos aprox. 8,500 / 9,448
2026-03-25 00:18:36,765 P[19164] [MainThread 20064] OAS progreso: batch 340 / 378 | bonos aprox. 8,500 / 9,448

============================================================
BATCH 341/378 | tamaño = 25
============================================================
Intento 1 | filas: 1734 | errores: 0
Tiempo batch: 2.97 s

============================================================
BATCH 342/378 | tamaño = 25
============================================================
Intento 1 | filas: 676 | errores: 0
Tiempo batch: 2.36 s

============================================================
BATCH 343/378 | tamaño = 25
============================================================
Intento 1 | filas: 1570 | errores: 0
Tiempo batch: 4.83 s

============================================================
BATCH 344/378 | tamaño = 25
============================================================
Intento 1 | filas: 1683 | errores: 0
Tiempo batch: 2.67 s

============================================================
BATCH 345/378 | tamaño = 25
============================================================
Intento 1 | filas: 1764 | errores: 0
Tiempo batch: 7.67 s

============================================================
BATCH 346/378 | tamaño = 25
============================================================
Intento 1 | filas: 796 | errores: 0
Tiempo batch: 2.30 s

============================================================
BATCH 347/378 | tamaño = 25
============================================================
Intento 1 | filas: 1065 | errores: 0
Tiempo batch: 7.14 s

============================================================
BATCH 348/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 121.09 s
⚠️ Errores en batch: 50

============================================================
BATCH 349/378 | tamaño = 25
============================================================
Intento 1 | filas: 1142 | errores: 0
Tiempo batch: 2.17 s

============================================================
BATCH 350/378 | tamaño = 25
============================================================
Intento 1 | filas: 1124 | errores: 0
Tiempo batch: 7.00 s

>>> PROGRESO: 8,750/9,448 bonos (92.61%)

2026-03-25 00:21:46 | INFO | OAS progreso: batch 350 / 378 | bonos aprox. 8,750 / 9,448
2026-03-25 00:21:46,982 P[19164] [MainThread 20064] OAS progreso: batch 350 / 378 | bonos aprox. 8,750 / 9,448

============================================================
BATCH 351/378 | tamaño = 25
============================================================
Intento 1 | filas: 668 | errores: 0
Tiempo batch: 4.23 s

============================================================
BATCH 352/378 | tamaño = 25
============================================================
Intento 1 | filas: 1135 | errores: 0
Tiempo batch: 1.99 s

============================================================
BATCH 353/378 | tamaño = 25
============================================================
Intento 1 | filas: 1816 | errores: 0
Tiempo batch: 2.72 s

============================================================
BATCH 354/378 | tamaño = 25
============================================================
Intento 1 | filas: 2005 | errores: 0
Tiempo batch: 2.71 s

============================================================
BATCH 355/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 121.24 s
⚠️ Errores en batch: 50

============================================================
BATCH 356/378 | tamaño = 25
============================================================
Intento 1 | filas: 1588 | errores: 0
Tiempo batch: 3.06 s

============================================================
BATCH 357/378 | tamaño = 25
============================================================
Intento 1 | filas: 1087 | errores: 0
Tiempo batch: 2.63 s

============================================================
BATCH 358/378 | tamaño = 25
============================================================
Intento 1 | filas: 634 | errores: 0
Tiempo batch: 2.49 s

============================================================
BATCH 359/378 | tamaño = 25
============================================================
Intento 1 | filas: 1682 | errores: 0
Tiempo batch: 2.63 s

============================================================
BATCH 360/378 | tamaño = 25
============================================================
Intento 1 | filas: 1184 | errores: 0
Tiempo batch: 2.47 s

>>> PROGRESO: 9,000/9,448 bonos (95.26%)

2026-03-25 00:24:43 | INFO | OAS progreso: batch 360 / 378 | bonos aprox. 9,000 / 9,448
2026-03-25 00:24:43,186 P[19164] [MainThread 20064] OAS progreso: batch 360 / 378 | bonos aprox. 9,000 / 9,448

============================================================
BATCH 361/378 | tamaño = 25
============================================================
Intento 1 | filas: 1176 | errores: 0
Tiempo batch: 2.56 s

============================================================
BATCH 362/378 | tamaño = 25
============================================================
Intento 1 | filas: 1646 | errores: 0
Tiempo batch: 2.70 s

============================================================
BATCH 363/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 130.06 s
⚠️ Errores en batch: 50

============================================================
BATCH 364/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 129.26 s
⚠️ Errores en batch: 50

============================================================
BATCH 365/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 122.08 s
⚠️ Errores en batch: 50

============================================================
BATCH 366/378 | tamaño = 25
============================================================
Intento 1 | filas: 1705 | errores: 0
Tiempo batch: 2.76 s

============================================================
BATCH 367/378 | tamaño = 25
============================================================
Intento 1 | filas: 1790 | errores: 0
Tiempo batch: 2.85 s

============================================================
BATCH 368/378 | tamaño = 25
============================================================
Intento 1 | filas: 1678 | errores: 0
Tiempo batch: 2.36 s

============================================================
BATCH 369/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 122.02 s
⚠️ Errores en batch: 50

============================================================
BATCH 370/378 | tamaño = 25
============================================================
Intento 1 | filas: 1176 | errores: 0
Tiempo batch: 20.82 s

>>> PROGRESO: 9,250/9,448 bonos (97.90%)

2026-03-25 00:34:10 | INFO | OAS progreso: batch 370 / 378 | bonos aprox. 9,250 / 9,448
2026-03-25 00:34:10,664 P[19164] [MainThread 20064] OAS progreso: batch 370 / 378 | bonos aprox. 9,250 / 9,448

============================================================
BATCH 371/378 | tamaño = 25
============================================================
Intento 1 | filas: 1146 | errores: 0
Tiempo batch: 5.53 s

============================================================
BATCH 372/378 | tamaño = 25
============================================================
Intento 1 | filas: 1850 | errores: 0
Tiempo batch: 3.04 s

============================================================
BATCH 373/378 | tamaño = 25
============================================================
Intento 1 | filas: 1728 | errores: 0
Tiempo batch: 5.58 s

============================================================
BATCH 374/378 | tamaño = 25
============================================================
Intento 1 | filas: 1749 | errores: 0
Tiempo batch: 2.76 s

============================================================
BATCH 375/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 128.20 s
⚠️ Errores en batch: 50

============================================================
BATCH 376/378 | tamaño = 25
============================================================
Intento 1 | filas: 25 | errores: 50
Tiempo batch: 122.22 s
⚠️ Errores en batch: 50

============================================================
BATCH 377/378 | tamaño = 25
============================================================
Intento 1 | filas: 1106 | errores: 0
Tiempo batch: 2.81 s

============================================================
BATCH 378/378 | tamaño = 23
============================================================
Intento 1 | filas: 1828 | errores: 0
Tiempo batch: 6.08 s

>>> PROGRESO: 9,448/9,448 bonos (100.00%)

2026-03-25 00:39:10 | INFO | OAS progreso: batch 378 / 378 | bonos aprox. 9,448 / 9,448
2026-03-25 00:39:10,898 P[19164] [MainThread 20064] OAS progreso: batch 378 / 378 | bonos aprox. 9,448 / 9,448

=== OAS HIST ALL ===
Shape: (331272, 3)

=== OAS COVERAGE ===
     bond_ric first_date  last_date  n_obs
0  001055AD4= 2015-01-30 2025-12-31    132
1  001055AF9=        NaT        NaT      0
2  001055AQ5= 2016-09-26 2025-12-31    112
3  001055AR3=        NaT        NaT      0
4  001055AY8=        NaT        NaT      0

2026-03-25 00:39:13 | INFO | Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/raw/oas_spreads_monthly_bond.parquet | rows=331,272 cols=5
2026-03-25 00:39:13,251 P[19164] [MainThread 20064] Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/raw/oas_spreads_monthly_bond.parquet | rows=331,272 cols=5
2026-03-25 00:39:14 | INFO | Guardado OAS en: C:\Users\vidar\OneDrive\Desktop\UDESA\Tesis\Tesis-main\data\raw\oas_spreads_monthly_bond.parquet
2026-03-25 00:39:14,223 P[19164] [MainThread 20064] Guardado OAS en: C:\Users\vidar\OneDrive\Desktop\UDESA\Tesis\Tesis-main\data\raw\oas_spreads_monthly_bond.parquet
2026-03-25 00:39:14 | INFO | Filas OAS: 331,272
2026-03-25 00:39:14,225 P[19164] [MainThread 20064] Filas OAS: 331,272
2026-03-25 00:39:14 | INFO | Bond RICs con OAS: 9,448 / 9,448
2026-03-25 00:39:14,266 P[19164] [MainThread 20064] Bond RICs con OAS: 9,448 / 9,448
2026-03-25 00:39:14 | INFO | Bond RICs sin OAS o fallidos: 2,269
2026-03-25 00:39:14,267 P[19164] [MainThread 20064] Bond RICs sin OAS o fallidos: 2,269

## 13bis) Enriquecimiento de bonos con maturity y residual maturity

**Input 1:** `df_bonds_universe`, construido a partir de los batches amplios de bonos descargados desde Workspace y filtrados por el universo de firmas del S&P 500.  
**Input 2:** `oas_spreads_monthly_bond.parquet`, con OAS mensual a nivel bono descargado desde Refinitiv.

### Objetivo
Preservar la metadata estructural del bono dentro del parquet mensual a nivel bono, en particular la fecha de vencimiento (`Maturity`) y la `residual_maturity_years`.

### Lógica
A diferencia de la versión anterior del pipeline, esta sección ya no utiliza archivos de yields ni construye spreads manualmente.  
La maturity del bono se toma directamente desde `df_bonds_universe`, que ya la preserva desde los exports amplios de Workspace. Luego esa metadata se mergea con el OAS mensual descargado desde Refinitiv.

A partir de `Maturity` y la fecha de observación (`date`), se calcula:

`residual_maturity_years = (Maturity - date) / 365.25`

### Output
- `bonds_monthly_spreads.parquet`
- `bonds_monthly_spreads.csv`

### Interpretación
Este parquet conserva el nombre histórico por compatibilidad con el resto del pipeline, pero en la versión actual ya no representa spreads construidos a partir de yields.  
Representa un panel mensual a nivel bono con:

- OAS descargado directamente desde Refinitiv,
- metadata del bono,
- y residual maturity derivada de la fecha de vencimiento.

In [31]:
# ==========================================================
# 13bis. Enriquecer bonos con Maturity y residual maturity
# ==========================================================

import pandas as pd
import numpy as np

# ----------------------------------------------------------
# Paths
# ----------------------------------------------------------
OUT_PARQUET = CLEAN_DIR / "bonds_monthly_spreads.parquet"
OUT_CSV     = CLEAN_DIR / "bonds_monthly_spreads.csv"

# ----------------------------------------------------------
# Helpers
# ----------------------------------------------------------
def to_eom(s):
    return pd.to_datetime(s, errors="coerce").dt.to_period("M").dt.to_timestamp("M")

def pick_col(df, candidates):
    cols = list(df.columns)
    lower_map = {str(c).lower(): c for c in cols}
    for cand in candidates:
        if cand in cols:
            return cand
        if str(cand).lower() in lower_map:
            return lower_map[str(cand).lower()]
    return None

def clean_ric(s):
    s = s.astype(str).str.strip()
    s = s.replace({"": pd.NA, "nan": pd.NA, "None": pd.NA, "NAN": pd.NA, "NONE": pd.NA})
    return s

# ----------------------------------------------------------
# 1) Validaciones básicas
# ----------------------------------------------------------
if "df_bonds_universe" not in globals():
    raise ValueError(
        "No encontré 'df_bonds_universe' en memoria. "
        "Primero corré la celda que construye el universo de bonos desde "
        "'data/inputs/new_bonds/' y lo filtra por el universo S&P 500."
    )

oas_path = OUT["oas_spreads_monthly_bond"] if "oas_spreads_monthly_bond" in OUT else (RAW_DIR / "oas_spreads_monthly_bond.parquet")
if not oas_path.exists():
    raise FileNotFoundError(f"No encontré el archivo de OAS: {oas_path}")

oas = pd.read_parquet(oas_path).copy()
bonds_meta = df_bonds_universe.copy()

# ----------------------------------------------------------
# 2) Normalizar metadata de bonos (fuente oficial de Maturity)
# ----------------------------------------------------------
ric_col = pick_col(bonds_meta, ["bond_ric", "Preferred RIC", "RIC", "Instrument", "Issue RIC"])
if ric_col is None:
    raise ValueError(
        f"No encontré columna de RIC en df_bonds_universe. Columnas: {list(bonds_meta.columns)}"
    )

mat_col = pick_col(bonds_meta, ["Maturity", "Maturity Date", "maturity"])
if mat_col is None:
    raise ValueError(
        f"No encontré columna de Maturity en df_bonds_universe. Columnas: {list(bonds_meta.columns)}"
    )

issuer_col = pick_col(bonds_meta, ["Issuer"])
ticker_col = pick_col(bonds_meta, ["Ticker"])
isin_col   = pick_col(bonds_meta, ["ISIN"])
coupon_col = pick_col(bonds_meta, ["Coupon"])
curr_col   = pick_col(bonds_meta, ["Principal_Currency", "Principal Currency"])
amt_col    = pick_col(bonds_meta, ["Amount_Issued_USD", "Amount Issued (USD)"])
src_col    = pick_col(bonds_meta, ["source_file"])

rename_map = {
    ric_col: "bond_ric",
    mat_col: "Maturity",
}
if issuer_col is not None:
    rename_map[issuer_col] = "Issuer"
if ticker_col is not None:
    rename_map[ticker_col] = "Ticker"
if isin_col is not None:
    rename_map[isin_col] = "ISIN"
if coupon_col is not None:
    rename_map[coupon_col] = "Coupon"
if curr_col is not None:
    rename_map[curr_col] = "Principal_Currency"
if amt_col is not None:
    rename_map[amt_col] = "Amount_Issued_USD"
if src_col is not None:
    rename_map[src_col] = "source_file"

keep_meta = list(rename_map.keys())

bonds_meta = bonds_meta[keep_meta].copy().rename(columns=rename_map)

bonds_meta["bond_ric"] = clean_ric(bonds_meta["bond_ric"])
bonds_meta["Maturity"] = pd.to_datetime(bonds_meta["Maturity"], errors="coerce")

if "Coupon" in bonds_meta.columns:
    bonds_meta["Coupon"] = pd.to_numeric(bonds_meta["Coupon"], errors="coerce")

if "Amount_Issued_USD" in bonds_meta.columns:
    bonds_meta["Amount_Issued_USD"] = pd.to_numeric(bonds_meta["Amount_Issued_USD"], errors="coerce")

bonds_meta = (
    bonds_meta
    .dropna(subset=["bond_ric"])
    .drop_duplicates(subset=["bond_ric"])
    .reset_index(drop=True)
)

print("\n=== QA bonds_meta ===")
print("Shape:", bonds_meta.shape)
print("RICs únicos:", bonds_meta["bond_ric"].nunique())
print("NA Maturity:", round(bonds_meta["Maturity"].isna().mean(), 4))
show_cols = [c for c in [
    "Issuer", "Ticker", "bond_ric", "Maturity", "ISIN", "Coupon",
    "Principal_Currency", "Amount_Issued_USD", "source_file"
] if c in bonds_meta.columns]
print(bonds_meta[show_cols].head())

# ----------------------------------------------------------
# 3) Preparar OAS mensual por bono
# ----------------------------------------------------------
oas.columns = [str(c).strip() for c in oas.columns]

ric_o = pick_col(oas, ["bond_ric", "RIC", "Instrument", "Preferred RIC", "Issue RIC"])
date_o = pick_col(oas, ["date", "Date"])
oas_o  = pick_col(oas, ["oas", "OAS", "oas_bps", "OAS(bp)", "Option Adjusted Spread Bid", "option_adjusted_spread"])

if ric_o is None or date_o is None:
    raise ValueError(
        f"No encontré columnas mínimas en oas_spreads_monthly_bond. Columnas: {list(oas.columns)}"
    )

oas = oas.rename(columns={
    ric_o: "bond_ric",
    date_o: "date",
})

if oas_o is not None and oas_o != "oas":
    oas = oas.rename(columns={oas_o: "oas"})

oas["bond_ric"] = clean_ric(oas["bond_ric"])
oas["date"] = to_eom(oas["date"])

if "oas" in oas.columns:
    oas["oas"] = pd.to_numeric(oas["oas"], errors="coerce")
else:
    oas["oas"] = pd.NA

# si hubiera múltiples filas por bond_ric-date, colapsa
agg_dict = {}
for c in oas.columns:
    if c in ["bond_ric", "date"]:
        continue
    if c == "oas":
        agg_dict[c] = "mean"
    else:
        agg_dict[c] = "first"

oas_m = oas.groupby(["bond_ric", "date"], as_index=False).agg(agg_dict)

print("\n=== QA oas_m ===")
print("Shape:", oas_m.shape)
print("RICs únicos:", oas_m["bond_ric"].nunique())
print("NA oas:", round(oas_m["oas"].isna().mean(), 4))
print(oas_m.head())

# ----------------------------------------------------------
# 4) Merge final: OAS + metadata + residual maturity
# ----------------------------------------------------------
bonds_monthly_spreads = oas_m.merge(
    bonds_meta,
    on="bond_ric",
    how="left",
    validate="m:1"
)

bonds_monthly_spreads["residual_maturity_years"] = (
    (bonds_monthly_spreads["Maturity"] - bonds_monthly_spreads["date"]).dt.days / 365.25
)

# negativos => NA
bonds_monthly_spreads.loc[
    bonds_monthly_spreads["residual_maturity_years"] < 0,
    "residual_maturity_years"
] = np.nan

print("\n=== QA bonds_monthly_spreads ===")
print("Shape:", bonds_monthly_spreads.shape)
print("RICs únicos:", bonds_monthly_spreads["bond_ric"].nunique())
print("NA Maturity:", round(bonds_monthly_spreads["Maturity"].isna().mean(), 4))
print("NA residual_maturity_years:", round(bonds_monthly_spreads["residual_maturity_years"].isna().mean(), 4))
print("NA oas:", round(bonds_monthly_spreads["oas"].isna().mean(), 4))

show_cols = [c for c in [
    "bond_ric", "date", "oas", "Maturity", "residual_maturity_years",
    "Issuer", "Ticker", "ISIN", "Coupon"
] if c in bonds_monthly_spreads.columns]
print(bonds_monthly_spreads[show_cols].head())

# ----------------------------------------------------------
# 5) Guardar
# ----------------------------------------------------------
OUT_PARQUET.parent.mkdir(parents=True, exist_ok=True)

bonds_monthly_spreads.to_parquet(OUT_PARQUET, index=False)
bonds_monthly_spreads.to_csv(OUT_CSV, index=False)

print(f"\n✅ Guardado parquet: {OUT_PARQUET}")
print(f"✅ Guardado csv:     {OUT_CSV}")

=== QA bonds_meta ===
Shape: (9448, 9)
RICs únicos: 9448
NA Maturity: 0.0
     Issuer Ticker    bond_ric   Maturity          ISIN  Coupon  \
0  AT&T INC      T  00206RML3= 2026-03-25  US00206RML32    1.70
1  AT&T INC      T  00206RHV7= 2026-07-15  US00206RHV78    2.95
2  AT&T INC      T  00206RGJ5= 2026-08-15  US00206RGJ59    7.30
3  AT&T INC      T  00206RHW5= 2027-02-15  US00206RHW51    3.80
4  AT&T INC      T  00206RDQ2= 2027-03-01  US00206RDQ20    4.25

  Principal_Currency  Amount_Issued_USD       source_file
0          US DOLLAR       3.000000e+09  first_batch.xlsx
1          US DOLLAR       7.072580e+08  first_batch.xlsx
2          US DOLLAR       2.127000e+07  first_batch.xlsx
3          US DOLLAR       1.329194e+09  first_batch.xlsx
4          US DOLLAR       2.000000e+09  first_batch.xlsx

=== QA oas_m ===
Shape: (327629, 5)
RICs únicos: 5805
NA oas: 0.0
     bond_ric       date    oas     Issuer Ticker
0  001055AD4= 2015-01-31  209.7  AFLAC INC    AFL
1  001055AD4= 2015-02-28  196.8  AFLAC INC    AFL
2  001055AD4= 2015-03-31  201.8  AFLAC INC    AFL
3  001055AD4= 2015-04-30  218.3  AFLAC INC    AFL
4  001055AD4= 2015-05-31  231.6  AFLAC INC    AFL

=== QA bonds_monthly_spreads ===
Shape: (327629, 14)
RICs únicos: 5805
NA Maturity: 0.0
NA residual_maturity_years: 0.0
NA oas: 0.0
     bond_ric       date    oas   Maturity  residual_maturity_years  \
0  001055AD4= 2015-01-31  209.7 2039-12-17                24.876112
1  001055AD4= 2015-02-28  196.8 2039-12-17                24.799452
2  001055AD4= 2015-03-31  201.8 2039-12-17                24.714579
3  001055AD4= 2015-04-30  218.3 2039-12-17                24.632444
4  001055AD4= 2015-05-31  231.6 2039-12-17                24.547570

           ISIN  Coupon
0  US001055AD49     6.9
1  US001055AD49     6.9
2  US001055AD49     6.9
3  US001055AD49     6.9
4  US001055AD49     6.9

✅ Guardado parquet: C:\Users\vidar\OneDrive\Desktop\UDESA\Tesis\Tesis-main\data\clean\bonds_monthly_spreads.parquet
✅ Guardado csv:     C:\Users\vidar\OneDrive\Desktop\UDESA\Tesis\Tesis-main\data\clean\bonds_monthly_spreads.csv

In [34]:
oas_all["bond_ric"].nunique()
oas_all["Ticker"].nunique()

328

## 14) CDS corporativo — spreads diarios (Primary CDS RIC)

**Input:** `data/inputs/empresas_tickers_test.csv` (Ticker/Issuer).  
**Output:** `data/raw/cds_spreads_daily.parquet` (+ `.csv`).  
**Chequeos:** emisores con CDS vs sin CDS, campo usado (5Y o genérico), rango de fechas y filas totales.  
**Notas:** se intenta primero `TR.CDSMidSpread5Y`; si no hay cobertura, se usa `TR.CDSMidSpread`. Se aplican pausas y reintentos ante 429.

In [35]:

# ======================
# CDS -> spreads diarios (Primary CDS RIC + PARMIDSPREAD)
# ======================

def clean_str_series(s: pd.Series) -> pd.Series:
    return (
        s.astype("string")
         .str.strip()
         .replace({"": pd.NA, "nan": pd.NA, "None": pd.NA, "NAN": pd.NA, "NONE": pd.NA})
    )

def get_primary_cds_ric_batch(rics_batch):
    """
    Devuelve el primary CDS RIC por emisor.
    """
    # limpiar batch antes de enviarlo
    rics_batch = [str(x).strip() for x in rics_batch if pd.notna(x) and str(x).strip() != ""]

    if not rics_batch:
        return pd.DataFrame()

    try:
        df, err = ek.get_data(rics_batch, ["TR.CDSPrimaryCDSRic"])

        print("\nPrimary CDS batch input:", rics_batch[:5])
        print(df.head() if df is not None else "df=None")
        print(err)

        if df is None or df.empty:
            return pd.DataFrame()

        df = df.rename(columns={
            "Instrument": "ric",
            "Primary CDS RIC": "primary_cds_ric"
        }).copy()

        df["ric"] = clean_str_series(df["ric"])
        df["primary_cds_ric"] = clean_str_series(df["primary_cds_ric"])

        return df

    except Exception as e:
        print(f"Error en primary CDS batch: {type(e).__name__}: {e}")
        return pd.DataFrame()


def get_cds_history_one(cds_ric, start_date, end_date):
    """
    Descarga histórico diario de PAR MID SPREAD para un CDS RIC.
    """
    cds_ric = "" if pd.isna(cds_ric) else str(cds_ric).strip()

    if cds_ric == "" or cds_ric.upper() in {"NONE", "NAN"}:
        return pd.DataFrame()

    try:
        df, err = ek.get_data(
            [cds_ric],
            ["TR.CDSType", "TR.PARMIDSPREAD.date", "TR.PARMIDSPREAD"],
            {
                "SDate": start_date,
                "EDate": end_date,
                "DateType": "AD",
                "CURN": "USD"
            }
        )

        print(f"\nTesting CDS history for {cds_ric}")
        print(df.head() if df is not None else "df=None")
        print(err)

        if df is None or df.empty:
            return pd.DataFrame()

        df = df.rename(columns={
            "Instrument": "cds_ric",
            "Date": "date",
            "Par Mid Spread": "cds_spread_bps",
            "CDS Type": "cds_type"
        }).copy()

        df["date"] = pd.to_datetime(df["date"], errors="coerce")
        df["cds_spread_bps"] = pd.to_numeric(df["cds_spread_bps"], errors="coerce")
        df["cds_ric"] = clean_str_series(df["cds_ric"])

        return df

    except Exception as e:
        print(f"Error CDS {cds_ric}: {type(e).__name__}: {e}")
        return pd.DataFrame()


# ----------------------
# Helper local
# ----------------------

def ticker_to_ric(ticker: str):
    ticker = str(ticker).strip().upper()

    nasdaq = {"AAPL","MSFT","GOOGL","META","CSCO","PEP","HON"}
    nyse   = {"JPM","BAC","C","WFC","GS","MS","XOM","CVX","COP","OXY",
              "JNJ","PFE","MRK","ABBV","PG","KO","MCD","WMT",
              "GE","MMM","CAT","DUK","NEE","SO","ORCL"}

    if ticker in nasdaq:
        return f"{ticker}.O"

    if ticker in nyse:
        return f"{ticker}.N"

    return f"{ticker}.N"


# ----------------------
# 1) Universo de emisores
# ----------------------

meta_path = RAW_DIR / "company_metadata.parquet"

# Universo base con Ticker / Issuer
df_univ = pd.read_csv(UNIVERSE_FILE, dtype=str).copy()
df_univ = df_univ.dropna(subset=["Ticker"]).reset_index(drop=True)

if "Issuer" not in df_univ.columns:
    df_univ["Issuer"] = pd.NA

df_univ["Ticker"] = df_univ["Ticker"].astype(str).str.strip()
if "RIC" in df_univ.columns:
    df_univ["RIC"] = clean_str_series(df_univ["RIC"])
else:
    df_univ["RIC"] = pd.NA

df_univ["ric"] = df_univ["RIC"]

mask_missing_ric = df_univ["ric"].isna()
df_univ.loc[mask_missing_ric, "ric"] = (
    df_univ.loc[mask_missing_ric, "Ticker"]
    .astype(str)
    .str.strip()
    .apply(ticker_to_ric)
)

df_univ["ric"] = clean_str_series(df_univ["ric"])

if meta_path.exists():
    meta_emp = pd.read_parquet(meta_path).copy()
    print("Usando metadata de empresas:", meta_path)

    # Normalizar nombre de columna del instrumento
    if "Instrument" in meta_emp.columns:
        meta_emp = meta_emp.rename(columns={"Instrument": "ric"})
    elif "RIC" in meta_emp.columns:
        meta_emp = meta_emp.rename(columns={"RIC": "ric"})

    if "ric" not in meta_emp.columns:
        raise RuntimeError("company_metadata.parquet no tiene columna 'ric'.")

    meta_emp["ric"] = clean_str_series(meta_emp["ric"])

    # Reconstruyo Ticker / Issuer desde el universo original
    df_emp = (
        meta_emp[["ric"]]
        .drop_duplicates()
        .merge(
            df_univ[["Ticker", "Issuer", "ric"]].drop_duplicates(),
            on="ric",
            how="left"
        )
    )

else:
    print("WARNING: no existe company_metadata.parquet. Uso fallback con Ticker.")
    df_emp = df_univ[["Ticker", "Issuer", "ric"]].drop_duplicates().copy()

df_emp["ric"] = clean_str_series(df_emp["ric"])
df_emp = df_emp.dropna(subset=["ric"]).drop_duplicates(subset=["ric"]).reset_index(drop=True)

rics = df_emp["ric"].tolist()
print(f"Emisores a pedir CDS: {len(rics)}")
print("Ejemplos rics:", rics[:10])


# ----------------------
# 2) Primary CDS RIC
# ----------------------
primary_frames = []

for batch in chunked(rics, 25):
    df_batch = get_primary_cds_ric_batch(batch)
    if not df_batch.empty:
        primary_frames.append(df_batch)

primary_cds = pd.concat(primary_frames, ignore_index=True) if primary_frames else pd.DataFrame()

if primary_cds.empty:
    raise RuntimeError("No se pudo obtener ningún Primary CDS RIC.")

primary_cds["ric"] = clean_str_series(primary_cds["ric"])
primary_cds["primary_cds_ric"] = clean_str_series(primary_cds["primary_cds_ric"])

primary_cds = (
    primary_cds
    .dropna(subset=["ric", "primary_cds_ric"])
    .drop_duplicates(subset=["ric", "primary_cds_ric"])
    .reset_index(drop=True)
)

print("Primary CDS RICs encontrados:", len(primary_cds))
print(primary_cds.head())


# ----------------------
# 3) Histórico CDS
# ----------------------
frames = []
invalid_primary = []

for _, row in primary_cds.iterrows():
    cds_ric = "" if pd.isna(row["primary_cds_ric"]) else str(row["primary_cds_ric"]).strip()
    issuer_ric = "" if pd.isna(row["ric"]) else str(row["ric"]).strip()

    if cds_ric == "" or cds_ric.upper() in {"NONE", "NAN"}:
        invalid_primary.append({"ric": issuer_ric, "primary_cds_ric": cds_ric})
        print(f"Primary CDS vacío/inválido: {issuer_ric} -> {cds_ric}")
        continue

    df = get_cds_history_one(cds_ric, START_DATE, END_DATE)

    if df is not None and not df.empty:
        df["ric"] = issuer_ric
        frames.append(df)
        print(f"OK CDS {issuer_ric} -> {cds_ric} | filas={len(df)}")
    else:
        print(f"Sin CDS histórico: {issuer_ric} -> {cds_ric}")

if not frames:
    raise RuntimeError("Ningún emisor devolvió histórico de CDS.")

cds_all = pd.concat(frames, ignore_index=True)

cds_all = cds_all.merge(
    df_emp[["ric", "Issuer", "Ticker"]].drop_duplicates(),
    on="ric",
    how="left"
)

cds_all = cds_all.sort_values(["ric", "date"]).reset_index(drop=True)

safe_write_parquet(cds_all, OUT["cds_spreads_daily"], index=False)

if invalid_primary:
    pd.DataFrame(invalid_primary).to_csv(
        OUT["cds_spreads_daily"].with_name("cds_invalid_primary_rics.csv"),
        index=False
    )

print(f"Filas CDS: {len(cds_all)}")
print(f"Emisores con CDS: {cds_all['ric'].nunique()}")
print("Guardado en:", OUT["cds_spreads_daily"])

Usando metadata de empresas: C:\Users\vidar\OneDrive\Desktop\UDESA\Tesis\Tesis-main\data\raw\company_metadata.parquet
Emisores a pedir CDS: 503
Ejemplos rics: ['PG.N', 'FDS.N', 'ODFL.OQ', 'GEHC.OQ', 'UAL.OQ', 'FCX.N', 'NOC.N', 'FIX.N', 'SNDK.OQ', 'EVRG.OQ']

Primary CDS batch input: ['PG.N', 'FDS.N', 'ODFL.OQ', 'GEHC.OQ', 'UAL.OQ']
  Instrument Primary CDS RIC
0       PG.N      PG5YUSAX=R
1      FDS.N
2    ODFL.OQ
3    GEHC.OQ
4     UAL.OQ    UAUA5YUSAX=R
None

Primary CDS batch input: ['RF.N', 'SBAC.OQ', 'CCI.N', 'CRWD.OQ', 'BLK.N']
  Instrument Primary CDS RIC
0       RF.N
1    SBAC.OQ
2      CCI.N
3    CRWD.OQ
4      BLK.N
None

Primary CDS batch input: ['MPWR.OQ', 'RVTY.N', 'DRI.N', 'CF.N', 'DOC.N']
  Instrument Primary CDS RIC
0    MPWR.OQ
1     RVTY.N    PKI5YUSAX=MP
2      DRI.N     DRI5YUSAX=R
3       CF.N
4      DOC.N
None

Primary CDS batch input: ['DHR.N', 'AXON.OQ', 'STT.N', 'BK.N', 'IT.N']
  Instrument Primary CDS RIC
0      DHR.N     DHR5YUSAX=R
1    AXON.OQ
2      STT.N    STT5YUSAX=MP
3       BK.N     BK5YUSAX=MT
4       IT.N
None

Primary CDS batch input: ['GIS.N', 'AEE.N', 'ABT.N', 'DLR.N', 'ULTA.OQ']
  Instrument Primary CDS RIC
0      GIS.N     GIS5YUSAX=R
1      AEE.N     AEE5YUSAX=R
2      ABT.N     ABT5YUSAX=R
3      DLR.N
4    ULTA.OQ
None

Primary CDS batch input: ['KR.N', 'ZBRA.OQ', 'ADM.N', 'FITB.OQ', 'REGN.OQ']
  Instrument Primary CDS RIC
0       KR.N      KR5YUSAX=R
1    ZBRA.OQ
2      ADM.N     ADM5YUSAX=R
3    FITB.OQ    FITB5YUSAX=R
4    REGN.OQ
None

Primary CDS batch input: ['EA.OQ', 'SOLV.N', 'RJF.N', 'CPAY.N', 'CVX.N']
  Instrument Primary CDS RIC
0      EA.OQ
1     SOLV.N
2      RJF.N
3     CPAY.N
4      CVX.N     CVX5YUSAX=R
None

Primary CDS batch input: ['SYF.N', 'UPS.N', 'MKC.N', 'AVY.N', 'COO.OQ']
  Instrument Primary CDS RIC
0      SYF.N    SYF5YUSAX=MP
1      UPS.N     UPS5YUSAX=R
2      MKC.N    MKC5YUSAR=FN
3      AVY.N     AVY5YUSAX=R
4     COO.OQ
None

Primary CDS batch input: ['SBUX.OQ', 'WFC.N', 'APH.N', 'HUM.N', 'IBM.N']
  Instrument Primary CDS RIC
0    SBUX.OQ  SBUX10YUSAX=MP
1      WFC.N     WFC5YUSAX=R
2      APH.N
3      HUM.N     HUM5YUSAX=R
4      IBM.N     IBM5YUSAX=R
None

Primary CDS batch input: ['KIM.N', 'WAB.N', 'ETR.N', 'EXC.OQ', 'ZTS.N']
  Instrument Primary CDS RIC
0      KIM.N
1      WAB.N
2      ETR.N     ETR5YUSAX=R
3     EXC.OQ     EXC5YUSAX=R
4      ZTS.N
None

Primary CDS batch input: ['UBER.N', 'INTU.OQ', 'CTRA.N', 'NTAP.OQ', 'F.N']
  Instrument Primary CDS RIC
0     UBER.N    UBER5YUSAX=R
1    INTU.OQ    INTU5YUSAX=R
2     CTRA.N
3    NTAP.OQ
4        F.N       F5YUSAX=R
None

Primary CDS batch input: ['FOX.OQ', 'XEL.OQ', 'CTAS.OQ', 'BALL.N', 'SJM.N']
  Instrument Primary CDS RIC
0     FOX.OQ
1     XEL.OQ    XCEL5YUSAX=R
2    CTAS.OQ
3     BALL.N     BLL5YUSAX=R
4      SJM.N
None

Primary CDS batch input: ['PPG.N', 'CRL.N', 'ACN.N', 'CFG.N', 'NVR.N']
  Instrument Primary CDS RIC
0      PPG.N     PPG5YUSAX=R
1      CRL.N
2      ACN.N
3      CFG.N   CIFK5YUSAX=MP
4      NVR.N     NVR5YUSAX=R
None

Primary CDS batch input: ['FAST.OQ', 'COR.N', 'ROST.OQ', 'PSA.N', 'CCL.N']
  Instrument Primary CDS RIC
0    FAST.OQ
1      COR.N    ABC5YUSAX=FN
2    ROST.OQ
3      PSA.N
4      CCL.N    CCLX5YUSAX=R
None

Primary CDS batch input: ['DD.N', 'HAL.N', 'NUE.N', 'FSLR.OQ', 'USB.N']
  Instrument Primary CDS RIC
0       DD.N
1      HAL.N     HAL5YUSAX=R
2      NUE.N     NUE5YUSAX=R
3    FSLR.OQ
4      USB.N     USB5YUSAX=R
None

Primary CDS batch input: ['L.N', 'FANG.OQ', 'GEN.OQ', 'SRE.N', 'POOL.OQ']
  Instrument Primary CDS RIC
0        L.N     LTR5YUSAX=R
1    FANG.OQ
2     GEN.OQ
3      SRE.N     SRE5YUSAX=R
4    POOL.OQ
None

Primary CDS batch input: ['MRK.N', 'CPRT.OQ', 'MA.N', 'UDR.N', 'AAPL.OQ']
  Instrument Primary CDS RIC
0      MRK.N     SGP5YUSAX=R
1    CPRT.OQ
2       MA.N
3      UDR.N    UDR5YUSAX=FN
4    AAPL.OQ    AAPL5YUSAX=R
None

Primary CDS batch input: ['V.N', 'LNT.OQ', 'DE.N', 'DECK.N', 'MSCI.N']
  Instrument Primary CDS RIC
0        V.N
1     LNT.OQ     LNT5YUSAX=R
2       DE.N      DE5YUSAX=R
3     DECK.N
4     MSCI.N
None

Primary CDS batch input: ['EL.N', 'MLM.N', 'LYB.N', 'VZ.N', 'VICI.N']
  Instrument Primary CDS RIC
0       EL.N      EL5YUSAX=R
1      MLM.N     MLM5YUSAX=R
2      LYB.N
3       VZ.N      VZ5YUSAX=R
4     VICI.N
None

Primary CDS batch input: ['DTE.N', 'GOOG.OQ', 'HWM.N', 'WM.N', 'SLB.N']
  Instrument Primary CDS RIC
0      DTE.N     DTE5YUSAX=R
1    GOOG.OQ   GOOF5YUSAX=MP
2      HWM.N    ARNL5YUSAX=R
3       WM.N     WMI5YUSAX=R
4      SLB.N     SLB5YUSAX=R
None

Primary CDS batch input: ['C.N', 'AXP.N', 'WRB.N']
  Instrument Primary CDS RIC
0        C.N       C5YUSAX=R
1      AXP.N     AXP5YUSAX=R
2      WRB.N     BER5YUSAR=R
None
Primary CDS RICs encontrados: 260
      ric primary_cds_ric
0    PG.N      PG5YUSAX=R
1  UAL.OQ    UAUA5YUSAX=R
2   FCX.N     FCX5YUSAX=R
3   NOC.N    NORV5YUSAX=R
4   TAP.N    TAP5YUSAX=FN

Testing CDS history for PG5YUSAX=R
   Instrument CDS Type  Date  Par Mid Spread
0  PG5YUSAX=R        C  <NA>            <NA>
[{'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.PARMIDSPREAD.DATE' and some specific identifier(s).", 'row': 0}, {'code': 416, 'col': 3, 'message': "Unable to collect data for the field 'Curn' and some specific identifier(s).", 'row': 0}]
OK CDS PG.N -> PG5YUSAX=R | filas=1

Testing CDS history for UAUA5YUSAX=R
     Instrument CDS Type  Date  Par Mid Spread
0  UAUA5YUSAX=R        C  <NA>            <NA>
[{'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.PARMIDSPREAD.DATE' and some specific identifier(s).", 'row': 0}, {'code': 416, 'col': 3, 'message': "Unable to collect data for the field 'Curn' and some specific identifier(s).", 'row': 0}]
OK CDS UAL.OQ -> UAUA5YUSAX=R | filas=1

Testing CDS history for FCX5YUSAX=R
    Instrument CDS Type                  Date  Par Mid Spread
0  FCX5YUSAX=R        C  2015-01-01T00:00:00Z            <NA>
1  FCX5YUSAX=R           2015-01-02T00:00:00Z            <NA>
2  FCX5YUSAX=R           2015-01-05T00:00:00Z            <NA>
3  FCX5YUSAX=R           2015-01-06T00:00:00Z            <NA>
4  FCX5YUSAX=R           2015-01-07T00:00:00Z            <NA>
None
OK CDS FCX.N -> FCX5YUSAX=R | filas=2870

Testing CDS history for NORV5YUSAX=R
     Instrument CDS Type                  Date  Par Mid Spread
0  NORV5YUSAX=R        C  2015-01-01T00:00:00Z           16.97
1  NORV5YUSAX=R           2015-01-02T00:00:00Z           16.97
2  NORV5YUSAX=R           2015-01-05T00:00:00Z           17.48
3  NORV5YUSAX=R           2015-01-06T00:00:00Z           17.48
4  NORV5YUSAX=R           2015-01-07T00:00:00Z           17.47
None
OK CDS NOC.N -> NORV5YUSAX=R | filas=2870

Testing CDS history for TAP5YUSAX=FN
     Instrument CDS Type                  Date  Par Mid Spread
0  TAP5YUSAX=FN        C  2014-12-31T00:00:00Z            70.0
1  TAP5YUSAX=FN           2015-01-02T00:00:00Z            70.0
2  TAP5YUSAX=FN           2015-01-05T00:00:00Z            73.0
3  TAP5YUSAX=FN           2015-01-06T00:00:00Z            75.0
4  TAP5YUSAX=FN           2015-01-07T00:00:00Z            73.5
None
OK CDS TAP.N -> TAP5YUSAX=FN | filas=2870

Testing CDS history for AMZN5YUSAX=R
     Instrument CDS Type                  Date  Par Mid Spread
0  AMZN5YUSAX=R        C  2015-01-01T00:00:00Z            <NA>
1  AMZN5YUSAX=R           2015-01-02T00:00:00Z            <NA>
2  AMZN5YUSAX=R           2015-01-05T00:00:00Z            <NA>
3  AMZN5YUSAX=R           2015-01-06T00:00:00Z            <NA>
4  AMZN5YUSAX=R           2015-01-07T00:00:00Z            <NA>
None
OK CDS AMZN.OQ -> AMZN5YUSAX=R | filas=2870

Testing CDS history for JNJ5YUSAX=R
    Instrument CDS Type                  Date  Par Mid Spread
0  JNJ5YUSAX=R        C  2015-01-01T00:00:00Z           14.92
1  JNJ5YUSAX=R           2015-01-02T00:00:00Z           14.92
2  JNJ5YUSAX=R           2015-01-05T00:00:00Z           14.93
3  JNJ5YUSAX=R           2015-01-06T00:00:00Z           15.01
4  JNJ5YUSAX=R           2015-01-07T00:00:00Z           13.21
None
OK CDS JNJ.N -> JNJ5YUSAX=R | filas=2870

Testing CDS history for NVDA5YUSAX=MP
      Instrument CDS Type  Date  Par Mid Spread
0  NVDA5YUSAX=MP        C  <NA>            <NA>
None
OK CDS NVDA.OQ -> NVDA5YUSAX=MP | filas=1

Testing CDS history for FDX5YUSAX=R
    Instrument CDS Type                  Date  Par Mid Spread
0  FDX5YUSAX=R        C  2015-01-01T00:00:00Z            42.6
1  FDX5YUSAX=R           2015-01-02T00:00:00Z            42.6
2  FDX5YUSAX=R           2015-01-05T00:00:00Z            43.1
3  FDX5YUSAX=R           2015-01-06T00:00:00Z           44.66
4  FDX5YUSAX=R           2015-01-07T00:00:00Z           44.11
None
OK CDS FDX.N -> FDX5YUSAX=R | filas=2870

Testing CDS history for GPN5YUSAX=MP
     Instrument CDS Type  Date  Par Mid Spread
0  GPN5YUSAX=MP        C  <NA>            <NA>
[{'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.PARMIDSPREAD.DATE' and some specific identifier(s).", 'row': 0}, {'code': 416, 'col': 3, 'message': "Unable to collect data for the field 'Curn' and some specific identifier(s).", 'row': 0}]
OK CDS GPN.N -> GPN5YUSAX=MP | filas=1

Testing CDS history for UNP5YUSAX=R
    Instrument CDS Type                  Date  Par Mid Spread
0  UNP5YUSAX=R        C  2015-01-01T00:00:00Z           16.41
1  UNP5YUSAX=R           2015-01-02T00:00:00Z            16.4
2  UNP5YUSAX=R           2015-01-05T00:00:00Z           16.42
3  UNP5YUSAX=R           2015-01-06T00:00:00Z           16.47
4  UNP5YUSAX=R           2015-01-07T00:00:00Z           16.91
None
OK CDS UNP.N -> UNP5YUSAX=R | filas=2870

Testing CDS history for EFX5YUSAR=R
          None  TR.CDSTYPE  TR.PARMIDSPREAD.DATE  TR.PARMIDSPREAD
0  EFX5YUSAR=R        <NA>                  <NA>             <NA>
[{'code': 412, 'col': 1, 'message': 'Unable to resolve all requested identifiers.', 'row': 0}, {'code': 412, 'col': 2, 'message': 'Unable to resolve all requested identifiers.', 'row': 0}, {'code': 412, 'col': 3, 'message': 'Unable to resolve all requested identifiers.', 'row': 0}]
Error CDS EFX5YUSAR=R: KeyError: 'date'
Sin CDS histórico: EFX.N -> EFX5YUSAR=R

Testing CDS history for JPM5YUSAX=R
    Instrument CDS Type  Date  Par Mid Spread
0  JPM5YUSAX=R        C  <NA>            <NA>
[{'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.PARMIDSPREAD.DATE' and some specific identifier(s).", 'row': 0}, {'code': 416, 'col': 3, 'message': "Unable to collect data for the field 'Curn' and some specific identifier(s).", 'row': 0}]
OK CDS JPM.N -> JPM5YUSAX=R | filas=1

Testing CDS history for CSX5YUSAX=R
    Instrument CDS Type                  Date  Par Mid Spread
0  CSX5YUSAX=R        C  2015-01-01T00:00:00Z            17.5
1  CSX5YUSAX=R           2015-01-02T00:00:00Z            17.5
2  CSX5YUSAX=R           2015-01-05T00:00:00Z           18.52
3  CSX5YUSAX=R           2015-01-06T00:00:00Z           18.53
4  CSX5YUSAX=R           2015-01-07T00:00:00Z           18.52
None
OK CDS CSX.OQ -> CSX5YUSAX=R | filas=2870

Testing CDS history for AMD5YUSAX=R
    Instrument CDS Type                  Date  Par Mid Spread
0  AMD5YUSAX=R        C  2015-01-01T00:00:00Z           647.5
1  AMD5YUSAX=R           2015-01-02T00:00:00Z          647.58
2  AMD5YUSAX=R           2015-01-05T00:00:00Z          659.93
3  AMD5YUSAX=R           2015-01-06T00:00:00Z          669.03
4  AMD5YUSAX=R           2015-01-07T00:00:00Z           672.0
None
OK CDS AMD.OQ -> AMD5YUSAX=R | filas=2870

Testing CDS history for COP5YUSAX=R
    Instrument CDS Type                  Date  Par Mid Spread
0  COP5YUSAX=R        C  2015-01-01T00:00:00Z           51.04
1  COP5YUSAX=R           2015-01-02T00:00:00Z           51.04
2  COP5YUSAX=R           2015-01-05T00:00:00Z           51.05
3  COP5YUSAX=R           2015-01-06T00:00:00Z           53.07
4  COP5YUSAX=R           2015-01-07T00:00:00Z           53.02
None
OK CDS COP.N -> COP5YUSAX=R | filas=2870

Testing CDS history for CRH5YEUAM=R
          None  TR.CDSTYPE  TR.PARMIDSPREAD.DATE  TR.PARMIDSPREAD
0  CRH5YEUAM=R        <NA>                  <NA>             <NA>
[{'code': 412, 'col': 1, 'message': 'Unable to resolve all requested identifiers.', 'row': 0}, {'code': 412, 'col': 2, 'message': 'Unable to resolve all requested identifiers.', 'row': 0}, {'code': 412, 'col': 3, 'message': 'Unable to resolve all requested identifiers.', 'row': 0}]
Error CDS CRH5YEUAM=R: KeyError: 'date'
Sin CDS histórico: CRH.N -> CRH5YEUAM=R

Testing CDS history for SWK5YUSAX=R
    Instrument CDS Type                  Date  Par Mid Spread
0  SWK5YUSAX=R        C  2015-01-01T00:00:00Z           66.95
1  SWK5YUSAX=R           2015-01-02T00:00:00Z           66.95
2  SWK5YUSAX=R           2015-01-05T00:00:00Z           66.95
3  SWK5YUSAX=R           2015-01-06T00:00:00Z           66.98
4  SWK5YUSAX=R           2015-01-07T00:00:00Z           66.95
None
OK CDS SWK.N -> SWK5YUSAX=R | filas=2870

Testing CDS history for TJX5YUSAX=R
    Instrument CDS Type                  Date  Par Mid Spread
0  TJX5YUSAX=R        C  2015-01-01T00:00:00Z           28.75
1  TJX5YUSAX=R           2015-01-02T00:00:00Z           28.74
2  TJX5YUSAX=R           2015-01-05T00:00:00Z           29.75
3  TJX5YUSAX=R           2015-01-06T00:00:00Z           29.86
4  TJX5YUSAX=R           2015-01-07T00:00:00Z           29.75
None
OK CDS TJX.N -> TJX5YUSAX=R | filas=2870

Testing CDS history for ED5YUSAX=R
         None  TR.CDSTYPE  TR.PARMIDSPREAD.DATE  TR.PARMIDSPREAD
0  ED5YUSAX=R        <NA>                  <NA>             <NA>
[{'code': 412, 'col': 1, 'message': 'Unable to resolve all requested identifiers.', 'row': 0}, {'code': 412, 'col': 2, 'message': 'Unable to resolve all requested identifiers.', 'row': 0}, {'code': 412, 'col': 3, 'message': 'Unable to resolve all requested identifiers.', 'row': 0}]
Error CDS ED5YUSAX=R: KeyError: 'date'
Sin CDS histórico: ED.N -> ED5YUSAX=R

Testing CDS history for PKI5YUSAX=MP
     Instrument CDS Type  Date  Par Mid Spread
0  PKI5YUSAX=MP        C  <NA>            <NA>
[{'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.PARMIDSPREAD.DATE' and some specific identifier(s).", 'row': 0}, {'code': 416, 'col': 3, 'message': "Unable to collect data for the field 'Curn' and some specific identifier(s).", 'row': 0}]
OK CDS RVTY.N -> PKI5YUSAX=MP | filas=1

Testing CDS history for DRI5YUSAX=R
    Instrument CDS Type                  Date  Par Mid Spread
0  DRI5YUSAX=R        C  2015-01-01T00:00:00Z          158.47
1  DRI5YUSAX=R           2015-01-02T00:00:00Z          158.48
2  DRI5YUSAX=R           2015-01-05T00:00:00Z          159.45
3  DRI5YUSAX=R           2015-01-06T00:00:00Z          159.44
4  DRI5YUSAX=R           2015-01-07T00:00:00Z          158.54
None
OK CDS DRI.N -> DRI5YUSAX=R | filas=2870

Testing CDS history for BLDR5YUSAX=MT
      Instrument CDS Type  Date  Par Mid Spread
0  BLDR5YUSAX=MT        C  <NA>            <NA>
[{'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.PARMIDSPREAD.DATE' and some specific identifier(s).", 'row': 0}, {'code': 416, 'col': 3, 'message': "Unable to collect data for the field 'Curn' and some specific identifier(s).", 'row': 0}]
OK CDS BLDR.N -> BLDR5YUSAX=MT | filas=1

Testing CDS history for FISV5YUSAX=R
     Instrument CDS Type                  Date  Par Mid Spread
0  FISV5YUSAX=R        C  2015-01-01T00:00:00Z            <NA>
1  FISV5YUSAX=R           2015-01-02T00:00:00Z            <NA>
2  FISV5YUSAX=R           2015-01-05T00:00:00Z            <NA>
3  FISV5YUSAX=R           2015-01-06T00:00:00Z            <NA>
4  FISV5YUSAX=R           2015-01-07T00:00:00Z            <NA>
None
OK CDS FISV.OQ -> FISV5YUSAX=R | filas=2870

Testing CDS history for SYY5YUSAX=R
    Instrument CDS Type                  Date  Par Mid Spread
0  SYY5YUSAX=R        C  2015-01-01T00:00:00Z            55.4
1  SYY5YUSAX=R           2015-01-02T00:00:00Z            55.4
2  SYY5YUSAX=R           2015-01-05T00:00:00Z            55.4
3  SYY5YUSAX=R           2015-01-06T00:00:00Z           53.14
4  SYY5YUSAX=R           2015-01-07T00:00:00Z           53.06
None
OK CDS SYY.N -> SYY5YUSAX=R | filas=2870

Testing CDS history for CHK5YUSAX=R
    Instrument CDS Type                  Date  Par Mid Spread
0  CHK5YUSAX=R        C  2015-01-01T00:00:00Z            <NA>
1  CHK5YUSAX=R           2015-01-02T00:00:00Z            <NA>
2  CHK5YUSAX=R           2015-01-05T00:00:00Z            <NA>
3  CHK5YUSAX=R           2015-01-06T00:00:00Z            <NA>
4  CHK5YUSAX=R           2015-01-07T00:00:00Z            <NA>
None
OK CDS EXE.OQ -> CHK5YUSAX=R | filas=2870

Testing CDS history for WY5YUSAX=R
   Instrument CDS Type                  Date  Par Mid Spread
0  WY5YUSAX=R        C  2015-01-01T00:00:00Z            43.6
1  WY5YUSAX=R           2015-01-02T00:00:00Z            43.6
2  WY5YUSAX=R           2015-01-05T00:00:00Z           43.61
3  WY5YUSAX=R           2015-01-06T00:00:00Z           44.12
4  WY5YUSAX=R           2015-01-07T00:00:00Z            44.1
None
OK CDS WY.N -> WY5YUSAX=R | filas=2870

Testing CDS history for T5YUSAX=R
  Instrument CDS Type  Date  Par Mid Spread
0  T5YUSAX=R        C  <NA>            <NA>
[{'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.PARMIDSPREAD.DATE' and some specific identifier(s).", 'row': 0}, {'code': 416, 'col': 3, 'message': "Unable to collect data for the field 'Curn' and some specific identifier(s).", 'row': 0}]
OK CDS T.N -> T5YUSAX=R | filas=1

Testing CDS history for ORCL5YUSAX=R
     Instrument CDS Type  Date  Par Mid Spread
0  ORCL5YUSAX=R        C  <NA>            <NA>
[{'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.PARMIDSPREAD.DATE' and some specific identifier(s).", 'row': 0}, {'code': 416, 'col': 3, 'message': "Unable to collect data for the field 'Curn' and some specific identifier(s).", 'row': 0}]
OK CDS ORCL.N -> ORCL5YUSAX=R | filas=1

Testing CDS history for XOM5YUSAX=R
    Instrument CDS Type  Date  Par Mid Spread
0  XOM5YUSAX=R        C  <NA>            <NA>
[{'code': 416, 'col': 2, 'message': "Unable to collect data for the field 'TR.PARMIDSPREAD.DATE' and some specific identifier(s).", 'row': 0}, {'code': 416, 'col': 3, 'message': "Unable to collect data for the field 'Curn' and some specific identifier(s).", 'row': 0}]
OK CDS XOM.N -> XOM5YUSAX=R | filas=1

Testing CDS history for KO5YUSAX=R
   Instrument CDS Type                  Date  Par Mid Spread
0  KO5YUSAX=R        C  2015-01-01T00:00:00Z           29.05
1  KO5YUSAX=R           2015-01-02T00:00:00Z           29.05
2  KO5YUSAX=R           2015-01-05T00:00:00Z           29.06
3  KO5YUSAX=R           2015-01-06T00:00:00Z           29.06
4  KO5YUSAX=R           2015-01-07T00:00:00Z           29.05
None
OK CDS KO.N -> KO5YUSAX=R | filas=2870

Testing CDS history for PHM5YUSAX=R
    Instrument CDS Type                  Date  Par Mid Spread
0  PHM5YUSAX=R        C  2015-01-01T00:00:00Z          151.79
1  PHM5YUSAX=R           2015-01-02T00:00:00Z          153.33
2  PHM5YUSAX=R           2015-01-05T00:00:00Z          155.89
3  PHM5YUSAX=R           2015-01-06T00:00:00Z          156.01
4  PHM5YUSAX=R           2015-01-07T00:00:00Z          155.41
None
OK CDS PHM.N -> PHM5YUSAX=R | filas=2870

Testing CDS history for DHR5YUSAX=R
    Instrument CDS Type                  Date  Par Mid Spread
0  DHR5YUSAX=R        C  2015-01-01T00:00:00Z           41.09
1  DHR5YUSAX=R           2015-01-02T00:00:00Z           41.09
2  DHR5YUSAX=R           2015-01-05T00:00:00Z            41.1
3  DHR5YUSAX=R           2015-01-06T00:00:00Z           41.16
4  DHR5YUSAX=R           2015-01-07T00:00:00Z           41.09
None
OK CDS DHR.N -> DHR5YUSAX=R | filas=2870

Testing CDS history for STT5YUSAX=MP
     Instrument CDS Type  Date  Par Mid Spread
0  STT5YUSAX=MP        C  <NA>            <NA>
None
OK CDS STT.N -> STT5YUSAX=MP | filas=1

Testing CDS history for BK5YUSAX=MT

2026-03-25 01:40:01,921 P[19164] [MainThread 20064] UDF Core request failed. Service Temporarily Unavailable
2026-03-25 01:40:01,922 P[19164] [MainThread 20064] HTTP request failed: EikonError-UDF Core request failed. Service Temporarily Unavailable

Error CDS C5YUSAX=R: EikonError: Error code 2503 | UDF Core request failed. Service Temporarily Unavailable
Sin CDS histórico: C.N -> C5YUSAX=R

Testing CDS history for AXP5YUSAX=R
    Instrument CDS Type                  Date  Par Mid Spread
0  AXP5YUSAX=R        C  2015-01-01T00:00:00Z           41.01
1  AXP5YUSAX=R           2015-01-02T00:00:00Z           41.01
2  AXP5YUSAX=R           2015-01-05T00:00:00Z           42.03
3  AXP5YUSAX=R           2015-01-06T00:00:00Z           42.76
4  AXP5YUSAX=R           2015-01-07T00:00:00Z           42.75
None
OK CDS AXP.N -> AXP5YUSAX=R | filas=2870

Testing CDS history for BER5YUSAR=R
    Instrument CDS Type  Date  Par Mid Spread
0  BER5YUSAR=R        C  <NA>            <NA>
None
OK CDS WRB.N -> BER5YUSAR=R | filas=1

2026-03-25 01:40:07 | INFO | Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/raw/cds_spreads_daily.parquet | rows=384,692 cols=7
2026-03-25 01:40:07,210 P[19164] [MainThread 20064] Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/raw/cds_spreads_daily.parquet | rows=384,692 cols=7

Filas CDS: 384692
Emisores con CDS: 246
Guardado en: C:\Users\vidar\OneDrive\Desktop\UDESA\Tesis\Tesis-main\data\raw\cds_spreads_daily.parquet

## 15) Revenue + market share (SP500) — revenue trimestral y participación por industria

**Input:** universo `0#.SPX` vía Refinitiv + `data/inputs/empresas_tickers_test.csv` para identificar la muestra.  
**Output:**  
- `data/raw/gics_industry_group_sales_quarterly_sp500.csv` (ventas agregadas por industria y trimestre)  
- `data/raw/fundamentals_with_market_share_sp500.csv` (panel SP500)  
- `data/raw/fundamentals_with_market_share.csv` (panel filtrado a la muestra)  

**Chequeos:** fuente de revenue usada, cobertura de GICS, filas por trimestre, market share en [0,1] (cuando hay industria).  
**Notas:** revenue se toma de un set de campos candidatos según disponibilidad/permisos. La agrupación base es `GICS Industry Group` (se puede cambiar a sector/industry si hiciera falta).

In [36]:
# ======================
# Revenue + market share (SP500)
# ======================

# ----------------------
# Helpers de descarga
# ----------------------
def chunked(items: list[str], n: int) -> Iterable[list[str]]:
    """Corta lista en batches."""
    for i in range(0, len(items), n):
        yield items[i:i + n]


def get_data_safe(
    rics_batch: list[str],
    fields: list[str],
    params: dict,
    max_retry: int = 3,
) -> pd.DataFrame:
    """
    Wrapper para ek.get_data con reintentos ante 429.
    Devuelve DataFrame (puede venir vacío).
    """
    for attempt in range(1, max_retry + 1):
        try:
            df, err = ek.get_data(rics_batch, fields=fields, parameters=params)
            if err is not None and len(err):
                logger.warning(f"Refinitiv warnings/errores (muestra): {str(err[:2])}")
            return df if df is not None else pd.DataFrame()

        except Exception as e:
            msg = str(e)
            if "429" in msg or "Too many requests" in msg:
                wait_sec = 4 + (attempt - 1) * 4
                logger.warning(f"429 en batch | espero {wait_sec}s | intento {attempt}/{max_retry}")
                time.sleep(wait_sec)
                continue

            logger.warning(f"Error en batch (no 429): {type(e).__name__}: {e}")
            return pd.DataFrame()

    return pd.DataFrame()


def get_metadata_batched(
    instruments: list[str],
    fields: list[str],
    batch_size: int = 25,
    pause_sec: float = 0.4,
) -> pd.DataFrame:
    """Baja metadata por batches usando ek.get_data (sin parameters)."""
    frames: list[pd.DataFrame] = []

    for i, batch in enumerate(chunked(instruments, batch_size), start=1):
        try:
            df_batch, err = ek.get_data(batch, fields=fields)
            if err is not None and len(err):
                logger.warning(f"Warnings/errores metadata batch (muestra): {str(err[:2])}")
            if df_batch is not None and not df_batch.empty:
                frames.append(df_batch)
        except Exception as e:
            logger.warning(f"Error metadata batch {i} | {type(e).__name__}: {e}")

        time.sleep(pause_sec)

    return pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()


def first_present(cands: list[str], cols_set: set[str]) -> Optional[str]:
    """Devuelve el primer candidato que exista en cols_set."""
    for c in cands:
        if c in cols_set:
            return c
    return None


# ----------------------
# 1) Muestra (para filtrar al final)
# ----------------------
df_emp = pd.read_csv(UNIVERSE_FILE, dtype=str)
df_emp["Ticker"] = df_emp["Ticker"].astype(str).str.strip()

RIC_FIX = {
    "PEP": "PEP.O",
    "ABBV": "ABBV.K",
    "HON": "HON.O",
    "AAPL": "AAPL.O",
    "CSCO": "CSCO.O",
    "ORCL": "ORCL.K",
    "META": "META.O",
    "GOOGL": "GOOGL.O",
    "MSFT": "MSFT.O",
}

def fix_ticker(t: str) -> str:
    t = str(t).strip()
    if not t:
        return t
    base = t.split(".")[0]
    return RIC_FIX.get(base, t)

df_emp["Ticker_fixed"] = df_emp["Ticker"].apply(fix_ticker)
df_emp["ric_base"] = df_emp["Ticker_fixed"].str.split(".").str[0]
target_bases = sorted(df_emp["ric_base"].dropna().unique().tolist())

logger.info(f"Muestra (bases RIC): {len(target_bases):,}")

# ----------------------
# 2) Universo SP500 (0#.SPX)
# ----------------------
logger.info("Descargando universo SP500 (0#.SPX) ...")
spx_df, spx_err = ek.get_data("0#.SPX", ["TR.RIC"])
if spx_err is not None and len(spx_err):
    logger.warning(f"Warnings universo SPX (muestra): {str(spx_err[:3])}")

if spx_df is None or spx_df.empty:
    raise RuntimeError("No llegó universo SPX desde Refinitiv.")

spx_df = spx_df.dropna(subset=["RIC"]).copy()
spx_df["RIC"] = spx_df["RIC"].astype(str).str.strip()
spx_rics = spx_df["RIC"].dropna().unique().tolist()

logger.info(f"RICs SP500 detectados: {len(spx_rics):,}")

# ----------------------
# 3) Metadata GICS SP500
# ----------------------
META_FIELDS = [
    "TR.CommonName",
    "TR.PrimaryRIC",
    "TR.ISIN",
    "TR.CUSIP",
    "TR.PermID",
    "TR.CompanyMarketCap",
    "TR.GICSSector",
    "TR.GICSSectorName",
    "TR.GICSIndustryGroup",
    "TR.GICSIndustryGroupName",
    "TR.GICSIndustry",
    "TR.GICSIndustryName",
    "TR.GICSSubIndustry",
    "TR.GICSSubIndustryName",
    "TR.HeadquartersCountry",
]

logger.info("Descargando metadata (GICS) para SP500 ...")
meta_spx = get_metadata_batched(spx_rics, META_FIELDS, batch_size=25, pause_sec=0.4)

if meta_spx.empty:
    raise RuntimeError("No llegó metadata SPX (GICS).")

meta_spx.columns = [str(c).strip() for c in meta_spx.columns]
meta_spx = meta_spx.rename(columns={
    "Instrument": "ric",
    "GICS Sector Name": "gics_sector_name",
    "GICS Industry Group Name": "gics_industry_group_name",
    "GICS Industry Name": "gics_industry_name",
    "GICS Sub-Industry Name": "gics_subindustry_name",
})

meta_spx["ric"] = meta_spx["ric"].astype(str).str.strip()

gics_cols = [
    "gics_sector_name",
    "gics_industry_group_name",
    "gics_industry_name",
    "gics_subindustry_name",
]

meta_spx_gics = meta_spx[["ric"] + gics_cols].drop_duplicates(subset=["ric"]).copy()
logger.info(f"Metadata GICS SP500 | filas={len(meta_spx_gics):,}")

# ----------------------
# 4) Fundamentals (revenue) SP500
# ----------------------
REV_CANDS = [
    "TR.F.TotRevenue",
    "TR.F.SalesTurnover",
    "TR.F.TotalRevenue",
    "TR.F.SalesOrRevenue",
    "TR.F.NetSales",
    "TR.F.Revenue",
    "TR.F.RevenueReported",
]

fields_funda = REV_CANDS + ["TR.F.PeriodEndDate"]

params = {
    "SDate": "2015-01-01",
    "EDate": "2025-12-31",
    "Frq": "Q",
    "Curn": "USD",
}

logger.info("Descargando fundamentals (revenue) para SP500 ...")

funda_frames: list[pd.DataFrame] = []
BATCH = 20
SLEEP_SEC = 1.0

for i, batch in enumerate(chunked(spx_rics, BATCH), start=1):
    logger.info(f"Batch funda {i} | size={len(batch)}")
    df_b = get_data_safe(batch, fields_funda, params, max_retry=RETRY_MAX)
    if df_b is not None and not df_b.empty:
        funda_frames.append(df_b)
    time.sleep(SLEEP_SEC)

if not funda_frames:
    raise RuntimeError("No llegó fundamentals de revenue.")

funda_all = pd.concat(funda_frames, ignore_index=True)
funda_all.columns = [str(c).strip() for c in funda_all.columns]
cols = set(funda_all.columns)

ric_col = first_present(["Instrument", "RIC", "TR.RIC", "Constituent RIC"], cols)
ped_col = first_present(["TR.F.PeriodEndDate", "Period End Date", "PeriodEndDate"], cols)
rev_col = first_present(
    REV_CANDS + ["Revenue from Business Activities - Total", "Revenue", "Sales/Turnover"],
    cols,
)

missing = [x for x, y in [("ric", ric_col), ("period_end", ped_col), ("revenue", rev_col)] if y is None]
if missing:
    raise RuntimeError(f"Columnas faltantes en fundamentals: {missing} | disponibles={sorted(cols)}")

logger.info(f"Campo revenue usado: {rev_col}")

funda_all = funda_all.rename(columns={ric_col: "ric", ped_col: "period_end", rev_col: "revenue"})
funda_all["ric"] = funda_all["ric"].astype(str).str.strip()
funda_all["period_end"] = pd.to_datetime(funda_all["period_end"], errors="coerce")
funda_all["revenue"] = pd.to_numeric(funda_all["revenue"], errors="coerce")

funda_all = funda_all.dropna(subset=["period_end"]).copy()
logger.info(f"Fundamentals revenue | filas={len(funda_all):,}")

# ----------------------
# 5) Merge + ventas industria + market share
# ----------------------
funda_all = funda_all.merge(meta_spx_gics, on="ric", how="left")

group_col = "gics_industry_group_name"
if group_col not in funda_all.columns:
    raise RuntimeError(f"No existe '{group_col}' en funda_all. Columnas={funda_all.columns.tolist()}")

sector_sales = (
    funda_all.dropna(subset=[group_col])
             .groupby([group_col, "period_end"], as_index=False)["revenue"]
             .sum()
             .rename(columns={"revenue": "industry_sales"})
)

out_sales = OUT.get(
    "gics_industry_group_sales_q_sp500",
    RAW_DIR / "gics_industry_group_sales_quarterly_sp500.csv"
)
sector_sales.to_csv(out_sales, index=False)
logger.info(f"Output -> {out_sales.as_posix()} | filas={len(sector_sales):,}")

funda_all = funda_all.merge(sector_sales, on=[group_col, "period_end"], how="left")
funda_all["market_share"] = funda_all["revenue"] / funda_all["industry_sales"]

# ----------------------
# 6) Export: SP500 completo + muestra
# ----------------------
funda_all["ric_base"] = funda_all["ric"].astype(str).str.split(".").str[0]

out_sp500 = OUT.get("fundamentals_with_market_share_sp500", RAW_DIR / "fundamentals_with_market_share_sp500.csv")
funda_all.to_csv(out_sp500, index=False)
logger.info(f"Output -> {out_sp500.as_posix()} | filas={len(funda_all):,}")

funda_focus = funda_all[funda_all["ric_base"].isin(target_bases)].copy()
out_focus = OUT.get("fundamentals_with_market_share_focus", RAW_DIR / "fundamentals_with_market_share.csv")
funda_focus.to_csv(out_focus, index=False)
logger.info(f"Output -> {out_focus.as_posix()} | filas={len(funda_focus):,}")

# QA rápido: market_share fuera de rango (solo donde hay industria_sales)
bad_ms = funda_all.loc[funda_all["industry_sales"].notna(), "market_share"]
share_oob = ((bad_ms < 0) | (bad_ms > 1)).sum()
if share_oob:
    logger.warning(f"Market share fuera de [0,1] (conteo): {int(share_oob)}")

# ==========================================================
# 7) FIX + Convertir quarterly → monthly (forward fill)
# ==========================================================

# ----------------------
# FIX 1: colapsar duplicados por ric-period_end
# ----------------------
funda_all = (
    funda_all
    .sort_values(["ric", "period_end"])
    .groupby(["ric", "period_end"], as_index=False)
    .agg({
        "revenue": "mean",
        "industry_sales": "mean",
        "market_share": "mean",
        "gics_sector_name": "first",
        "gics_industry_group_name": "first",
        "gics_industry_name": "first",
        "gics_subindustry_name": "first",
    })
)

print("\n=== QA after collapse ===")
print("Duplicados ric-period_end:", funda_all.duplicated(["ric", "period_end"]).sum())
print("Shape:", funda_all.shape)

# ----------------------
# FIX 2: crear fecha mensual
# ----------------------
funda_all["date"] = funda_all["period_end"].dt.to_period("M").dt.to_timestamp("M")

cols_keep = [
    "ric",
    "date",
    "market_share",
    "industry_sales",
    "revenue",
    "gics_sector_name",
    "gics_industry_group_name",
    "gics_industry_name",
    "gics_subindustry_name",
]

funda_monthly = funda_all[cols_keep].copy()

# ----------------------
# FIX 3: expansión mensual segura (sin resample bug)
# ----------------------
funda_monthly = funda_monthly.sort_values(["ric", "date"])

funda_monthly = (
    funda_monthly
    .groupby("ric", group_keys=False)
    .apply(lambda df: df.set_index("date").resample("M").ffill())
    .reset_index()
)

print("\n=== QA funda_monthly ===")
print("Shape:", funda_monthly.shape)
print("NA market_share:", round(funda_monthly["market_share"].isna().mean(), 4))
print(funda_monthly.head())

# ==========================================================
# 8) Export (MISMO NOMBRE QUE ANTES)
# ==========================================================

# SP500 completo
out_sp500 = OUT.get(
    "fundamentals_with_market_share_sp500",
    RAW_DIR / "fundamentals_with_market_share_sp500.csv"
)

funda_monthly.to_csv(out_sp500, index=False)
logger.info(f"Output -> {out_sp500.as_posix()} | filas={len(funda_monthly):,}")

# muestra (focus)
funda_monthly["ric_base"] = funda_monthly["ric"].astype(str).str.split(".").str[0]

funda_focus = funda_monthly[funda_monthly["ric_base"].isin(target_bases)].copy()

out_focus = OUT.get(
    "fundamentals_with_market_share_focus",
    RAW_DIR / "fundamentals_with_market_share.csv"
)

funda_focus.to_csv(out_focus, index=False)
logger.info(f"Output -> {out_focus.as_posix()} | filas={len(funda_focus):,}")

2026-03-25 01:43:26 | INFO | Muestra (bases RIC): 503
2026-03-25 01:43:26,715 P[19164] [MainThread 20064] Muestra (bases RIC): 503
2026-03-25 01:43:26 | INFO | Descargando universo SP500 (0#.SPX) ...
2026-03-25 01:43:26,717 P[19164] [MainThread 20064] Descargando universo SP500 (0#.SPX) ...
2026-03-25 01:43:28 | INFO | RICs SP500 detectados: 503
2026-03-25 01:43:28,150 P[19164] [MainThread 20064] RICs SP500 detectados: 503
2026-03-25 01:43:28 | INFO | Descargando metadata (GICS) para SP500 ...
2026-03-25 01:43:28,152 P[19164] [MainThread 20064] Descargando metadata (GICS) para SP500 ...
c:\Users\vidar\OneDrive\Desktop\UDESA\Tesis\Tesis-main\venv\Lib\site-packages\pandas\core\dtypes\cast.py:1056: RuntimeWarning: invalid value encountered in cast
  if (arr.astype(int) == arr).all():
c:\Users\vidar\OneDrive\Desktop\UDESA\Tesis\Tesis-main\venv\Lib\site-packages\pandas\core\dtypes\cast.py:1080: RuntimeWarning: invalid value encountered in cast
  if (arr.astype(int) == arr).all():
2026-03-25 01:43:54 | INFO | Metadata GICS SP500 | filas=503
2026-03-25 01:43:54,058 P[19164] [MainThread 20064] Metadata GICS SP500 | filas=503
2026-03-25 01:43:54 | INFO | Descargando fundamentals (revenue) para SP500 ...
2026-03-25 01:43:54,060 P[19164] [MainThread 20064] Descargando fundamentals (revenue) para SP500 ...
2026-03-25 01:43:54 | INFO | Batch funda 1 | size=20
2026-03-25 01:43:54,062 P[19164] [MainThread 20064] Batch funda 1 | size=20
c:\Users\vidar\OneDrive\Desktop\UDESA\Tesis\Tesis-main\venv\Lib\site-packages\pandas\core\dtypes\cast.py:1056: RuntimeWarning: invalid value encountered in cast
  if (arr.astype(int) == arr).all():
c:\Users\vidar\OneDrive\Desktop\UDESA\Tesis\Tesis-main\venv\Lib\site-packages\pandas\core\dtypes\cast.py:1080: RuntimeWarning: invalid value encountered in cast
  if (arr.astype(int) == arr).all():
2026-03-25 01:43:56 | INFO | Batch funda 2 | size=20
2026-03-25 01:43:56,108 P[19164] [MainThread 20064] Batch funda 2 | size=20
2026-03-25 01:43:57 | INFO | Batch funda 3 | size=20
2026-03-25 01:43:57,768 P[19164] [MainThread 20064] Batch funda 3 | size=20
2026-03-25 01:43:59 | INFO | Batch funda 4 | size=20
2026-03-25 01:43:59,596 P[19164] [MainThread 20064] Batch funda 4 | size=20
2026-03-25 01:44:01 | INFO | Batch funda 5 | size=20
2026-03-25 01:44:01,338 P[19164] [MainThread 20064] Batch funda 5 | size=20
2026-03-25 01:44:03 | INFO | Batch funda 6 | size=20
2026-03-25 01:44:03,026 P[19164] [MainThread 20064] Batch funda 6 | size=20
2026-03-25 01:44:04 | INFO | Batch funda 7 | size=20
2026-03-25 01:44:04,906 P[19164] [MainThread 20064] Batch funda 7 | size=20
2026-03-25 01:44:06 | INFO | Batch funda 8 | size=20
2026-03-25 01:44:06,658 P[19164] [MainThread 20064] Batch funda 8 | size=20
2026-03-25 01:44:08 | INFO | Batch funda 9 | size=20
2026-03-25 01:44:08,490 P[19164] [MainThread 20064] Batch funda 9 | size=20
2026-03-25 01:44:10 | INFO | Batch funda 10 | size=20
2026-03-25 01:44:10,168 P[19164] [MainThread 20064] Batch funda 10 | size=20
2026-03-25 01:44:11 | INFO | Batch funda 11 | size=20
2026-03-25 01:44:11,916 P[19164] [MainThread 20064] Batch funda 11 | size=20
2026-03-25 01:44:13 | INFO | Batch funda 12 | size=20
2026-03-25 01:44:13,678 P[19164] [MainThread 20064] Batch funda 12 | size=20
2026-03-25 01:44:15 | INFO | Batch funda 13 | size=20
2026-03-25 01:44:15,400 P[19164] [MainThread 20064] Batch funda 13 | size=20
2026-03-25 01:44:17 | INFO | Batch funda 14 | size=20
2026-03-25 01:44:17,171 P[19164] [MainThread 20064] Batch funda 14 | size=20
2026-03-25 01:44:18 | INFO | Batch funda 15 | size=20
2026-03-25 01:44:18,829 P[19164] [MainThread 20064] Batch funda 15 | size=20
2026-03-25 01:44:20 | INFO | Batch funda 16 | size=20
2026-03-25 01:44:20,604 P[19164] [MainThread 20064] Batch funda 16 | size=20
2026-03-25 01:44:22 | INFO | Batch funda 17 | size=20
2026-03-25 01:44:22,477 P[19164] [MainThread 20064] Batch funda 17 | size=20
2026-03-25 01:44:24 | INFO | Batch funda 18 | size=20
2026-03-25 01:44:24,244 P[19164] [MainThread 20064] Batch funda 18 | size=20
2026-03-25 01:44:25 | INFO | Batch funda 19 | size=20
2026-03-25 01:44:25,935 P[19164] [MainThread 20064] Batch funda 19 | size=20
2026-03-25 01:44:27 | INFO | Batch funda 20 | size=20
2026-03-25 01:44:27,780 P[19164] [MainThread 20064] Batch funda 20 | size=20
2026-03-25 01:44:29 | INFO | Batch funda 21 | size=20
2026-03-25 01:44:29,542 P[19164] [MainThread 20064] Batch funda 21 | size=20
2026-03-25 01:44:31 | INFO | Batch funda 22 | size=20
2026-03-25 01:44:31,363 P[19164] [MainThread 20064] Batch funda 22 | size=20
2026-03-25 01:44:33 | INFO | Batch funda 23 | size=20
2026-03-25 01:44:33,117 P[19164] [MainThread 20064] Batch funda 23 | size=20
2026-03-25 01:44:34 | INFO | Batch funda 24 | size=20
2026-03-25 01:44:34,911 P[19164] [MainThread 20064] Batch funda 24 | size=20
2026-03-25 01:44:36 | INFO | Batch funda 25 | size=20
2026-03-25 01:44:36,582 P[19164] [MainThread 20064] Batch funda 25 | size=20
2026-03-25 01:44:38 | INFO | Batch funda 26 | size=3
2026-03-25 01:44:38,436 P[19164] [MainThread 20064] Batch funda 26 | size=3
2026-03-25 01:44:40 | INFO | Campo revenue usado: Revenue from Business Activities - Total
2026-03-25 01:44:40,711 P[19164] [MainThread 20064] Campo revenue usado: Revenue from Business Activities - Total
2026-03-25 01:44:40 | INFO | Fundamentals revenue | filas=21,741
2026-03-25 01:44:40,728 P[19164] [MainThread 20064] Fundamentals revenue | filas=21,741
2026-03-25 01:44:40 | INFO | Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/raw/gics_industry_group_sales_quarterly_sp500.csv | filas=1,392
2026-03-25 01:44:40,760 P[19164] [MainThread 20064] Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/raw/gics_industry_group_sales_quarterly_sp500.csv | filas=1,392
2026-03-25 01:44:40 | INFO | Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/raw/fundamentals_with_market_share_sp500.csv | filas=21,741
2026-03-25 01:44:40,951 P[19164] [MainThread 20064] Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/raw/fundamentals_with_market_share_sp500.csv | filas=21,741
2026-03-25 01:44:41 | INFO | Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/raw/fundamentals_with_market_share.csv | filas=21,653
2026-03-25 01:44:41,122 P[19164] [MainThread 20064] Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/raw/fundamentals_with_market_share.csv | filas=21,653

=== QA after collapse ===
Duplicados ric-period_end: 0
Shape: (5533, 9)

=== QA funda_monthly ===
Shape: (60952, 9)
NA market_share: 0.0
        date  ric  market_share  industry_sales       revenue  \
0 2014-10-31  A.N      0.333333   12144000000.0  4048000000.0
1 2014-11-30  A.N      0.333333   12144000000.0  4048000000.0
2 2014-12-31  A.N      0.333333   12144000000.0  4048000000.0
3 2015-01-31  A.N      0.333333   12144000000.0  4048000000.0
4 2015-02-28  A.N      0.333333   12144000000.0  4048000000.0

  gics_sector_name                        gics_industry_group_name  \
0      Health Care  Pharmaceuticals, Biotechnology & Life Sciences
1      Health Care  Pharmaceuticals, Biotechnology & Life Sciences
2      Health Care  Pharmaceuticals, Biotechnology & Life Sciences
3      Health Care  Pharmaceuticals, Biotechnology & Life Sciences
4      Health Care  Pharmaceuticals, Biotechnology & Life Sciences

               gics_industry_name           gics_subindustry_name
0  Life Sciences Tools & Services  Life Sciences Tools & Services
1  Life Sciences Tools & Services  Life Sciences Tools & Services
2  Life Sciences Tools & Services  Life Sciences Tools & Services
3  Life Sciences Tools & Services  Life Sciences Tools & Services
4  Life Sciences Tools & Services  Life Sciences Tools & Services

2026-03-25 01:44:44 | INFO | Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/raw/fundamentals_with_market_share_sp500.csv | filas=60,952
2026-03-25 01:44:44,122 P[19164] [MainThread 20064] Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/raw/fundamentals_with_market_share_sp500.csv | filas=60,952
2026-03-25 01:44:44 | INFO | Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/raw/fundamentals_with_market_share.csv | filas=60,698
2026-03-25 01:44:44,789 P[19164] [MainThread 20064] Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/raw/fundamentals_with_market_share.csv | filas=60,698

## 15bis) Proxies alternativas de market power / competencia

**Motivación.** La variable original de `market_share` fue cuestionada metodológicamente porque su denominador utilizaba solo las firmas de la muestra, por lo que medía participación relativa dentro de la submuestra y no poder de mercado en sentido más amplio. :contentReference[oaicite:1]{index=1}

**Objetivo de esta sección.** Construir proxies más defendibles usando un universo más amplio de comparables y una clasificación GICS más fina.

### Proxies a construir

1. **`market_share_industry_group_sp500`**  
   Participación en ventas de la firma dentro de su **GICS Industry Group** usando el universo del S&P 500.  
   - Ventaja: simple, estable y comparable con la versión ya implementada.
   - Limitación: el denominador sigue siendo SP500, no el universo total de competidores.

2. **`market_share_industry_sp500`**  
   Participación en ventas dentro de **GICS Industry**.  
   - Ventaja: aproxima mejor el mercado relevante que el sector o industry group.
   - Uso sugerido: candidata principal para la tesis si la cobertura es razonable.

3. **`market_share_subindustry_sp500`**  
   Participación en ventas dentro de **GICS Sub-Industry**.  
   - Ventaja: mayor cercanía al mercado de producto.
   - Limitación: puede haber grupos con pocos comparables.

4. **`hhi_industry_sp500`** y `hhi_subindustry_sp500`  
   Índices de concentración construidos como suma de shares al cuadrado dentro de cada industry / subindustry y período.
   - Interpretación: estructura competitiva del mercado donde opera la firma.
   - Uso sugerido: robustez o complemento de market share.

5. **`relative_size_industry_sp500`**  
   Tamaño relativo de la firma frente al total o mediana de ventas de su industria.
   - Interpretación: escala relativa más que poder de mercado.
   - Uso sugerido: robustez si el market share fino tiene poca cobertura.

### Criterio empírico sugerido

- **Proxy principal:** `market_share_industry_sp500`
- **Robustez 1:** `market_share_subindustry_sp500`
- **Robustez 2:** `hhi_industry_sp500`
- **Robustez 3:** `relative_size_industry_sp500`

### Outputs

Esta sección exporta:

- `data/raw/market_power_proxies_sp500_quarterly.csv`
- `data/raw/market_power_proxies_focus_quarterly.csv`

El primer archivo contiene el universo SP500 con las proxies construidas; el segundo filtra a la muestra de firmas de la tesis para luego mergearlo en el pipeline del panel mensual.

Chequeos de los datos.

In [37]:
# ======================
# MARKET POWER PROXIES (SP500)
# ======================

import numpy as np
import pandas as pd

# -------------------------------------------------
# 0) Base de trabajo
# -------------------------------------------------
req_cols = [
    "ric", "period_end", "revenue",
    "gics_sector_name", "gics_industry_group_name"
]
missing_req = [c for c in req_cols if c not in funda_all.columns]
if missing_req:
    raise RuntimeError(f"Faltan columnas en funda_all: {missing_req}")

req_cols = [
    "ric", "period_end", "revenue",
    "gics_sector_name", "gics_industry_group_name"
]
missing_req = [c for c in req_cols if c not in funda_all.columns]
if missing_req:
    raise RuntimeError(f"Faltan columnas en funda_all: {missing_req}")

print("\nCobertura columnas GICS finas en funda_all:")
for c in ["gics_industry_name", "gics_subindustry_name"]:
    print(f"{c}: {c in funda_all.columns}")

mp = funda_all.copy()
mp["period_end"] = pd.to_datetime(mp["period_end"], errors="coerce")
mp["revenue"] = pd.to_numeric(mp["revenue"], errors="coerce")
mp = mp.dropna(subset=["ric", "period_end"]).copy()

# -------------------------------------------------
# FIX 1: colapsar duplicados (CRÍTICO)
# -------------------------------------------------
agg_dict = {
    "revenue": "mean",
    "gics_sector_name": "first",
    "gics_industry_group_name": "first",
}

if "gics_industry_name" in mp.columns:
    agg_dict["gics_industry_name"] = "first"

if "gics_subindustry_name" in mp.columns:
    agg_dict["gics_subindustry_name"] = "first"

mp = (
    mp
    .sort_values(["ric", "period_end"])
    .groupby(["ric", "period_end"], as_index=False)
    .agg(agg_dict)
)

print("\n=== QA mp after collapse ===")
print("Duplicados:", mp.duplicated(["ric", "period_end"]).sum())

# Limpieza robusta
for c in [
    "gics_sector_name",
    "gics_industry_group_name",
    "gics_industry_name",
    "gics_subindustry_name"
]:
    if c in mp.columns:
        mp[c] = mp[c].astype("string").str.strip()

mp.loc[mp["revenue"] <= 0, "revenue"] = np.nan

# -------------------------------------------------
# 1) Helper robusto
# -------------------------------------------------
def build_share_hhi(df, group_col, suffix):

    tmp = df[["ric", "period_end", "revenue", group_col]].copy()
    tmp = tmp.dropna(subset=["period_end", group_col])

    tmp_valid = tmp.dropna(subset=["revenue"]).copy()

    grp = (
        tmp_valid
        .groupby([group_col, "period_end"], as_index=False)
        .agg(
            group_sales=("revenue", "sum"),
            group_median_sales=("revenue", "median"),
            n_firms=("ric", "nunique")
        )
    )

    grp = grp[grp["group_sales"] > 0]

    out = tmp.merge(grp, on=[group_col, "period_end"], how="left")

    out[f"market_share_{suffix}"] = out["revenue"] / out["group_sales"]
    out[f"relative_size_{suffix}"] = out["revenue"] / out["group_median_sales"]

    out[f"rank_revenue_{suffix}"] = (
        out.groupby([group_col, "period_end"])["revenue"]
        .rank(method="dense", ascending=False)
    )

    hhi = (
        out.dropna(subset=[f"market_share_{suffix}"])
        .assign(share_sq=lambda x: x[f"market_share_{suffix}"] ** 2)
        .groupby([group_col, "period_end"], as_index=False)["share_sq"]
        .sum()
        .rename(columns={"share_sq": f"hhi_{suffix}"})
    )

    out = out.merge(hhi, on=[group_col, "period_end"], how="left")

    out = out.rename(columns={
        "group_sales": f"group_sales_{suffix}",
        "group_median_sales": f"group_median_sales_{suffix}",
        "n_firms": f"n_firms_{suffix}"
    })

    keep = [
        "ric", "period_end",
        f"group_sales_{suffix}",
        f"group_median_sales_{suffix}",
        f"n_firms_{suffix}",
        f"market_share_{suffix}",
        f"relative_size_{suffix}",
        f"rank_revenue_{suffix}",
        f"hhi_{suffix}",
    ]

    return out[keep].drop_duplicates(subset=["ric", "period_end"])


# -------------------------------------------------
# 2) Construcción proxies (ROBUSTO)
# -------------------------------------------------
logger.info("Construyendo proxies market power ...")

proxies = []

# siempre existe
proxies.append(
    build_share_hhi(mp, "gics_industry_group_name", "industry_group_sp500")
)

# opcionales
if "gics_industry_name" in mp.columns:
    proxies.append(
        build_share_hhi(mp, "gics_industry_name", "industry_sp500")
    )

if "gics_subindustry_name" in mp.columns:
    proxies.append(
        build_share_hhi(mp, "gics_subindustry_name", "subindustry_sp500")
    )

# -------------------------------------------------
# 3) Merge horizontal
# -------------------------------------------------
base_cols = [
    c for c in [
        "ric", "period_end", "revenue",
        "gics_sector_name",
        "gics_industry_group_name",
        "gics_industry_name",
        "gics_subindustry_name"
    ] if c in mp.columns
]

market_power = mp[base_cols].copy()

for piece in proxies:
    market_power = market_power.merge(
        piece,
        on=["ric", "period_end"],
        how="left"
    )

# -------------------------------------------------
# 4) Variables extra
# -------------------------------------------------
market_power["log_revenue"] = np.log(market_power["revenue"])

if "n_firms_subindustry_sp500" in market_power.columns:
    market_power["small_subindustry_group"] = (
        market_power["n_firms_subindustry_sp500"].fillna(0) < 4
    ).astype(int)

if "n_firms_industry_sp500" in market_power.columns:
    market_power["small_industry_group"] = (
        market_power["n_firms_industry_sp500"].fillna(0) < 4
    ).astype(int)

market_power["ric_base"] = market_power["ric"].astype(str).str.split(".").str[0]

# -------------------------------------------------
# 5) Quarterly → Monthly
# -------------------------------------------------
market_power = market_power.sort_values(["ric", "period_end"])

market_power["date"] = market_power["period_end"].dt.to_period("M").dt.to_timestamp("M")

market_power = (
    market_power
    .groupby("ric", group_keys=False)
    .apply(lambda df: df.set_index("date").resample("M").ffill())
    .reset_index()
)

print("\n=== QA market_power monthly ===")
print("NA IG:", market_power["market_share_industry_group_sp500"].isna().mean())

if "market_share_industry_sp500" in market_power.columns:
    print("NA IND:", market_power["market_share_industry_sp500"].isna().mean())

if "market_share_subindustry_sp500" in market_power.columns:
    print("NA SUB:", market_power["market_share_subindustry_sp500"].isna().mean())

# -------------------------------------------------
# 6) Export
# -------------------------------------------------
out_all = OUT.get(
    "market_power_proxies_sp500_q",
    RAW_DIR / "market_power_proxies_sp500_quarterly.csv"
)
market_power.to_csv(out_all, index=False)

market_power_focus = market_power[market_power["ric_base"].isin(target_bases)].copy()

out_focus = OUT.get(
    "market_power_proxies_focus_q",
    RAW_DIR / "market_power_proxies_focus_quarterly.csv"
)
market_power_focus.to_csv(out_focus, index=False)

# -------------------------------------------------
# 7) Coverage
# -------------------------------------------------
summary_cols = [c for c in [
    "market_share_industry_group_sp500",
    "market_share_industry_sp500",
    "market_share_subindustry_sp500",
    "hhi_industry_group_sp500",
    "hhi_industry_sp500",
    "hhi_subindustry_sp500",
] if c in market_power_focus.columns]

coverage = (
    market_power_focus[summary_cols]
    .notna()
    .mean()
    .sort_values(ascending=False)
)

print("\n=== COVERAGE ===")
print(coverage)

2026-03-25 01:45:33 | INFO | Construyendo proxies market power ...
2026-03-25 01:45:33,808 P[19164] [MainThread 20064] Construyendo proxies market power ...

Cobertura columnas GICS finas en funda_all:
gics_industry_name: True
gics_subindustry_name: True

=== QA mp after collapse ===
Duplicados: 0

=== QA market_power monthly ===
NA IG: 0.0
NA IND: 0.0
NA SUB: 0.0

=== COVERAGE ===
market_share_industry_group_sp500    1.0
market_share_industry_sp500          1.0
market_share_subindustry_sp500       1.0
hhi_industry_group_sp500             1.0
hhi_industry_sp500                   1.0
hhi_subindustry_sp500                1.0
dtype: float64

In [38]:
# ==========================================================
# 1) Distribución del número de firmas por grupo (ROBUSTO)
# ==========================================================
cols_n_firms = [
    "n_firms_industry_group_sp500",
    "n_firms_industry_sp500",
    "n_firms_subindustry_sp500"
]

for c in cols_n_firms:
    if c in market_power_focus.columns:
        print("\n", c)
        print(market_power_focus[c].describe())
        print(market_power_focus[c].value_counts().sort_index().head(10))
    else:
        print(f"\n{c} -> NO EXISTE")

# ==========================================================
# 2) Casos donde HHI = 1 (ROBUSTO)
# ==========================================================
cols_hhi = [
    "hhi_industry_group_sp500",
    "hhi_industry_sp500",
    "hhi_subindustry_sp500"
]

for c in cols_hhi:
    if c not in market_power.columns:
        print(f"\n{c} -> NO EXISTE")
        continue

    print(f"\nCasos con {c} = 1")

    cols_show = ["ric", "period_end", c]

    # agregar columnas si existen
    extra_cols = [
        "gics_industry_group_name",
        "gics_industry_name",
        "gics_subindustry_name",
        "n_firms_industry_group_sp500",
        "n_firms_industry_sp500",
        "n_firms_subindustry_sp500"
    ]

    cols_show += [col for col in extra_cols if col in market_power.columns]

    print(market_power.loc[market_power[c] == 1, cols_show].head(20))
    print("Total:", (market_power[c] == 1).sum())

# ==========================================================
# 3) Verificar duplicados ric-period_end
# ==========================================================
dup_check = (
    mp.groupby(["ric", "period_end"])
      .size()
      .reset_index(name="n")
      .query("n > 1")
)

print("\nDuplicados ric-period_end:", len(dup_check))
print(dup_check.head(20))

 n_firms_industry_group_sp500
count    60698.000000
mean        16.726202
std         13.134976
min          1.000000
25%          3.000000
50%         14.000000
75%         28.000000
max         45.000000
Name: n_firms_industry_group_sp500, dtype: float64
n_firms_industry_group_sp500
1     9193
2     4541
3     2356
4     3148
5      420
6     1890
7      511
8       96
9      108
10     970
Name: count, dtype: int64

 n_firms_industry_sp500
count    60698.000000
mean         7.740848
std          6.835468
min          1.000000
25%          2.000000
50%          5.000000
75%         12.000000
max         23.000000
Name: n_firms_industry_sp500, dtype: float64
n_firms_industry_sp500
1     12663
2      5904
3      4899
4      4848
5      2230
6      2544
7      3232
8      1420
9      1877
10     2540
Name: count, dtype: int64

 n_firms_subindustry_sp500
count    60698.000000
mean         4.497117
std          3.832876
min          1.000000
25%          1.000000
50%          3.000000
75%          7.000000
max         17.000000
Name: n_firms_subindustry_sp500, dtype: float64
n_firms_subindustry_sp500
1     16282
2      9044
3      7875
4      4016
5      4540
6      3126
7      3297
8      2912
9      1854
10     3620
Name: count, dtype: int64

Casos con hhi_industry_group_sp500 = 1
    ric period_end  hhi_industry_group_sp500  \
0   A.N 2014-10-31                       1.0
1   A.N 2014-10-31                       1.0
2   A.N 2014-10-31                       1.0
3   A.N 2014-10-31                       1.0
4   A.N 2014-10-31                       1.0
5   A.N 2014-10-31                       1.0
6   A.N 2014-10-31                       1.0
7   A.N 2014-10-31                       1.0
8   A.N 2014-10-31                       1.0
9   A.N 2014-10-31                       1.0
10  A.N 2014-10-31                       1.0
11  A.N 2014-10-31                       1.0
12  A.N 2015-10-31                       1.0
13  A.N 2015-10-31                       1.0
14  A.N 2015-10-31                       1.0
15  A.N 2015-10-31                       1.0
16  A.N 2015-10-31                       1.0
17  A.N 2015-10-31                       1.0
18  A.N 2015-10-31                       1.0
19  A.N 2015-10-31                       1.0

                          gics_industry_group_name  \
0   Pharmaceuticals, Biotechnology & Life Sciences
1   Pharmaceuticals, Biotechnology & Life Sciences
2   Pharmaceuticals, Biotechnology & Life Sciences
3   Pharmaceuticals, Biotechnology & Life Sciences
4   Pharmaceuticals, Biotechnology & Life Sciences
5   Pharmaceuticals, Biotechnology & Life Sciences
6   Pharmaceuticals, Biotechnology & Life Sciences
7   Pharmaceuticals, Biotechnology & Life Sciences
8   Pharmaceuticals, Biotechnology & Life Sciences
9   Pharmaceuticals, Biotechnology & Life Sciences
10  Pharmaceuticals, Biotechnology & Life Sciences
11  Pharmaceuticals, Biotechnology & Life Sciences
12  Pharmaceuticals, Biotechnology & Life Sciences
13  Pharmaceuticals, Biotechnology & Life Sciences
14  Pharmaceuticals, Biotechnology & Life Sciences
15  Pharmaceuticals, Biotechnology & Life Sciences
16  Pharmaceuticals, Biotechnology & Life Sciences
17  Pharmaceuticals, Biotechnology & Life Sciences
18  Pharmaceuticals, Biotechnology & Life Sciences
19  Pharmaceuticals, Biotechnology & Life Sciences

                gics_industry_name           gics_subindustry_name  \
0   Life Sciences Tools & Services  Life Sciences Tools & Services
1   Life Sciences Tools & Services  Life Sciences Tools & Services
2   Life Sciences Tools & Services  Life Sciences Tools & Services
3   Life Sciences Tools & Services  Life Sciences Tools & Services
4   Life Sciences Tools & Services  Life Sciences Tools & Services
5   Life Sciences Tools & Services  Life Sciences Tools & Services
6   Life Sciences Tools & Services  Life Sciences Tools & Services
7   Life Sciences Tools & Services  Life Sciences Tools & Services
8   Life Sciences Tools & Services  Life Sciences Tools & Services
9   Life Sciences Tools & Services  Life Sciences Tools & Services
10  Life Sciences Tools & Services  Life Sciences Tools & Services
11  Life Sciences Tools & Services  Life Sciences Tools & Services
12  Life Sciences Tools & Services  Life Sciences Tools & Services
13  Life Sciences Tools & Services  Life Sciences Tools & Services
14  Life Sciences Tools & Services  Life Sciences Tools & Services
15  Life Sciences Tools & Services  Life Sciences Tools & Services
16  Life Sciences Tools & Services  Life Sciences Tools & Services
17  Life Sciences Tools & Services  Life Sciences Tools & Services
18  Life Sciences Tools & Services  Life Sciences Tools & Services
19  Life Sciences Tools & Services  Life Sciences Tools & Services

    n_firms_industry_group_sp500  n_firms_industry_sp500  \
0                              1                       1
1                              1                       1
2                              1                       1
3                              1                       1
4                              1                       1
5                              1                       1
6                              1                       1
7                              1                       1
8                              1                       1
9                              1                       1
10                             1                       1
11                             1                       1
12                             1                       1
13                             1                       1
14                             1                       1
15                             1                       1
16                             1                       1
17                             1                       1
18                             1                       1
19                             1                       1

    n_firms_subindustry_sp500
0                           1
1                           1
2                           1
3                           1
4                           1
5                           1
6                           1
7                           1
8                           1
9                           1
10                          1
11                          1
12                          1
13                          1
14                          1
15                          1
16                          1
17                          1
18                          1
19                          1
Total: 9193

Casos con hhi_industry_sp500 = 1
    ric period_end  hhi_industry_sp500  \
0   A.N 2014-10-31                 1.0
1   A.N 2014-10-31                 1.0
2   A.N 2014-10-31                 1.0
3   A.N 2014-10-31                 1.0
4   A.N 2014-10-31                 1.0
5   A.N 2014-10-31                 1.0
6   A.N 2014-10-31                 1.0
7   A.N 2014-10-31                 1.0
8   A.N 2014-10-31                 1.0
9   A.N 2014-10-31                 1.0
10  A.N 2014-10-31                 1.0
11  A.N 2014-10-31                 1.0
12  A.N 2015-10-31                 1.0
13  A.N 2015-10-31                 1.0
14  A.N 2015-10-31                 1.0
15  A.N 2015-10-31                 1.0
16  A.N 2015-10-31                 1.0
17  A.N 2015-10-31                 1.0
18  A.N 2015-10-31                 1.0
19  A.N 2015-10-31                 1.0

                          gics_industry_group_name  \
0   Pharmaceuticals, Biotechnology & Life Sciences
1   Pharmaceuticals, Biotechnology & Life Sciences
2   Pharmaceuticals, Biotechnology & Life Sciences
3   Pharmaceuticals, Biotechnology & Life Sciences
4   Pharmaceuticals, Biotechnology & Life Sciences
5   Pharmaceuticals, Biotechnology & Life Sciences
6   Pharmaceuticals, Biotechnology & Life Sciences
7   Pharmaceuticals, Biotechnology & Life Sciences
8   Pharmaceuticals, Biotechnology & Life Sciences
9   Pharmaceuticals, Biotechnology & Life Sciences
10  Pharmaceuticals, Biotechnology & Life Sciences
11  Pharmaceuticals, Biotechnology & Life Sciences
12  Pharmaceuticals, Biotechnology & Life Sciences
13  Pharmaceuticals, Biotechnology & Life Sciences
14  Pharmaceuticals, Biotechnology & Life Sciences
15  Pharmaceuticals, Biotechnology & Life Sciences
16  Pharmaceuticals, Biotechnology & Life Sciences
17  Pharmaceuticals, Biotechnology & Life Sciences
18  Pharmaceuticals, Biotechnology & Life Sciences
19  Pharmaceuticals, Biotechnology & Life Sciences

                gics_industry_name           gics_subindustry_name  \
0   Life Sciences Tools & Services  Life Sciences Tools & Services
1   Life Sciences Tools & Services  Life Sciences Tools & Services
2   Life Sciences Tools & Services  Life Sciences Tools & Services
3   Life Sciences Tools & Services  Life Sciences Tools & Services
4   Life Sciences Tools & Services  Life Sciences Tools & Services
5   Life Sciences Tools & Services  Life Sciences Tools & Services
6   Life Sciences Tools & Services  Life Sciences Tools & Services
7   Life Sciences Tools & Services  Life Sciences Tools & Services
8   Life Sciences Tools & Services  Life Sciences Tools & Services
9   Life Sciences Tools & Services  Life Sciences Tools & Services
10  Life Sciences Tools & Services  Life Sciences Tools & Services
11  Life Sciences Tools & Services  Life Sciences Tools & Services
12  Life Sciences Tools & Services  Life Sciences Tools & Services
13  Life Sciences Tools & Services  Life Sciences Tools & Services
14  Life Sciences Tools & Services  Life Sciences Tools & Services
15  Life Sciences Tools & Services  Life Sciences Tools & Services
16  Life Sciences Tools & Services  Life Sciences Tools & Services
17  Life Sciences Tools & Services  Life Sciences Tools & Services
18  Life Sciences Tools & Services  Life Sciences Tools & Services
19  Life Sciences Tools & Services  Life Sciences Tools & Services

    n_firms_industry_group_sp500  n_firms_industry_sp500  \
0                              1                       1
1                              1                       1
2                              1                       1
3                              1                       1
4                              1                       1
5                              1                       1
6                              1                       1
7                              1                       1
8                              1                       1
9                              1                       1
10                             1                       1
11                             1                       1
12                             1                       1
13                             1                       1
14                             1                       1
15                             1                       1
16                             1                       1
17                             1                       1
18                             1                       1
19                             1                       1

    n_firms_subindustry_sp500
0                           1
1                           1
2                           1
3                           1
4                           1
5                           1
6                           1
7                           1
8                           1
9                           1
10                          1
11                          1
12                          1
13                          1
14                          1
15                          1
16                          1
17                          1
18                          1
19                          1
Total: 12796

Casos con hhi_subindustry_sp500 = 1
    ric period_end  hhi_subindustry_sp500  \
0   A.N 2014-10-31                    1.0
1   A.N 2014-10-31                    1.0
2   A.N 2014-10-31                    1.0
3   A.N 2014-10-31                    1.0
4   A.N 2014-10-31                    1.0
5   A.N 2014-10-31                    1.0
6   A.N 2014-10-31                    1.0
7   A.N 2014-10-31                    1.0
8   A.N 2014-10-31                    1.0
9   A.N 2014-10-31                    1.0
10  A.N 2014-10-31                    1.0
11  A.N 2014-10-31                    1.0
12  A.N 2015-10-31                    1.0
13  A.N 2015-10-31                    1.0
14  A.N 2015-10-31                    1.0
15  A.N 2015-10-31                    1.0
16  A.N 2015-10-31                    1.0
17  A.N 2015-10-31                    1.0
18  A.N 2015-10-31                    1.0
19  A.N 2015-10-31                    1.0

                          gics_industry_group_name  \
0   Pharmaceuticals, Biotechnology & Life Sciences
1   Pharmaceuticals, Biotechnology & Life Sciences
2   Pharmaceuticals, Biotechnology & Life Sciences
3   Pharmaceuticals, Biotechnology & Life Sciences
4   Pharmaceuticals, Biotechnology & Life Sciences
5   Pharmaceuticals, Biotechnology & Life Sciences
6   Pharmaceuticals, Biotechnology & Life Sciences
7   Pharmaceuticals, Biotechnology & Life Sciences
8   Pharmaceuticals, Biotechnology & Life Sciences
9   Pharmaceuticals, Biotechnology & Life Sciences
10  Pharmaceuticals, Biotechnology & Life Sciences
11  Pharmaceuticals, Biotechnology & Life Sciences
12  Pharmaceuticals, Biotechnology & Life Sciences
13  Pharmaceuticals, Biotechnology & Life Sciences
14  Pharmaceuticals, Biotechnology & Life Sciences
15  Pharmaceuticals, Biotechnology & Life Sciences
16  Pharmaceuticals, Biotechnology & Life Sciences
17  Pharmaceuticals, Biotechnology & Life Sciences
18  Pharmaceuticals, Biotechnology & Life Sciences
19  Pharmaceuticals, Biotechnology & Life Sciences

                gics_industry_name           gics_subindustry_name  \
0   Life Sciences Tools & Services  Life Sciences Tools & Services
1   Life Sciences Tools & Services  Life Sciences Tools & Services
2   Life Sciences Tools & Services  Life Sciences Tools & Services
3   Life Sciences Tools & Services  Life Sciences Tools & Services
4   Life Sciences Tools & Services  Life Sciences Tools & Services
5   Life Sciences Tools & Services  Life Sciences Tools & Services
6   Life Sciences Tools & Services  Life Sciences Tools & Services
7   Life Sciences Tools & Services  Life Sciences Tools & Services
8   Life Sciences Tools & Services  Life Sciences Tools & Services
9   Life Sciences Tools & Services  Life Sciences Tools & Services
10  Life Sciences Tools & Services  Life Sciences Tools & Services
11  Life Sciences Tools & Services  Life Sciences Tools & Services
12  Life Sciences Tools & Services  Life Sciences Tools & Services
13  Life Sciences Tools & Services  Life Sciences Tools & Services
14  Life Sciences Tools & Services  Life Sciences Tools & Services
15  Life Sciences Tools & Services  Life Sciences Tools & Services
16  Life Sciences Tools & Services  Life Sciences Tools & Services
17  Life Sciences Tools & Services  Life Sciences Tools & Services
18  Life Sciences Tools & Services  Life Sciences Tools & Services
19  Life Sciences Tools & Services  Life Sciences Tools & Services

    n_firms_industry_group_sp500  n_firms_industry_sp500  \
0                              1                       1
1                              1                       1
2                              1                       1
3                              1                       1
4                              1                       1
5                              1                       1
6                              1                       1
7                              1                       1
8                              1                       1
9                              1                       1
10                             1                       1
11                             1                       1
12                             1                       1
13                             1                       1
14                             1                       1
15                             1                       1
16                             1                       1
17                             1                       1
18                             1                       1
19                             1                       1

    n_firms_subindustry_sp500
0                           1
1                           1
2                           1
3                           1
4                           1
5                           1
6                           1
7                           1
8                           1
9                           1
10                          1
11                          1
12                          1
13                          1
14                          1
15                          1
16                          1
17                          1
18                          1
19                          1
Total: 16536

Duplicados ric-period_end: 0
Empty DataFrame
Columns: [ric, period_end, n]
Index: []

## 16) Controles macroeconómicos agregados — descarga y construcción mensual

**Objetivo:** incorporar un set parsimonioso de controles macro para los modelos sin efectos fijos de tiempo, de modo de evaluar si los coeficientes de los shocks agregados de mercado y crédito son robustos a otras condiciones macrofinancieras comunes.

### Criterio de selección

Se priorizan controles con interpretación económica clara y bajo solapamiento con los factores ya incluidos en la tesis.

**Set mínimo sugerido para regresiones:**
- `policy_rate`: tasa de política monetaria de la Fed (o proxy de corto plazo si la serie directa no está disponible).
- `term_spread_10y_2y`: pendiente de la curva del Tesoro.
- `indpro_yoy`: actividad económica agregada.

**Set ampliado de robustez:**
- `cpi_yoy`: inflación interanual.
- `vix_eom`: incertidumbre / aversión al riesgo agregada.
- `move_eom`: volatilidad implícita del mercado de Treasuries.

### Notas metodológicas

- La pendiente del Tesoro se construye a partir de la curva UST ya descargada en la etapa anterior.
- Para la tasa de política se intenta primero una serie macro directa; si no hay cobertura por permisos o por RIC, se construye una **proxy** con la tasa UST de 3 meses.
- Las series diarias se agregan a frecuencia mensual usando **último dato disponible de cada mes**.
- Las series macro mensuales se guardan ya listas para merge con el panel firma–mes.

### Outputs

- `data/raw/macro_controls_daily.parquet`
- `data/clean/macro_controls_monthly.parquet`
- `data/clean/macro_controls_sources.csv`

### Observación importante

Los RICs de algunas series macroeconómicas en Refinitiv pueden variar según permisos, Workspace o convención del monitor económico. Por eso la celda prueba varios candidatos por variable y registra cuál funcionó. Si una serie no baja, normalmente alcanza con reemplazar la lista de candidatos de esa variable por el RIC correcto encontrado en Workspace.

In [39]:
# ======================
# CONTROLES MACRO -> descarga + construcción mensual
# ======================

# Requiere:
# - START_DATE, END_DATE
# - RAW_DIR, CLEAN_DIR, OUT
# - logger, sleep_request
# - get_ts_safe(...) de la celda de UST
# - ust_yield_curve_daily.parquet ya generado

from typing import Optional

# -------------------------------------------------
# 1) Configuración
# -------------------------------------------------

# Variables seleccionadas:
# - baseline: policy_rate, term_spread_10y_2y, indpro_yoy
# - robustez: cpi_yoy, vix_eom, move_eom
#
# Nota:
# - TED spread NO se incluye acá porque su construcción homogénea hasta 2025
#   es menos limpia por el quiebre de LIBOR. Si después querés, lo armamos
#   como robustness separado.

# Candidatos de RIC por variable.
# IMPORTANTE:
# Los RICs macro pueden variar según permisos / Workspace.
# Si una serie no baja, buscá el RIC en Workspace y reemplazá esta lista.
MACRO_RIC_CANDIDATES = {
    # incertidumbre / robustez
    "vix": [
        ".VIX",
        "VIX"
    ],
    "move": [
        ".MOVE",
        "MOVE"
    ],

    # política monetaria (si no funciona ninguno, se usa proxy UST 3M)
    "policy_rate": [
        "USFFTARGET=",      # candidato 1
        "USFEDFUNDS=",      # candidato 2
        "FEDFUNDS"          # candidato 3
    ],

    # inflación interanual (mensual)
    "cpi_yoy": [
        "USCPIY=ECI",       # candidato 1
        "aUSCPIY",          # candidato 2
        "USCPNY=ECI"        # candidato 3
    ],

    # actividad real (mensual)
    "indpro_yoy": [
        "USIPY=ECI",        # candidato 1
        "aUSIPY",           # candidato 2
        "USIP=ECI"          # candidato 3 (si devuelve índice nivel, se transforma)
    ],
}

# frecuencia deseada por variable descargada directamente
MACRO_FREQ = {
    "vix": "daily",
    "move": "daily",
    "policy_rate": "monthly",
    "cpi_yoy": "monthly",
    "indpro_yoy": "monthly",
}

# -------------------------------------------------
# 2) Helpers
# -------------------------------------------------

def normalize_ts_output(ts: pd.DataFrame, var_name: str, ric_used: str) -> pd.DataFrame:
    """
    Normaliza la salida de ek.get_timeseries a columnas:
    date, value, variable, ric
    """
    if ts is None or ts.empty:
        return pd.DataFrame(columns=["date", "value", "variable", "ric"])

    df = ts.reset_index().copy()

    # detectar columna fecha
    date_col = None
    for c in df.columns:
        if str(c).lower() in {"date", "index"}:
            date_col = c
            break
    if date_col is None:
        date_col = df.columns[0]

    # detectar columna valor
    preferred = ["CLOSE", "VALUE", "OPEN", "HIGH", "LOW"]
    value_col = None
    for c in preferred:
        if c in df.columns:
            value_col = c
            break

    if value_col is None:
        # primer numérico disponible distinto de date
        candidates = [c for c in df.columns if c != date_col]
        if not candidates:
            return pd.DataFrame(columns=["date", "value", "variable", "ric"])
        value_col = candidates[0]

    out = df[[date_col, value_col]].rename(columns={date_col: "date", value_col: "value"}).copy()
    out["date"] = pd.to_datetime(out["date"], errors="coerce")
    if getattr(out["date"].dt, "tz", None) is not None:
        out["date"] = out["date"].dt.tz_localize(None)

    out["value"] = pd.to_numeric(out["value"], errors="coerce")
    out["variable"] = var_name
    out["ric"] = ric_used

    out = out.dropna(subset=["date"]).sort_values("date").reset_index(drop=True)
    return out


def fetch_first_valid_series(
    var_name: str,
    candidates: list[str],
    start_date: str,
    end_date: str,
    interval: str,
    max_attempts: int = 3,
) -> tuple[pd.DataFrame, Optional[str]]:
    """
    Prueba varios RICs y devuelve la primera serie válida.
    """
    for ric in candidates:
        logger.info(f"[macro] {var_name} -> probando {ric} ({interval})")
        try:
            ts = ek.get_timeseries(
                ric,
                fields=["CLOSE"],
                start_date=start_date,
                end_date=end_date,
                interval=interval,
            )
            df = normalize_ts_output(ts, var_name=var_name, ric_used=ric)
            if not df.empty and df["value"].notna().sum() > 0:
                logger.info(f"[macro] OK {var_name} con {ric} | filas={len(df):,}")
                return df, ric

        except Exception as e:
            msg = str(e)
            if "429" in msg or "Too many requests" in msg:
                wait_sec = 4
                logger.warning(f"[macro] 429 para {var_name}/{ric} | espero {wait_sec}s")
                time.sleep(wait_sec)
                continue
            logger.warning(f"[macro] error {var_name}/{ric}: {type(e).__name__}: {e}")

        sleep_request(0.4)

    logger.warning(f"[macro] sin cobertura para {var_name}")
    return pd.DataFrame(columns=["date", "value", "variable", "ric"]), None


def monthly_last(df: pd.DataFrame, date_col: str, value_col: str, out_name: str) -> pd.DataFrame:
    """
    Último dato disponible de cada mes.
    """
    x = df[[date_col, value_col]].copy()
    x[date_col] = pd.to_datetime(x[date_col], errors="coerce")
    x = x.dropna(subset=[date_col]).sort_values(date_col)
    x["date"] = x[date_col].dt.to_period("M").dt.to_timestamp("M")
    x = x.groupby("date", as_index=False)[value_col].last()
    x = x.rename(columns={value_col: out_name})
    return x


def monthly_mean(df: pd.DataFrame, date_col: str, value_col: str, out_name: str) -> pd.DataFrame:
    """
    Promedio mensual.
    """
    x = df[[date_col, value_col]].copy()
    x[date_col] = pd.to_datetime(x[date_col], errors="coerce")
    x = x.dropna(subset=[date_col]).sort_values(date_col)
    x["date"] = x[date_col].dt.to_period("M").dt.to_timestamp("M")
    x = x.groupby("date", as_index=False)[value_col].mean()
    x = x.rename(columns={value_col: out_name})
    return x


# -------------------------------------------------
# 3) Descargar series macro directas
# -------------------------------------------------

logger.info("Descargando controles macro directos...")

macro_long = []
macro_sources = []

for var_name, ric_list in MACRO_RIC_CANDIDATES.items():
    interval = MACRO_FREQ[var_name]
    df_var, ric_used = fetch_first_valid_series(
        var_name=var_name,
        candidates=ric_list,
        start_date=START_DATE,
        end_date=END_DATE,
        interval=interval,
        max_attempts=RETRY_MAX,
    )

    if not df_var.empty:
        macro_long.append(df_var)

    macro_sources.append({
        "variable": var_name,
        "ric_used": ric_used,
        "download_status": "ok" if ric_used is not None else "missing",
        "frequency_requested": interval,
    })

    sleep_request(0.5)

macro_sources = pd.DataFrame(macro_sources)

if macro_long:
    macro_raw = pd.concat(macro_long, ignore_index=True)
else:
    macro_raw = pd.DataFrame(columns=["date", "value", "variable", "ric"])

# Export raw
raw_macro_parquet = OUT.get("macro_controls_daily", RAW_DIR / "macro_controls_daily.parquet")
raw_macro_csv = raw_macro_parquet.with_suffix(".csv")

safe_write_parquet(macro_raw, raw_macro_parquet, index=False)
macro_raw.to_csv(raw_macro_csv, index=False)
logger.info(f"Output raw macro -> {raw_macro_csv.as_posix()}")

# -------------------------------------------------
# 4) Construir UST monthly + policy proxy + term spread
# -------------------------------------------------

ust_path = OUT.get("ust_yield_curve_daily", RAW_DIR / "ust_yield_curve_daily.parquet")
if not ust_path.exists():
    raise RuntimeError(
        "No existe ust_yield_curve_daily.parquet. "
        "Primero corré la celda de curva UST."
    )

ust = pd.read_parquet(ust_path).copy()
ust["date"] = pd.to_datetime(ust["date"], errors="coerce")

# último dato disponible por mes y tenor
ust_m = (
    ust.dropna(subset=["date", "tenor", "yield"])
       .sort_values(["tenor", "date"])
       .assign(date=lambda x: x["date"].dt.to_period("M").dt.to_timestamp("M"))
       .groupby(["date", "tenor"], as_index=False)["yield"].last()
       .pivot(index="date", columns="tenor", values="yield")
       .reset_index()
)

# normalizar nombres
ust_m = ust_m.rename(columns={
    "US3M": "ust_3m",
    "US2Y": "ust_2y",
    "US10Y": "ust_10y",
})

# spreads risk-free
if {"ust_10y", "ust_2y"}.issubset(ust_m.columns):
    ust_m["term_spread_10y_2y"] = ust_m["ust_10y"] - ust_m["ust_2y"]

if {"ust_10y", "ust_3m"}.issubset(ust_m.columns):
    ust_m["term_spread_10y_3m"] = ust_m["ust_10y"] - ust_m["ust_3m"]

# -------------------------------------------------
# 5) Pasar series directas a monthly
# -------------------------------------------------

monthly_parts = [ust_m[["date"] + [c for c in ust_m.columns if c != "date"]].copy()]

if not macro_raw.empty:
    # VIX -> último del mes
    if (macro_raw["variable"] == "vix").any():
        vix_m = monthly_last(
            macro_raw.loc[macro_raw["variable"] == "vix"],
            date_col="date",
            value_col="value",
            out_name="vix_eom",
        )
        monthly_parts.append(vix_m)

    # MOVE -> último del mes
    if (macro_raw["variable"] == "move").any():
        move_m = monthly_last(
            macro_raw.loc[macro_raw["variable"] == "move"],
            date_col="date",
            value_col="value",
            out_name="move_eom",
        )
        monthly_parts.append(move_m)

    # policy rate directo (mensual)
    if (macro_raw["variable"] == "policy_rate").any():
        pol_m = monthly_last(
            macro_raw.loc[macro_raw["variable"] == "policy_rate"],
            date_col="date",
            value_col="value",
            out_name="policy_rate",
        )
        monthly_parts.append(pol_m)

    # CPI YoY (mensual)
    if (macro_raw["variable"] == "cpi_yoy").any():
        cpi_m = monthly_last(
            macro_raw.loc[macro_raw["variable"] == "cpi_yoy"],
            date_col="date",
            value_col="value",
            out_name="cpi_yoy",
        )
        monthly_parts.append(cpi_m)

    # INDPRO YoY (mensual)
    if (macro_raw["variable"] == "indpro_yoy").any():
        ip_m = monthly_last(
            macro_raw.loc[macro_raw["variable"] == "indpro_yoy"],
            date_col="date",
            value_col="value",
            out_name="indpro_yoy",
        )
        monthly_parts.append(ip_m)

# merge outer sobre date
macro_monthly = None
for part in monthly_parts:
    if macro_monthly is None:
        macro_monthly = part.copy()
    else:
        macro_monthly = macro_monthly.merge(part, on="date", how="outer")

macro_monthly = macro_monthly.sort_values("date").reset_index(drop=True)

# -------------------------------------------------
# 6) Fallback para tasa de política
# -------------------------------------------------

# Si no se pudo bajar una serie directa de policy_rate, usar proxy UST 3M.
if "policy_rate" not in macro_monthly.columns or macro_monthly["policy_rate"].notna().sum() == 0:
    if "ust_3m" in macro_monthly.columns:
        macro_monthly["policy_rate"] = macro_monthly["ust_3m"]
        macro_sources = pd.concat([
            macro_sources,
            pd.DataFrame([{
                "variable": "policy_rate_fallback",
                "ric_used": "UST_3M_proxy_from_ust_yield_curve_daily",
                "download_status": "constructed_proxy",
                "frequency_requested": "monthly"
            }])
        ], ignore_index=True)
        logger.warning("policy_rate directo no disponible -> se usa proxy 'ust_3m'.")
    else:
        logger.warning("No hay policy_rate directo ni proxy ust_3m disponible.")

# -------------------------------------------------
# 7) Si INDPRO vino en nivel, transformar a YoY
# -------------------------------------------------

# Si por permisos el candidato de indpro devuelve nivel y no tasa YoY,
# transformarlo automáticamente.
if "indpro_yoy" in macro_monthly.columns:
    # heurística simple: si los valores parecen índice nivel (> 50 de forma persistente),
    # convertir a variación interanual.
    s = pd.to_numeric(macro_monthly["indpro_yoy"], errors="coerce")
    if s.notna().sum() >= 24 and s.median() > 20:
        macro_monthly = macro_monthly.sort_values("date").reset_index(drop=True)
        macro_monthly["indpro_yoy"] = 100 * (macro_monthly["indpro_yoy"] / macro_monthly["indpro_yoy"].shift(12) - 1)
        logger.info("indpro_yoy fue transformada desde índice nivel a variación interanual (%).")

# -------------------------------------------------
# 8) Rango final y columnas sugeridas
# -------------------------------------------------

macro_monthly = macro_monthly[
    (macro_monthly["date"] >= pd.to_datetime(START_DATE))
    & (macro_monthly["date"] <= pd.to_datetime(END_DATE))
].copy()

preferred_order = [
    "date",
    # baseline
    "policy_rate",
    "term_spread_10y_2y",
    "indpro_yoy",
    # robustness
    "cpi_yoy",
    "vix_eom",
    "move_eom",
    # auxiliares / QA
    "ust_3m",
    "ust_2y",
    "ust_10y",
    "term_spread_10y_3m",
]

existing_cols = [c for c in preferred_order if c in macro_monthly.columns]
other_cols = [c for c in macro_monthly.columns if c not in existing_cols]
macro_monthly = macro_monthly[existing_cols + other_cols]

# -------------------------------------------------
# 9) Export
# -------------------------------------------------

out_parquet = OUT.get("macro_controls_monthly", CLEAN_DIR / "macro_controls_monthly.parquet")
out_csv = out_parquet.with_suffix(".csv")
src_csv = CLEAN_DIR / "macro_controls_sources.csv"

safe_write_parquet(macro_monthly, out_parquet, index=False)
macro_monthly.to_csv(out_csv, index=False)
macro_sources.to_csv(src_csv, index=False)

logger.info(f"Output monthly macro -> {out_csv.as_posix()}")
logger.info(f"Output sources      -> {src_csv.as_posix()}")

# -------------------------------------------------
# 10) Resumen
# -------------------------------------------------

print("\n=== RESUMEN CONTROLES MACRO ===")
print("Columnas disponibles:")
print(macro_monthly.columns.tolist())

print("\nCobertura no nula por variable:")
print(macro_monthly.notna().sum().sort_values(ascending=False))

print("\nPrimeras filas:")
display(macro_monthly.head())

print("\nFuentes / RICs usados:")
display(macro_sources)

2026-03-25 01:45:53 | INFO | Descargando controles macro directos...
2026-03-25 01:45:53,340 P[19164] [MainThread 20064] Descargando controles macro directos...
2026-03-25 01:45:53 | INFO | [macro] vix -> probando .VIX (daily)
2026-03-25 01:45:53,343 P[19164] [MainThread 20064] [macro] vix -> probando .VIX (daily)
2026-03-25 01:45:53,684 P[19164] [MainThread 20064] Error with .VIX: The user does not have permission for the requested data
2026-03-25 01:45:53,685 P[19164] [MainThread 20064] .VIX: The user does not have permission for the requested data |
2026-03-25 01:45:53 | WARNING | [macro] error vix/.VIX: EikonError: Error code -1 | .VIX: The user does not have permission for the requested data |
2026-03-25 01:45:53,685 P[19164] [MainThread 20064] [macro] error vix/.VIX: EikonError: Error code -1 | .VIX: The user does not have permission for the requested data |
2026-03-25 01:45:54 | INFO | [macro] vix -> probando VIX (daily)
2026-03-25 01:45:54,088 P[19164] [MainThread 20064] [macro] vix -> probando VIX (daily)
2026-03-25 01:45:54,485 P[19164] [MainThread 20064] Error with VIX: Invalid RIC
2026-03-25 01:45:54,485 P[19164] [MainThread 20064] VIX: Invalid RIC |
2026-03-25 01:45:54 | WARNING | [macro] error vix/VIX: EikonError: Error code -1 | VIX: Invalid RIC |
2026-03-25 01:45:54,486 P[19164] [MainThread 20064] [macro] error vix/VIX: EikonError: Error code -1 | VIX: Invalid RIC |
2026-03-25 01:45:54 | WARNING | [macro] sin cobertura para vix
2026-03-25 01:45:54,889 P[19164] [MainThread 20064] [macro] sin cobertura para vix
2026-03-25 01:45:55 | INFO | [macro] move -> probando .MOVE (daily)
2026-03-25 01:45:55,391 P[19164] [MainThread 20064] [macro] move -> probando .MOVE (daily)
2026-03-25 01:45:56 | INFO | [macro] OK move con .MOVE | filas=2,731
2026-03-25 01:45:56,116 P[19164] [MainThread 20064] [macro] OK move con .MOVE | filas=2,731
2026-03-25 01:45:56 | INFO | [macro] policy_rate -> probando USFFTARGET= (monthly)
2026-03-25 01:45:56,618 P[19164] [MainThread 20064] [macro] policy_rate -> probando USFFTARGET= (monthly)
2026-03-25 01:45:57 | INFO | [macro] OK policy_rate con USFFTARGET= | filas=132
2026-03-25 01:45:57,168 P[19164] [MainThread 20064] [macro] OK policy_rate con USFFTARGET= | filas=132
2026-03-25 01:45:57 | INFO | [macro] cpi_yoy -> probando USCPIY=ECI (monthly)
2026-03-25 01:45:57,670 P[19164] [MainThread 20064] [macro] cpi_yoy -> probando USCPIY=ECI (monthly)
2026-03-25 01:45:58,434 P[19164] [MainThread 20064] Error with USCPIY=ECI: TimeSeries request failed
2026-03-25 01:45:58,435 P[19164] [MainThread 20064] USCPIY=ECI: TimeSeries request failed |
2026-03-25 01:45:58 | WARNING | [macro] error cpi_yoy/USCPIY=ECI: EikonError: Error code -1 | USCPIY=ECI: TimeSeries request failed |
2026-03-25 01:45:58,436 P[19164] [MainThread 20064] [macro] error cpi_yoy/USCPIY=ECI: EikonError: Error code -1 | USCPIY=ECI: TimeSeries request failed |
2026-03-25 01:45:58 | INFO | [macro] cpi_yoy -> probando aUSCPIY (monthly)
2026-03-25 01:45:58,839 P[19164] [MainThread 20064] [macro] cpi_yoy -> probando aUSCPIY (monthly)
2026-03-25 01:45:59,674 P[19164] [MainThread 20064] Error with aUSCPIY: TimeSeries request failed
2026-03-25 01:45:59,675 P[19164] [MainThread 20064] aUSCPIY: TimeSeries request failed |
2026-03-25 01:45:59 | WARNING | [macro] error cpi_yoy/aUSCPIY: EikonError: Error code -1 | aUSCPIY: TimeSeries request failed |
2026-03-25 01:45:59,676 P[19164] [MainThread 20064] [macro] error cpi_yoy/aUSCPIY: EikonError: Error code -1 | aUSCPIY: TimeSeries request failed |
2026-03-25 01:46:00 | INFO | [macro] cpi_yoy -> probando USCPNY=ECI (monthly)
2026-03-25 01:46:00,079 P[19164] [MainThread 20064] [macro] cpi_yoy -> probando USCPNY=ECI (monthly)
2026-03-25 01:46:01 | WARNING | [macro] sin cobertura para cpi_yoy
2026-03-25 01:46:01,424 P[19164] [MainThread 20064] [macro] sin cobertura para cpi_yoy
2026-03-25 01:46:01 | INFO | [macro] indpro_yoy -> probando USIPY=ECI (monthly)
2026-03-25 01:46:01,927 P[19164] [MainThread 20064] [macro] indpro_yoy -> probando USIPY=ECI (monthly)
2026-03-25 01:46:03 | INFO | [macro] indpro_yoy -> probando aUSIPY (monthly)
2026-03-25 01:46:03,442 P[19164] [MainThread 20064] [macro] indpro_yoy -> probando aUSIPY (monthly)
2026-03-25 01:46:04,052 P[19164] [MainThread 20064] Error with aUSIPY: TimeSeries request failed
2026-03-25 01:46:04,053 P[19164] [MainThread 20064] aUSIPY: TimeSeries request failed |
2026-03-25 01:46:04 | WARNING | [macro] error indpro_yoy/aUSIPY: EikonError: Error code -1 | aUSIPY: TimeSeries request failed |
2026-03-25 01:46:04,054 P[19164] [MainThread 20064] [macro] error indpro_yoy/aUSIPY: EikonError: Error code -1 | aUSIPY: TimeSeries request failed |
2026-03-25 01:46:04 | INFO | [macro] indpro_yoy -> probando USIP=ECI (monthly)
2026-03-25 01:46:04,455 P[19164] [MainThread 20064] [macro] indpro_yoy -> probando USIP=ECI (monthly)
2026-03-25 01:46:05 | WARNING | [macro] sin cobertura para indpro_yoy
2026-03-25 01:46:05,810 P[19164] [MainThread 20064] [macro] sin cobertura para indpro_yoy
2026-03-25 01:46:06 | INFO | Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/raw/macro_controls_daily.parquet | rows=2,863 cols=4
2026-03-25 01:46:06,320 P[19164] [MainThread 20064] Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/raw/macro_controls_daily.parquet | rows=2,863 cols=4
2026-03-25 01:46:06 | INFO | Output raw macro -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/raw/macro_controls_daily.csv
2026-03-25 01:46:06,332 P[19164] [MainThread 20064] Output raw macro -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/raw/macro_controls_daily.csv
2026-03-25 01:46:06 | INFO | Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/clean/macro_controls_monthly.parquet | rows=132 cols=15
2026-03-25 01:46:06,425 P[19164] [MainThread 20064] Output -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/clean/macro_controls_monthly.parquet | rows=132 cols=15
2026-03-25 01:46:06 | INFO | Output monthly macro -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/clean/macro_controls_monthly.csv
2026-03-25 01:46:06,433 P[19164] [MainThread 20064] Output monthly macro -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/clean/macro_controls_monthly.csv
2026-03-25 01:46:06 | INFO | Output sources      -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/clean/macro_controls_sources.csv
2026-03-25 01:46:06,435 P[19164] [MainThread 20064] Output sources      -> C:/Users/vidar/OneDrive/Desktop/UDESA/Tesis/Tesis-main/data/clean/macro_controls_sources.csv

=== RESUMEN CONTROLES MACRO ===
Columnas disponibles:
['date', 'policy_rate', 'term_spread_10y_2y', 'move_eom', 'ust_3m', 'ust_2y', 'ust_10y', 'term_spread_10y_3m', 'US1M', 'US1Y', 'US30Y', 'US3Y', 'US5Y', 'US6M', 'US7Y']

Cobertura no nula por variable:
date                  132
policy_rate           132
term_spread_10y_2y    132
move_eom              132
ust_3m                132
ust_2y                132
ust_10y               132
term_spread_10y_3m    132
US1M                  132
US1Y                  132
US30Y                 132
US3Y                  132
US5Y                  132
US6M                  132
US7Y                  132
dtype: int64

Primeras filas:

,date,policy_rate,term_spread_10y_2y,move_eom,ust_3m,ust_2y,ust_10y,term_spread_10y_3m,US1M,US1Y,US30Y,US3Y,US5Y,US6M,US7Y
0,2015-01-31,0.25,1.208,86.6,0.013,0.472,1.68,1.667,0.005,0.147,2.258,0.768,1.19,0.051,1.496
1,2015-02-28,0.25,1.376,91.4,0.015,0.626,2.002,1.987,0.018,0.193,2.6,1.0,1.504,0.074,1.823
2,2015-03-31,0.25,1.375,86.1,0.036,0.559,1.934,1.898,0.018,0.229,2.543,0.882,1.375,0.137,1.714
3,2015-04-30,0.25,1.465,75.3,0.005,0.579,2.044,2.039,-0.003,0.232,2.752,0.914,1.44,0.038,1.804
4,2015-05-31,0.25,1.49,82.7,0.003,0.605,2.095,2.092,0.008,0.25,2.847,0.922,1.469,0.064,1.844

Fuentes / RICs usados:

      variable     ric_used download_status frequency_requested
0          vix         None         missing               daily
1         move        .MOVE              ok               daily
2  policy_rate  USFFTARGET=              ok             monthly
3      cpi_yoy         None         missing             monthly
4   indpro_yoy         None         missing             monthly